# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 12:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedproductdiscount',
            name='percentage_discount',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='fixedproductdiscount',
            name='discount',
            field=django_prices.models.PriceField(blank=True, currency='USD', decimal_places=2, max_digits=12, null=True, verbose_name='discount value'),
        ),
    ]
