# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20160112_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='discount',
        ),
        migrations.AddField(
            model_name='discount',
            name='type',
            field=models.CharField(choices=[('fixed', 'Fixed amount'), ('percentage', 'Percentage discount')], default='fixed', max_length=10),
        ),
        migrations.AddField(
            model_name='discount',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Value for a discount. It could be fixed amount or percentage value in range 0-100', max_digits=12),
        ),
    ]
