# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_fixedproductdiscount_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('fixed', 'Fixed amount'), ('percentage', 'Percentage discount')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, help_text='Value for a discount. It could be fixed amount or percentage value in range 0-100', max_digits=12)),
                ('categories', models.ManyToManyField(blank=True, to='product.Category')),
                ('products', models.ManyToManyField(blank=True, to='product.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='fixedproductdiscount',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='fixedproductdiscount',
            name='products',
        ),
        migrations.DeleteModel(
            name='FixedProductDiscount',
        ),
    ]
