# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20160112_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='apply_on',
            field=models.CharField(choices=[('products', 'Products'), ('categories', 'Categories'), ('both', 'Both products and categories')], default='both', max_length=10),
        ),
    ]
