# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 00:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_prices.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20160218_0812'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('has_variants', models.BooleanField(default=True, verbose_name='has variants')),
                ('is_shipping_required', models.BooleanField(default=False, verbose_name='is shipping required')),
            ],
            options={
                'verbose_name_plural': 'product classes',
                'verbose_name': 'product class',
            },
        ),
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='location')),
            ],
        ),
        migrations.AlterModelOptions(
            name='attributechoicevalue',
            options={'verbose_name': 'attribute choices value', 'verbose_name_plural': 'attribute choices values'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelOptions(
            name='productattribute',
            options={'ordering': ('name',), 'verbose_name': 'product attribute', 'verbose_name_plural': 'product attributes'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ('order',), 'verbose_name': 'product image', 'verbose_name_plural': 'product images'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'verbose_name': 'product variant', 'verbose_name_plural': 'product variants'},
        ),
        migrations.AlterModelOptions(
            name='variantimage',
            options={'verbose_name': 'variant image', 'verbose_name_plural': 'variant images'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='weight_override',
        ),
        migrations.AddField(
            model_name='attributechoicevalue',
            name='slug',
            field=models.SlugField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='is featured'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=django_prices.models.PriceField(currency='EUR', decimal_places=2, max_digits=12, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(upload_to='products', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='order',
            field=models.PositiveIntegerField(editable=False, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='ppoi'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.Product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='images',
            field=models.ManyToManyField(through='product.VariantImage', to='product.ProductImage', verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price_override',
            field=django_prices.models.PriceField(blank=True, currency='EUR', decimal_places=2, max_digits=12, null=True, verbose_name='price override'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='cost_price',
            field=django_prices.models.PriceField(blank=True, currency='EUR', decimal_places=2, max_digits=12, null=True, verbose_name='cost price'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.StockLocation'),
        ),
        migrations.AlterField(
            model_name='variantimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_images', to='product.ProductImage', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='variantimage',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_images', to='product.ProductVariant', verbose_name='variant'),
        ),
        migrations.RemoveField(
            model_name='attributechoicevalue',
            name='image',
        ),
        migrations.AlterUniqueTogether(
            name='attributechoicevalue',
            unique_together=set([('display', 'attribute')]),
        ),
        migrations.AddField(
            model_name='productclass',
            name='product_attributes',
            field=models.ManyToManyField(blank=True, related_name='products_class', to='product.ProductAttribute', verbose_name='product attributes'),
        ),
        migrations.AddField(
            model_name='productclass',
            name='variant_attributes',
            field=models.ManyToManyField(blank=True, related_name='product_variants_class', to='product.ProductAttribute', verbose_name='variant attributes'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_class',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.ProductClass', verbose_name='product class'),
            preserve_default=False,
        ),
    ]
