# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("product", "0013_auto_20161130_0608")]

    operations = [
        migrations.RemoveField(model_name="productvariant", name="attributes")
    ]
