# Generated by Django 1.10.3 on 2016-12-21 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0025_auto_20161219_0517"),
        ("product", "0018_auto_20161212_0725"),
    ]

    operations = []
