# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_auto_20161219_0517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('products', models.ManyToManyField(to='product.Product')),
            ],
        ),
        migrations.AlterField(
            model_name='stocklocation',
            name='name',
            field=models.CharField(max_length=100, verbose_name='location'),
        ),
    ]
