# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_auto_20161230_0347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='name')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('products', models.ManyToManyField(blank=True, to='product.Product')),
            ],
        ),
    ]
