# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_auto_20170113_0435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='name')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('products', models.ManyToManyField(blank=True, to='product.Product')),
            ],
        ),
    ]
