# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0026_merge_20161221_0845"),
        ("product", "0027_auto_20170113_0435"),
    ]

    operations = []
