# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_merge_20170116_1016'),
        ('product', '0028_collection'),
    ]

    operations = [
    ]
