# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='productclass',
            name='vat_rate_type',
            field=models.CharField(blank=True, max_length=60, verbose_name='vat rate type'),
        ),
    ]
