# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_product_is_featured'),
        ('product', '0029_merge_20170117_0754'),
    ]

    operations = [
    ]
