# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_attributechoicevaluetranslation_productattributetranslation_producttranslation_productvarianttransla'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productattributetranslation',
            old_name='display',
            new_name='name',
        ),
    ]
