# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_auto_20171115_0608'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeChoiceValueTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=35, verbose_name='language code')),
                ('name', models.CharField(max_length=100, verbose_name='display name')),
                ('attribute_choice_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='product.AttributeChoiceValue', verbose_name='product attribute')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttributeTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=35, verbose_name='language code')),
                ('name', models.CharField(max_length=100, verbose_name='display name')),
                ('product_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='product.ProductAttribute', verbose_name='product attribute')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=50, verbose_name='language code')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='product.Product', verbose_name='product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariantTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=35, verbose_name='language code')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='variant name')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='product.ProductVariant', verbose_name='product variant')),
            ],
        ),
    ]
