# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_auto_20170320_0623'),
        ('product', '0035_auto_20170919_0846'),
    ]

    operations = [
    ]
