# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 10:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_auto_20170906_0859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': (('view', 'View in Dashboard'), ('edit', 'Edit in Dashboard')), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': (('view', 'View in Dashboard'), ('edit', 'Edit in Dashboard')), 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
