# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_auto_20170907_0527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocklocation',
            options={'permissions': (('view_stocklocation', 'Can View Category in Dashboard'), ('edit_stocklocation', 'Can Edit Category in Dashboard'))},
        ),
    ]
