# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0039_auto_20170907_0816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocklocation',
            options={'permissions': (('view_stock_location', 'Can View Category in Dashboard'), ('edit_stock_location', 'Can Edit Category in Dashboard'))},
        ),
    ]
