# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0040_auto_20170907_0818'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocklocation',
            options={'permissions': (('view_stock_location', 'Can View Stock Location in Dashboard'), ('edit_stock_location', 'Can Edit Stock Location in Dashboard'))},
        ),
    ]
