# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-06 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("product", "0041_auto_20171205_0546")]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="is_hidden",
            field=models.BooleanField(default=False, verbose_name="is hidden"),
        )
    ]
