# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0042_auto_20171206_0501'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='product_pro_name_5bb6fa_gin',
        ),
    ]
