# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_product_is_published'),
        ('product', '0042_auto_20170912_0401'),
    ]

    operations = [
    ]
