# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-15 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0044_auto_20180108_0814'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductClass',
            new_name='ProductType',
        ),
    ]
