# Generated by Django 1.11.9 on 2018-01-15 11:16

from django.db import migrations


class Migration(migrations.Migration):
    """No-op kept only to preserve the migration graph.

    This migration used to render every product's Markdown description to HTML
    (a per-row Python loop over the whole table). Descriptions have since been
    converted to editorjs JSON, so replaying it on a fresh database is pointless
    and on an existing one it already ran. Emptying it drops the `markdown`
    runtime dependency.
    """

    dependencies = [("product", "0044_auto_20180108_0814")]

    operations = []
