# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-15 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0045_auto_20180115_0428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_class',
            new_name='product_type',
        ),
        migrations.AlterField(
            model_name='producttype',
            name='product_attributes',
            field=models.ManyToManyField(blank=True, related_name='product_types', to='product.ProductAttribute'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='variant_attributes',
            field=models.ManyToManyField(blank=True, related_name='product_variant_types', to='product.ProductAttribute'),
        ),
    ]
