# Generated by Django 1.11.5 on 2018-01-31 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("product", "0049_collection")]

    operations = [
        migrations.AlterField(
            model_name="collection", name="slug", field=models.SlugField(max_length=255)
        )
    ]
