# Generated by Django 2.0.3 on 2018-04-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0056_auto_20180330_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='charge_taxes',
            field=models.BooleanField(default=True),
        ),
    ]
