# Generated by Django 2.0.3 on 2018-05-15 17:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0059_generate_variant_name_from_attrs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, validators=[django.core.validators.MaxLengthValidator(64)])),
            ],
        ),
        migrations.AddField(
            model_name='productvariant',
            name='vendor_sku',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.ProductVendor'),
        ),
    ]
