# Generated by Django 2.0.3 on 2018-05-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0062_nullable_attr_value_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributechoicevalue',
            name='sort_order',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
