# Generated by Django 2.0.3 on 2018-05-17 03:33

from django.db import migrations
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0063_required_attr_value_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=django_prices.models.MoneyField(currency='USD', decimal_places=2, max_digits=12, verbose_name='Price'),
        ),
    ]
