# Generated by Django 2.1.4 on 2019-01-04 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0082_merge_20181219_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ('slug',)},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'permissions': (('manage_products', 'Manage products.'),)},
        ),
    ]
