# Generated by Django 2.2 on 2019-04-19 09:55

import django.core.validators
from django.db import migrations, models
import re
import saleor.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0091_auto_20190402_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributevalue',
            name='slug',
            field=models.SlugField(max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid'), saleor.core.validators.validate_empty_slug]),
        ),
    ]
