# Generated by Django 2.2.2 on 2019-06-11 14:52

from django.db import migrations, models
from django.db.models import Count


def ensure_attribute_slugs_are_unique_or_fix(apps, schema_editor):
    Attribute = apps.get_model("product", "Attribute")  # noqa
    non_unique_slugs = (
        Attribute.objects.values_list("slug", flat=True)
        .annotate(slug_count=Count("slug"))
        .filter(slug_count__gt=1)
    )
    non_unique_attrs = Attribute.objects.filter(slug__in=list(non_unique_slugs))
    for suffix, attr in enumerate(non_unique_attrs):
        attr.slug += f"__{suffix}"
        attr.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [("product", "0093_auto_20190521_0124")]

    operations = [
        migrations.RunPython(ensure_attribute_slugs_are_unique_or_fix),
        migrations.AlterField(
            model_name="attribute", name="slug", field=models.SlugField(unique=True)
        ),
    ]
