# Generated by Django 2.2.1 on 2019-05-30 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0094_auto_20190530_0511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='attribute_category',
        ),
        migrations.DeleteModel(
            name='AttributeCategory',
        ),
    ]
