# Generated by Django 2.2.6 on 2020-05-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0095_auto_20200509_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
    ]
