# Generated by Django 2.2.3 on 2019-07-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0095_auto_20190618_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_visible',
            field=models.CharField(choices=[('public', 'Everyone'), ('customer', 'Customers and staff'), ('staff', 'Staff only')], default='public', max_length=128),
        ),
    ]
