# Generated by Django 2.2.6 on 2020-05-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0096_product_sku'),
    ]

    def add_sku_variant_in_products(apps, schema_editor):

        Product = apps.get_model('product', 'Product')
        ProductVariant = apps.get_model('product', 'ProductVariant')

        variants = ProductVariant.objects.all()

        for variant in variants:
            product = Product.objects.get(
                id = variant.id
            )
            product.sku = variant.sku
            product.save()
    
    operations = [
        migrations.RunPython(add_sku_variant_in_products)
    ]
