# Generated by Django 2.2.3 on 2019-07-19 13:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0096_raw_html_to_json"),
        ("product", "0099_auto_20190719_0745"),
    ]

    operations = []
