# Generated by Django 2.2.3 on 2019-07-17 11:26

from django.db import migrations, models
from django.db.models import Max


def _set_default_position(qs):
    existing_max = qs.aggregate(Max("sort_order"))
    existing_max = existing_max.get("sort_order__max") or 0

    for sort_order, item in enumerate(qs.filter(sort_order=None), existing_max + 1):
        item.sort_order = sort_order
        item.save(update_fields=["sort_order"])


def set_default_position_m2m(model_name, fk_name):
    def _wrapped(apps, schema_editor):
        attribute_m2m = apps.get_model("product", model_name)
        foreigners = attribute_m2m.objects.distinct().values_list(fk_name, flat=True)

        for pk in foreigners:
            _set_default_position(attribute_m2m.objects.filter(**{fk_name: pk}))

    return _wrapped


def set_default_position_m2o(model_name):
    def _wrapped(apps, schema_editor):
        attribute_m2m = apps.get_model("product", model_name)
        _set_default_position(attribute_m2m.objects)

    return _wrapped


class Migration(migrations.Migration):

    dependencies = [("product", "0099_auto_20190626_0815")]

    operations = [
        # m2m models
        migrations.RunPython(
            set_default_position_m2m("AttributeProduct", "product_type_id")
        ),
        migrations.RunPython(
            set_default_position_m2m("AttributeVariant", "product_type_id")
        ),
        migrations.RunPython(
            set_default_position_m2m("CollectionProduct", "collection_id")
        ),
        # m2o models
        migrations.RunPython(set_default_position_m2o("AttributeValue")),
        migrations.RunPython(set_default_position_m2o("ProductImage")),
        # drop nulls
        migrations.AlterField(
            model_name="attributeproduct",
            name="sort_order",
            field=models.PositiveIntegerField(
                db_index=True, editable=False, default=0, null=False
            ),
        ),
        migrations.AlterField(
            model_name="attributevariant",
            name="sort_order",
            field=models.PositiveIntegerField(
                db_index=True, editable=False, default=0, null=False
            ),
        ),
        migrations.AlterField(
            model_name="collectionproduct",
            name="sort_order",
            field=models.PositiveIntegerField(
                db_index=True, editable=False, default=0, null=False
            ),
        ),
        migrations.AlterField(
            model_name="attributevalue",
            name="sort_order",
            field=models.PositiveIntegerField(
                db_index=True, editable=False, default=0, null=False
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="sort_order",
            field=models.PositiveIntegerField(
                db_index=True, editable=False, default=0, null=False
            ),
        ),
    ]
