# Generated by Django 2.2.2 on 2019-06-10 10:25

from django.db import migrations, models

from saleor.core.fields import FilterableJSONBField
from saleor.product.models import validate_attribute_json


def migrate_attributes_to_list(model_name):
    def make_migration(apps, schema):
        Model = apps.get_model("product", model_name)

        for instance in Model.objects.all():
            new_attributes = {}

            for k, v in instance.attributes.items():
                if not isinstance(v, list):
                    new_attributes[k] = [v]
                else:
                    new_attributes[k] = v

            instance.attributes = new_attributes
            instance.save(update_fields=["attributes"])

    return make_migration


class Migration(migrations.Migration):

    dependencies = [("product", "0103_migrate_attrs_to_m2m")]

    operations = [
        migrations.AddField(
            model_name="attribute",
            name="input_type",
            field=models.CharField(
                choices=[("dropdown", "Dropdown"), ("multiselect", "Multi Select")],
                default="dropdown",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="attributes",
            field=FilterableJSONBField(
                blank=True, default=dict, validators=[validate_attribute_json]
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="attributes",
            field=FilterableJSONBField(
                blank=True, default=dict, validators=[validate_attribute_json]
            ),
        ),
        migrations.RunPython(migrate_attributes_to_list("Product")),
        migrations.RunPython(migrate_attributes_to_list("ProductVariant")),
    ]
