# Generated by Django 2.2.1 on 2019-06-10 11:23

import django_prices.models
from django.db import migrations


def populate_product_minimal_variant_price(apps, schema_editor):
    Product = apps.get_model("product", "Product")
    for product in Product.objects.prefetch_related("variants").iterator():
        # Set the "minimal variant price" to the default product's price
        product.minimal_variant_price = product.price
        product.save(update_fields=["minimal_variant_price"])


class Migration(migrations.Migration):

    dependencies = [("product", "0104_fix_invalid_attributes_map")]

    operations = [
        migrations.AddField(
            model_name="product",
            name="minimal_variant_price",
            field=django_prices.models.MoneyField(
                currency="USD", decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.RunPython(
            populate_product_minimal_variant_price,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="product",
            name="minimal_variant_price",
            field=django_prices.models.MoneyField(
                currency="USD", decimal_places=2, max_digits=12
            ),
        ),
    ]
