# Generated by Django 2.2.7 on 2019-12-09 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("product", "0110_auto_20191108_0340"), ("stock", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="productvariant", name="quantity"),
        migrations.RemoveField(model_name="productvariant", name="quantity_allocated"),
    ]
