# Generated by Django 2.2.7 on 2019-12-09 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("product", "0111_auto_20191209_0349")]

    operations = [
        migrations.RemoveField(model_name="productvariant", name="quantity"),
        migrations.RemoveField(model_name="productvariant", name="quantity_allocated"),
    ]
