# Generated by Django 2.2.9 on 2020-01-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0111_auto_20191209_0437"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttype",
            name="slug",
            field=models.SlugField(default="", unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name="collection",
            name="slug",
            field=models.SlugField(max_length=128, unique=True),
        ),
    ]
