# Generated by Django 2.2.9 on 2020-01-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0112_auto_20200129_0050"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attribute", name="name", field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="attribute",
            name="slug",
            field=models.SlugField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name="attributevalue",
            name="name",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="attributevalue",
            name="slug",
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name="category", name="name", field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="collection",
            name="name",
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name="collection",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="name",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
