# Generated by Django 2.2.9 on 2020-01-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0113_auto_20200129_0717"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(default="", max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product", name="name", field=models.CharField(max_length=250),
        ),
    ]
