# Generated by Django 2.2.10 on 2020-02-17 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0114_auto_20200129_0815"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="producttype", options={"ordering": ("slug",)},
        ),
        migrations.AlterModelOptions(
            name="productvariant", options={"ordering": ("sku",)},
        ),
    ]
