# Generated by Django 3.0.6 on 2020-06-16 09:05

from django.db import migrations, models
import draftjs_sanitizer
import saleor.core.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0117_auto_20200423_0737"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="description_json",
            field=saleor.core.db.fields.SanitizedJSONField(
                blank=True, default=dict, sanitizer=draftjs_sanitizer.clean_draft_js
            ),
        ),
        migrations.AddField(
            model_name="productvarianttranslation",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="productvarianttranslation",
            name="description_json",
            field=saleor.core.db.fields.SanitizedJSONField(
                blank=True, default=dict, sanitizer=draftjs_sanitizer.clean_draft_js
            ),
        ),
    ]
