# Generated by Django 3.0.6 on 2020-07-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0120_auto_20200714_0539"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productvariant", options={"ordering": ("sort_by_attributes",)},
        ),
        migrations.AddField(
            model_name="productvariant",
            name="sort_by_attributes",
            field=models.IntegerField(db_index=True, editable=False, null=True),
        ),
    ]
