# Generated by Django 3.0.6 on 2020-07-14 13:44

from django.db import migrations


def sort_all_productvariants(apps, schema_editor):
    from ..tasks import update_productvariant_sorting

    ProductType = apps.get_model("product", "ProductType")
    product_types = ProductType.objects.all().values_list("pk", flat=True)
    for product_type in product_types:
        update_productvariant_sorting(product_type=product_type)


def remove_productvariants_sorting(apps, schema_editor):
    ProductVariant = apps.get_model("product", "ProductVariant")
    ProductVariant.objects.all().update(sort_by_attributes=None)


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0121_auto_20200714_1327"),
    ]

    operations = [
        migrations.RunPython(
            sort_all_productvariants, reverse_code=remove_productvariants_sorting
        )
    ]
