# Generated by Django 3.0.6 on 2020-07-16 09:34

import django.db.models.deletion
from django.db import migrations, models


def migrate_variant_price_data(apps, schema_editor):
    Channel = apps.get_model("channel", "Channel")
    ProductVariant = apps.get_model("product", "ProductVariant")
    ProductVariantChannelListing = apps.get_model(
        "product", "ProductVariantChannelListing"
    )

    if ProductVariant.objects.exists():
        channels_dict = {}

        for variant in ProductVariant.objects.iterator():
            currency = variant.currency
            channel = channels_dict.get(currency)
            if not channel:
                channel, _ = Channel.objects.get_or_create(
                    currency_code=currency,
                    defaults={
                        "name": f"Channel {currency}",
                        "slug": f"channel-{currency.lower()}",
                    },
                )
                channels_dict[currency] = channel
            ProductVariantChannelListing.objects.create(
                variant=variant,
                channel=channel,
                currency=currency,
                price_amount=variant.price_amount,
            )


class Migration(migrations.Migration):

    dependencies = [
        # TODO: Change dependencies after merge
        # #5818(Add product availability in channel)
        ("channel", "0001_initial"),
        ("product", "0121_productchannellisting"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductVariantChannelListing",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.CharField(max_length=3,),),
                ("price_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variant_listing",
                        to="channel.Channel",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_listing",
                        to="product.ProductVariant",
                    ),
                ),
            ],
            options={"ordering": ("pk",), "unique_together": {("variant", "channel")}},
        ),
        migrations.RunPython(migrate_variant_price_data),
        migrations.RemoveField(model_name="productvariant", name="price_amount",),
    ]
