# Generated by Django 3.1 on 2020-09-04 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0122_auto_20200828_1135"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="variantimage", unique_together={("variant", "image")},
        ),
    ]
