# Generated by Django 3.1.1 on 2020-09-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0124_auto_20200909_0904"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="default",
            field=models.BooleanField(default=False),
        ),
    ]
