# Generated by Django 3.1.1 on 2020-09-21 08:03

from django.db import migrations, models


def set_default_variants(apps, schema_editor):
    Product = apps.get_model("product", "Product")

    for product in Product.objects.prefetch_related("variants"):
        first_variant = product.variants.first()
        if first_variant:
            first_variant.default = True


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0125_auto_20200916_1511"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="default",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            set_default_variants, reverse_code=migrations.RunPython.noop
        ),
    ]
