# Generated by Django 3.1.1 on 2020-09-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0125_auto_20200916_1511"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="default",
            field=models.BooleanField(default=False),
        ),
    ]
