# Generated by Django 3.1 on 2020-10-01 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0126_product_default_variant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="default_variant",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="product.productvariant",
            ),
        ),
    ]
