# Generated by Django 3.1 on 2020-10-06 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0127_auto_20201001_0933"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="producttype",
            options={
                "ordering": ("slug",),
                "permissions": (
                    (
                        "manage_product_types_and_attributes",
                        "Manage product types and attributes.",
                    ),
                ),
            },
        ),
    ]
