# Generated by Django 3.1 on 2020-08-28 08:36

from django.db import migrations, models


def migrate_minimal_variant_price_data(apps, schema_editor):
    Channel = apps.get_model("channel", "Channel")
    Product = apps.get_model("product", "Product")
    ProductChannelListing = apps.get_model("product", "ProductChannelListing")

    channels_dict = {}
    for product in Product.objects.iterator():
        currency = product.currency
        channel = channels_dict.get(currency)
        if not channel:
            channel, _ = Channel.objects.get_or_create(
                currency_code=currency,
                defaults={
                    "name": f"Channel {currency}",
                    "slug": f"channel-{currency.lower()}",
                },
            )
            channels_dict[currency] = channel
        ProductChannelListing.objects.update_or_create(
            product=product,
            channel=channel,
            defaults={
                "currency": currency,
                "discounted_price_amount": product.minimal_variant_price_amount,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0127_productchannellisting"),
    ]

    operations = [
        migrations.AddField(
            model_name="productchannellisting",
            name="currency",
            field=models.CharField(default="", max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productchannellisting",
            name="discounted_price_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.RunPython(migrate_minimal_variant_price_data),
        migrations.RemoveField(model_name="product", name="currency",),
        migrations.RemoveField(
            model_name="product", name="minimal_variant_price_amount",
        ),
    ]
