# Generated by Django 3.1 on 2020-10-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0013_pagetype"),
        ("product", "0128_attribute_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="attribute",
            name="page_types",
            field=models.ManyToManyField(
                blank=True, related_name="attributes", to="page.PageType"
            ),
        ),
    ]
