# Generated by Django 3.1.2 on 2020-10-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0129_add_product_types_and_attributes_perm"),
    ]

    operations = [
        migrations.AddField(
            model_name="product", name="rating", field=models.FloatField(default=0.0),
        ),
    ]
