# Generated by Django 3.1 on 2020-09-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0131_refactor_minimal_variant_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productchannellisting",
            name="discounted_price_amount",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="productvariantchannellisting",
            name="price_amount",
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
    ]
