# Generated by Django 3.1 on 2020-10-12 11:29

import os

import django.db.models.deletion
from django.db import migrations, models


def create_collection_channel_listing(apps, schema_editor):
    CollectionChannelListing = apps.get_model("product", "CollectionChannelListing")
    Collection = apps.get_model("product", "Collection")
    Channel = apps.get_model("channel", "Channel")

    if Collection.objects.exists():
        currency = os.environ.get("DEFAULT_CURRENCY", "USD")
        channel, _ = Channel.objects.get_or_create(
            currency_code=currency,
            defaults={
                "name": f"Channel {currency}",
                "slug": f"channel-{currency.lower()}",
            },
        )
        for collection in Collection.objects.iterator():

            CollectionChannelListing.objects.create(
                collection=collection,
                channel=channel,
                is_published=collection.is_published,
                publication_date=collection.publication_date,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("channel", "0002_channel_availability"),
        ("product", "0135_auto_20201006_0635"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionChannelListing",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("is_published", models.BooleanField(default=False)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_listing",
                        to="channel.channel",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_listing",
                        to="product.collection",
                    ),
                ),
            ],
            options={
                "ordering": ("pk",),
                "unique_together": {("collection", "channel")},
            },
        ),
        migrations.RunPython(
            create_collection_channel_listing, migrations.RunPython.noop
        ),
        migrations.RemoveField(model_name="collection", name="is_published",),
        migrations.RemoveField(model_name="collection", name="publication_date",),
    ]
