# Generated by Django 3.1 on 2020-11-03 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    # TODO squash before merging multicurrency into master
    dependencies = [
        ("channel", "0003_auto_20201015_1107"),
        ("product", "0138_auto_20201102_1132"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionchannellisting",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collection_listings",
                to="channel.channel",
            ),
        ),
        migrations.AlterField(
            model_name="collectionchannellisting",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channel_listings",
                to="product.collection",
            ),
        ),
    ]
