# Generated by Django 3.1.5 on 2021-02-12 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0138_migrate_description_json_into_description"),
    ]
    operations = []
