# Generated by Django 3.1.5 on 2021-02-12 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0139_description_vector_search"),
        ("product", "0140_auto_20210125_0905"),
    ]

    operations = []
