# Generated by Django 3.1.5 on 2021-01-25 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0140_auto_20210125_0905"),
    ]

    operations = [
        migrations.RunSQL(
            """
            DROP TRIGGER title_vector_update ON product_product;
            """
        ),
        migrations.RunSQL(
            """
            CREATE TRIGGER title_vector_update BEFORE INSERT OR UPDATE
            ON product_product FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(
                'search_vector', 'pg_catalog.english', 'description_plaintext', 'name'
            )
            """
        ),
        migrations.RunSQL(
            """
            CREATE FUNCTION product_trigger() RETURNS trigger AS $$
            begin
              new.search_vector :=
                 setweight(
                 to_tsvector('pg_catalog.english', coalesce(new.name,'')), 'A'
                 ) ||
                 setweight(
                 to_tsvector(
                 'pg_catalog.english', coalesce(new.description_plaintext,'')),
                 'B'
                 );
              return new;
            end
            $$ LANGUAGE plpgsql;
            CREATE TRIGGER tsvectorupdate BEFORE INSERT OR UPDATE
                ON product_product FOR EACH ROW EXECUTE FUNCTION product_trigger();
            """
        ),
    ]
