# Generated by Django 3.1.7 on 2021-03-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0141_update_descritpion_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariantchannellisting",
            name="price_amount",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=12, null=True
            ),
        ),
    ]
