# Generated by Django 3.2.5 on 2021-07-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0146_auto_20210518_0945"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttype",
            name="kind",
            field=models.CharField(
                choices=[
                    ("normal", "A standard product type."),
                    ("gift_card", "A gift card product type."),
                ],
                default="normal",
                max_length=32,
            ),
            preserve_default=False,
        ),
    ]
