# Generated by Django 3.2.5 on 2021-08-01 11:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0146_auto_20210518_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariantSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_interval', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(1)])),
                ('billing_period', models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], default='day', max_length=128)),
                ('trial_interval', models.IntegerField(default=0)),
                ('trial_period', models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], default='day', max_length=128)),
                ('length', models.IntegerField(default=0)),
                ('limit', models.CharField(choices=[('no', 'No'), ('active', 'Active'), ('any', 'Any')], default='no', max_length=128)),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='product.productvariant')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
