# Generated by Django 3.2.7 on 2021-10-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0149_alter_productvariant_sku"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="is_preorder",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="preorder_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="preorder_global_threshold",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productvariantchannellisting",
            name="preorder_quantity_threshold",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
