# Generated by Django 3.2.6 on 2021-10-08 10:49

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0150_collection_collection_search_gin"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="productvariant",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["sku", "name"],
                name="product_variant_search_gin",
                opclasses=["gin_trgm_ops", "gin_trgm_ops"],
            ),
        ),
    ]
