# Generated by Django 3.2.7 on 2021-10-19 12:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0151_merge_20211004_1344"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="quantity_limit_per_customer",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
