# Generated by Django 3.2.12 on 2022-05-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0151_productchannellisting_product_pro_discoun_3145f3_btree'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='original_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='original_sku',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
