# Generated by Django 3.2.6 on 2021-10-06 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0150_collection_collection_search_gin"),
        ("product", "0152_merge_20211005_1324"),
    ]

    operations = []
