# Generated by Django 3.2.6 on 2021-12-27 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0156_product_search_document"),
    ]

    operations = []
