# Generated by Django 3.2.12 on 2022-02-22 11:07

from django.db import migrations
from django.db.models import Exists, OuterRef, Subquery
from django.db.models.fields import IntegerField
from django.db.models.functions import Coalesce


def clean_product_channel_listings(apps, schema_editor):
    """Drop ProductChannelListing for channels where no available variant exists."""
    ProductVariant = apps.get_model("product", "ProductVariant")
    ProductChannelListing = apps.get_model("product", "ProductChannelListing")
    ProductVariantChannelListing = apps.get_model(
        "product", "ProductVariantChannelListing"
    )

    variant_subquery = Subquery(
        queryset=ProductVariant.objects.filter(id=OuterRef("variant_id")).values(
            "product_id"
        ),
        output_field=IntegerField(),
    )
    variant_channel_listings = ProductVariantChannelListing.objects.annotate(
        product_id=Coalesce(variant_subquery, 0)
    )

    # get ProductChannelListings for which there is no ProductVariantChannelListing
    # for the ProductChannelListing channel
    invalid_product_channel_listings = ProductChannelListing.objects.exclude(
        Exists(
            variant_channel_listings.filter(
                channel_id=OuterRef("channel_id"), product_id=OuterRef("product_id")
            )
        )
    )

    invalid_product_channel_listings.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0158_auto_20220120_1633"),
    ]

    operations = [
        migrations.RunPython(
            clean_product_channel_listings,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
