# Generated by Django 3.2.12 on 2022-02-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0161_auto_20220209_1511"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="created",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="updated_at",
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
