# Generated by Django 3.2.12 on 2022-02-09 15:17

from django.db import migrations
from django.utils import timezone


def populate_products_variants_datetimes(apps, _schema_editor):
    timestamp = timezone.now()

    ProductVariant = apps.get_model("product", "ProductVariant")
    ProductVariant.objects.update(created=timestamp, updated_at=timestamp)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("product", "0162_auto_20220209_1517"),
    ]

    operations = [
        migrations.RunPython(
            populate_products_variants_datetimes,
            migrations.RunPython.noop,
        ),
    ]
