# Generated by Django 3.2.12 on 2022-04-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0163_auto_20220414_1025"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionchannellisting",
            name="publication_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productchannellisting",
            name="available_for_purchase",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productchannellisting",
            name="publication_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
