# Generated by Django 3.2.12 on 2022-04-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0164_auto_20220419_0910"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="productchannellisting",
            name="product_pro_publica_67290c_idx",
        ),
        migrations.RenameField(
            model_name="collectionchannellisting",
            old_name="publication_date",
            new_name="published_at",
        ),
        migrations.RenameField(
            model_name="productchannellisting",
            old_name="available_for_purchase",
            new_name="available_for_purchase_at",
        ),
        migrations.RenameField(
            model_name="productchannellisting",
            old_name="publication_date",
            new_name="published_at",
        ),
        migrations.AddIndex(
            model_name="productchannellisting",
            index=models.Index(
                fields=["published_at"], name="product_pro_publish_a3c049_idx"
            ),
        ),
    ]
