# Generated by Django 3.2.12 on 2022-04-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0165_update_product_search_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionchannellisting",
            name="publication_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productchannellisting",
            name="available_for_purchase",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productchannellisting",
            name="publication_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveIndex(
            model_name="productchannellisting",
            name="product_pro_publica_67290c_idx",
        ),
        migrations.RenameField(
            model_name="collectionchannellisting",
            old_name="publication_date",
            new_name="published_at",
        ),
        migrations.RenameField(
            model_name="productchannellisting",
            old_name="available_for_purchase",
            new_name="available_for_purchase_at",
        ),
        migrations.RenameField(
            model_name="productchannellisting",
            old_name="publication_date",
            new_name="published_at",
        ),
        migrations.AddIndex(
            model_name="productchannellisting",
            index=models.Index(
                fields=["published_at"], name="product_pro_publish_a3c049_idx"
            ),
        ),
    ]
