# Generated by Django 3.2.12 on 2022-04-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0166_update_publication_date_and_available_for_purchase"),
    ]

    operations = [
        migrations.AddField(
            model_name="digitalcontenturl",
            name="order_line_token",
            field=models.UUIDField(null=True),
        ),
    ]
