# Generated by Django 3.2.13 on 2022-07-18 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0171_alter_versatile_images"),
        ("product", "0171_auto_20220527_1222"),
    ]

    operations = []
