# Generated by Django 3.2.16 on 2022-11-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0172_alter_product_search_index_dirty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariantchannellisting',
            name='cost_price_amount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
    ]
