# Generated by Django 3.2.14 on 2022-08-09 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0172_merge_20220718_1354"),
        ("product", "0173_create_default_category_and_product_type"),
    ]

    operations = []
