# Generated by Django 3.2.13 on 2022-07-19 10:33

from django.db import migrations

from ...core.tasks import delete_files_from_storage_task


def drop_media_to_remove(apps, _schema_editor):
    ProductMedia = apps.get_model("product", "ProductMedia")
    # delete all related images
    image_paths_to_delete = []
    for media in ProductMedia.objects.filter(to_remove=True).iterator():
        image_paths_to_delete.append(media.image.name)
        for thumbnail in media.thumbnails.all():
            image_paths_to_delete.append(thumbnail.image.name)

    if image_paths_to_delete:
        delete_files_from_storage_task.delay(image_paths_to_delete)

    ProductMedia.objects.filter(to_remove=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0173_create_default_category_and_product_type"),
        ("thumbnail", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            drop_media_to_remove,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
