# Generated by Django 3.2.16 on 2022-10-07 13:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0172_alter_product_search_index_dirty"),
        ("product", "0173_create_default_category_and_product_type"),
    ]

    operations = []
