# Generated by Django 3.2.13 on 2022-07-19 10:33

from django.db import migrations


def drop_media_to_remove(apps, _schema_editor):
    ProductMedia = apps.get_model("product", "ProductMedia")
    # delete all related images
    for media in ProductMedia.objects.filter(to_remove=True).iterator():
        media.image.delete()
        thumbnails = media.thumbnails.all()
        for thumbnail in thumbnails:
            thumbnail.image.delete()

    ProductMedia.objects.filter(to_remove=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0173_create_default_category_and_product_type"),
    ]

    operations = [
        migrations.RunPython(
            drop_media_to_remove,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
