# Generated by Django 4.0.7 on 2022-09-14 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tax", "0001_initial"),
        ("product", "0175_alter_productmedia_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="tax_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="tax.taxclass",
            ),
        ),
        migrations.AddField(
            model_name="producttype",
            name="tax_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_types",
                to="tax.taxclass",
            ),
        ),
    ]
