# Generated by Django 4.0.7 on 2022-10-12 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0176_merge_20221007_1324"),
        ("product", "0176_product_tax_class_producttype_tax_class"),
    ]

    operations = []
