# Generated by Django 3.2.16 on 2022-11-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0176_merge_20221007_1324"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="should_refresh",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="collection",
            name="type",
            field=models.CharField(
                choices=[("static", "static"), ("dynamic", "dynamic")],
                default="static",
                max_length=64,
            ),
        ),
    ]
