# Generated by Django 3.2.16 on 2022-11-17 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("attribute", "0026_merge_20221019_0937"),
        ("product", "0177_product_tax_class_producttype_tax_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="should_refresh",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="collection",
            name="type",
            field=models.CharField(
                choices=[("static", "Static"), ("dynamic", "Dynamic")],
                default="static",
                max_length=64,
            ),
        ),
        migrations.CreateModel(
            name="CollectionRule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        choices=[("is", "Is"), ("is_not", "Is not")], max_length=64
                    ),
                ),
                (
                    "qualifier",
                    models.CharField(
                        choices=[("attribute", "Attribute")], max_length=64
                    ),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="attribute.attribute",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="product.collection",
                    ),
                ),
            ],
            options={
                "ordering": ("pk",),
            },
        ),
        migrations.CreateModel(
            name="RuleValue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(blank=True, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("boolean", models.BooleanField(blank=True, null=True)),
                ("numeric_value", models.IntegerField(blank=True, null=True)),
                ("reference_id", models.IntegerField(blank=True, null=True)),
                (
                    "collection_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="product.collectionrule",
                    ),
                ),
                (
                    "value",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="attribute.attributevalue",
                    ),
                ),
            ],
            options={
                "ordering": ("pk",),
            },
        ),
    ]
