# Generated by Django 3.2.18 on 2023-04-17 08:00

from django.db import migrations
from django.db.models import Q

from ...core.utils.editorjs import clean_editor_js

BATCH_SIZE = 2000


def queryset_in_batches(queryset):
    start_pk = 0

    while True:
        qs = queryset.order_by("pk").filter(pk__gt=start_pk)[:BATCH_SIZE]
        pks = list(qs.values_list("pk", flat=True))

        if not pks:
            break

        yield pks

        start_pk = pks[-1]


def set_description_plaintext_if_description_exists(apps, schema_editor):
    Product = apps.get_model("product", "Product")
    queryset = Product.objects.filter(
        Q(description_plaintext="") & ~Q(description=None)
    )

    for batch_pks in queryset_in_batches(queryset):
        products = Product.objects.filter(pk__in=batch_pks)
        for product in products:
            product.description_plaintext = clean_editor_js(
                product.description, to_string=True
            )
            product.search_index_dirty = True

        Product.objects.bulk_update(
            products, ["description_plaintext", "search_index_dirty"]
        )


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0177_product_tax_class_producttype_tax_class"),
    ]

    operations = [
        migrations.RunPython(
            set_description_plaintext_if_description_exists, migrations.RunPython.noop
        )
    ]
