# Generated by Django 3.2.16 on 2023-02-01 12:30

import django.contrib.postgres.indexes
from django.db import migrations, models
import saleor.core.utils.json_serializer


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0179_productvariant_external_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmedia",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=saleor.core.utils.json_serializer.CustomJsonEncoder,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="productmedia",
            name="private_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=saleor.core.utils.json_serializer.CustomJsonEncoder,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="productmedia",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["private_metadata"], name="productmedia_p_meta_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productmedia",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["metadata"], name="productmedia_meta_idx"
            ),
        ),
    ]
