# Generated by Django 3.2.18 on 2023-04-28 08:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0181_merge_20230417_1323"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="charge_taxes",
        ),
    ]
