# Generated by Django 3.2.22 on 2023-12-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0185_unmount_product_charge_taxes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmedia",
            name="alt",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
