# Generated by Django 3.2.22 on 2023-12-21 10:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0186_alter_productmedia_alt"),
        ("product", "0186_remove_product_charge_taxes"),
    ]

    operations = []
