# Generated by Django 3.2.20 on 2023-08-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0186_remove_product_charge_taxes"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
