# Generated by Django 3.2.20 on 2023-09-27 06:31

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("product", "0187_category_updated_at"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="category",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["updated_at"], name="updated_at_idx"
            ),
        ),
    ]
