# Generated by Django 3.2.22 on 2023-12-21 11:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0186_alter_productmedia_alt"),
        ("product", "0187_auto_20230614_0838"),
    ]

    operations = []
