# Generated by Django 3.2.22 on 2024-04-05 11:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0187_merge_20231221_1030"),
        ("product", "0188_merge_20231221_1119"),
    ]

    operations = []
