# Generated by Django 3.2.22 on 2024-05-13 10:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0188_merge_20240513_1023"),
        ("product", "0189_merge_20240405_1121"),
    ]

    operations = []
