# Generated by Django 3.2.22 on 2023-12-21 12:50

from django.db import migrations


class Migration(migrations.Migration):
    replaces = [
        ("product", "0190_merge_20231221_1250"),
    ]
    dependencies = [
        ("product", "0186_alter_productmedia_alt"),
        ("product", "0189_merge_20230929_0857"),
    ]

    operations = []
