# Generated by Django 3.2.23 on 2024-01-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0190_merge_20231221_1356"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discounted_price_dirty",
            field=models.BooleanField(default=False),
        ),
        migrations.RunSQL(
            """
            ALTER TABLE product_product
            ALTER COLUMN discounted_price_dirty
            SET DEFAULT false;
            """,
            migrations.RunSQL.noop,
        ),
    ]
