# Generated by Django 3.2.22 on 2024-05-13 10:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0190_merge_20240513_1042"),
        ("product", "0191_merge_20240405_1125"),
    ]

    operations = []
