# Generated by Django 4.2.17 on 2025-01-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0196_slug_unique_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmedia",
            name="downloaded",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
