# Generated by Django 4.2.20 on 2025-05-07 06:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "product",
            "0195_alter_productchannellisting_discounted_price_amount_and_more",
        ),
        ("product", "0197_productvariantchannellisting_prior_price_amount"),
    ]

    operations = []
