# Generated by Django 5.2 on 2025-05-27 12:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0199_alter_category_metadata_and_more"),
        ("product", "0199_alter_productvariantchannellisting_prior_price_amount"),
    ]

    operations = []
