# Generated by Django 5.2.8 on 2026-02-20

from django.apps import apps as registry
from django.db import migrations
from django.db.models.signals import post_migrate

from .tasks.saleor3_23 import mark_products_search_index_as_dirty_task


def mark_products_search_index_as_dirty(apps, _schema_editor):
    def on_migrations_complete(sender=None, **kwargs):
        mark_products_search_index_as_dirty_task.delay()

    sender = registry.get_app_config("product")
    post_migrate.connect(on_migrations_complete, weak=False, sender=sender)


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0202_category_product_category_tree_id_lf1e1"),
    ]

    operations = [
        migrations.RunPython(
            mark_products_search_index_as_dirty, migrations.RunPython.noop
        ),
    ]
