# Generated by Django 5.2.16 on 2026-07-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0205_merge_20260615_1308"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="variantmedia",
            options={"ordering": ("sort_order", "pk")},
        ),
        migrations.AddField(
            model_name="variantmedia",
            name="sort_order",
            field=models.IntegerField(db_index=True, editable=False, null=True),
        ),
    ]
