# Generated by Django 5.2.16 on 2026-08-20 07:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0205_merge_20260615_1308"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmedia",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
