# Generated by Django 5.2.16 on 2026-09-08 11:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0205_merge_20260615_1308"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("slug",),
                "permissions": (
                    ("manage_products", "Manage products."),
                    ("read_products", "Read products."),
                ),
            },
        ),
        migrations.AlterModelOptions(
            name="producttype",
            options={
                "ordering": ("slug",),
                "permissions": (
                    (
                        "manage_product_types_and_attributes",
                        "Manage product types and attributes.",
                    ),
                    (
                        "read_product_types_and_attributes",
                        "Read product types and attributes.",
                    ),
                ),
            },
        ),
    ]
