# Generated by Django 5.2.17 on 2026-09-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0206_product_media_translation"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorytranslation",
            name="background_image_alt",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="collectiontranslation",
            name="background_image_alt",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
