# Generated by Django 5.2.16 on 2026-09-15 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0002_move_productmedia_from_product_app"),
        ("product", "0207_remove_producttype_is_digital_from_state"),
        ("thumbnail", "0006_repoint_product_media_fk"),
    ]

    # Django state only: the foreign keys already point at the same table, and
    # `ProductMedia` is not dropped - it is now owned by the media app.
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="variantmedia",
                    name="media",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variant_media",
                        to="media.productmedia",
                    ),
                ),
                migrations.AlterField(
                    model_name="productvariant",
                    name="media",
                    field=models.ManyToManyField(
                        through="product.VariantMedia", to="media.productmedia"
                    ),
                ),
                migrations.DeleteModel(
                    name="ProductMedia",
                ),
            ],
        ),
    ]
