# Generated by Django 5.2.17 on 2026-10-05 07:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0208_category_external_reference_unique_constraint"),
        ("product", "0208_merge_20260917_1338"),
    ]

    operations = []
