# Generated by Django 5.2.17 on 2026-09-30 12:09

from django.db import migrations

import saleor.core.db.fields
import saleor.core.editorjs.converters


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0209_collection_full_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectiontranslation",
            name="full_description",
            field=saleor.core.db.fields.SanitizedJSONField(
                blank=True,
                null=True,
                sanitizer=saleor.core.editorjs.converters.clean_editorjs,
            ),
        ),
    ]
