# Generated by Django 5.2.17 on 2026-10-05 07:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0209_merge_20261005_0735"),
        ("product", "0210_collection_external_reference_unique_constraint"),
    ]

    operations = []
