# Generated by Django 5.2.17 on 2026-10-10 16:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0211_merge_20261005_0745"),
        ("product", "0214_collection_translation_full_description"),
    ]

    operations = []
