# Generated by Django 3.1 on 2020-09-18 07:17

from django.db import migrations, models


def set_default_flag(apps, schema):
    # TODO: delete it before merge to master
    Channel = apps.get_model("channel", "Channel")
    Channel.objects.filter(is_active=False).update(is_active=True)


class Migration(migrations.Migration):

    dependencies = [
        ("channel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(set_default_flag, migrations.RunPython.noop),
    ]
