# Generated by Django 3.2.18 on 2023-03-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channel", "0009_channel_order_mark_as_paid_strategy"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="default_transaction_flow_strategy",
            field=models.CharField(
                choices=[("authorization", "Authorize"), ("charge", "Charge")],
                default="charge",
                max_length=255,
            ),
        ),
        migrations.RunSQL(
            """
            ALTER TABLE channel_channel
            ALTER COLUMN default_transaction_flow_strategy
            SET DEFAULT 'charge';
            """,
            migrations.RunSQL.noop,
        ),
    ]
