# Generated by Django 3.2.18 on 2023-04-28 07:00

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channel", "0011_channel_expire_orders_after"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="delete_expired_orders_after",
            field=models.DurationField(default=datetime.timedelta(days=60)),
        ),
        migrations.RunSQL(
            """
            ALTER TABLE channel_channel
            ALTER COLUMN delete_expired_orders_after
            SET DEFAULT INTERVAL '60 days';
            """,
            migrations.RunSQL.noop,
        ),
    ]
