# Generated by Django 3.2.19 on 2023-06-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channel", "0014_channel_allow_to_create_order_without_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="use_legacy_error_flow_for_checkout",
            field=models.BooleanField(default=True),
        ),
        migrations.RunSQL(
            """
            ALTER TABLE channel_channel
            ALTER COLUMN use_legacy_error_flow_for_checkout
            SET DEFAULT true;
            """,
            migrations.RunSQL.noop,
        ),
    ]
