# Generated by Django 3.2.25 on 2025-06-25 10:48

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channel", "0017_channel_include_draft_order_in_voucher_usage"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="checkout_release_funds_cut_off_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="channel",
            name="checkout_ttl_before_releasing_funds",
            field=models.DurationField(default=datetime.timedelta(seconds=21600)),
        ),
        migrations.AddField(
            model_name="channel",
            name="release_funds_for_expired_checkouts",
            field=models.BooleanField(default=True),
        ),
        migrations.RunSQL(
            "ALTER TABLE channel_channel "
            "ALTER COLUMN checkout_ttl_before_releasing_funds "
            "SET DEFAULT '0 days 21600.000000 seconds'::interval;"
        ),
    ]
