# Generated by Django 4.2.16 on 2025-02-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channel", "0018_channel_automatically_complete_paid_checkouts"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="draft_order_line_price_freeze_period",
            field=models.PositiveIntegerField(blank=True, default=24, null=True),
        ),
        migrations.RunSQL(
            """
            ALTER TABLE channel_channel
            ALTER COLUMN draft_order_line_price_freeze_period
            SET DEFAULT 24;
            """,
            migrations.RunSQL.noop,
        ),
    ]
