# Generated by Django 4.2.15 on 2025-06-25 11:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("channel", "0018_channel_automatically_complete_paid_checkouts"),
        ("channel", "0019_migrate_checkout_ttl_release_funds"),
    ]

    operations = []
