# Generated by Django 3.2.25 on 2025-06-25 10:48

from django.apps import apps as registry
from django.db import migrations
from django.db.models.signals import post_migrate

from .tasks.saleor3_21 import migrate_env_variable_setting_to_channels


def migrate_checkout_ttl_release_funds(apps, _schema_editor):
    def on_migrations_complete(sender=None, **kwargs):
        migrate_env_variable_setting_to_channels.delay()

    sender = registry.get_app_config("channel")
    post_migrate.connect(on_migrations_complete, weak=False, sender=sender)


class Migration(migrations.Migration):
    dependencies = [
        ("channel", "0019_auto_20250625_1048"),
    ]

    operations = [
        migrations.RunPython(
            migrate_checkout_ttl_release_funds,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
