# Generated by Django 4.2.18 on 2025-04-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channel", "0019_channel_draft_order_line_price_freeze_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="use_legacy_line_voucher_propagation_for_order",
            field=models.BooleanField(default=True),
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE channel_channel
            ALTER COLUMN use_legacy_line_voucher_propagation_for_order
            SET DEFAULT true;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
