# Generated by Django 5.2 on 2025-04-23 10:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("channel", "0020_alter_channel_metadata_and_more"),
        ("channel", "0020_channel_use_legacy_line_voucher_propagation_for_order"),
    ]

    operations = []
