# Generated by Django 5.2 on 2025-05-27 12:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("channel", "0021_merge_20250423_1021"),
        (
            "channel",
            "0021_rename_use_legacy_line_voucher_propagation_for_order_channel_use_legacy_line_discount_propagation_fo",
        ),
    ]

    operations = []
