# Generated by Django 4.2.20 on 2025-07-08 12:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("channel", "0020_migrate_checkout_ttl_release_funds"),
        (
            "channel",
            "0021_rename_use_legacy_line_voucher_propagation_for_order_channel_use_legacy_line_discount_propagation_fo",
        ),
    ]

    operations = []
