# Generated by Django 5.2.1 on 2025-07-09 14:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("channel", "0022_merge_20250527_1210"),
        ("channel", "0022_merge_20250708_1220"),
    ]

    operations = []
