# Generated by Django 5.2.1 on 2025-08-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channel", "0023_merge_20250709_1453"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="create_transactions_for_gift_cards",
            field=models.BooleanField(default=False),
        ),
    ]
