# Generated by Django 5.2.5 on 2025-11-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channel", "0023_merge_20250709_1453"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="allow_attaching_gift_card_to_checkout_via_add_promo_code_mutation",
            field=models.BooleanField(default=True),
        ),
    ]
