# Generated by Django 5.2.8 on 2025-11-13 16:16

from django.apps import apps as registry
from django.db import migrations
from django.db.models.signals import post_migrate

from .tasks.saleor3_22 import set_automatic_completion_delay_task


def set_automatic_completion_delay(apps, schema_editor):
    def on_migrations_complete(sender=None, **kwargs):
        set_automatic_completion_delay_task.delay()

    sender = registry.get_app_config("order")
    post_migrate.connect(on_migrations_complete, weak=False, sender=sender)


class Migration(migrations.Migration):
    dependencies = [
        ("channel", "0024_channel_automatic_completion_delay"),
    ]

    operations = [
        migrations.RunPython(
            set_automatic_completion_delay,
            migrations.RunPython.noop,
        ),
    ]
