# Generated by Django 5.2.5 on 2025-12-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channel", "0026_channel_automatic_completion_cut_off_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="allow_legacy_gift_card_use",
            field=models.BooleanField(db_default=True, default=True),
        ),
    ]
