# Generated by Django 5.2.16 on 2026-09-09 07:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("channel", "0027_channel_allow_legacy_gift_card_use"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="channel",
            options={
                "ordering": ("slug",),
                "permissions": (
                    ("manage_channels", "Manage channels."),
                    ("read_channels", "Read channels."),
                ),
            },
        ),
    ]
