# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django_prices.models


def split_price_to_price_net_and_gross(apps, schema_editor):
    Shipping = apps.get_model('shipping', 'ShippingMethodCountry')
    for shipping in Shipping.objects.all():
        shipping.price_net = shipping.price
        shipping.price_gross = shipping.price
        shipping.save()


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0007_auto_20171129_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingmethodcountry',
            name='price',
            field=django_prices.models.AmountField(verbose_name='price', max_digits=12, decimal_places=2, currency='USD', blank=True, null=True)),
        migrations.AddField(
            model_name='shippingmethodcountry',
            name='price_net',
            field=django_prices.models.AmountField(verbose_name='price net', max_digits=12, decimal_places=2, currency='USD', blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingmethodcountry',
            name='price_gross',
            field=django_prices.models.AmountField(verbose_name='price gross', max_digits=12, decimal_places=2, currency='USD', blank=True, null=True),
        ),
        migrations.RunPython(split_price_to_price_net_and_gross),
    ]
