# Generated by Django 2.0.3 on 2018-07-19 10:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("shipping", "0009_auto_20180629_1055")]

    operations = [
        migrations.AlterModelOptions(
            name="shippingmethod",
            options={"permissions": (("manage_shipping", "Manage shipping."),)},
        )
    ]
