# Generated by Django 2.1.5 on 2019-03-05 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0014_auto_20180920_0956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingmethod',
            options={'ordering': ('pk',)},
        ),
    ]
