# Generated by Django 2.2.4 on 2019-08-14 09:13

import os

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("shipping", "0016_shippingmethod_meta")]

    operations = [
        migrations.RenameField(
            model_name="shippingmethod",
            old_name="maximum_order_price",
            new_name="maximum_order_price_amount",
        ),
        migrations.RenameField(
            model_name="shippingmethod",
            old_name="minimum_order_price",
            new_name="minimum_order_price_amount",
        ),
        migrations.RenameField(
            model_name="shippingmethod", old_name="price", new_name="price_amount"
        ),
        migrations.AddField(
            model_name="shippingmethod",
            name="currency",
            field=models.CharField(
                default=os.environ.get("DEFAULT_CURRENCY", "USD"),
                max_length=settings.DEFAULT_CURRENCY_CODE_LENGTH,
            ),
        ),
    ]
