# Generated by Django 3.1 on 2020-08-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0019_shippingmethodchannellisting"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shippingmethod", name="maximum_order_price_amount",
        ),
        migrations.RemoveField(
            model_name="shippingmethod", name="minimum_order_price_amount",
        ),
        migrations.RemoveField(model_name="shippingmethod", name="price_amount",),
        migrations.RemoveField(
            model_name="shippingmethodchannellisting", name="max_value",
        ),
        migrations.RemoveField(
            model_name="shippingmethodchannellisting", name="min_value",
        ),
        migrations.RemoveField(
            model_name="shippingmethodchannellisting", name="price",
        ),
        migrations.AddField(
            model_name="shippingmethodchannellisting",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="shippingmethodchannellisting",
            name="maximum_order_price_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="shippingmethodchannellisting",
            name="minimum_order_price_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="shippingmethodchannellisting",
            name="price_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
