# Generated by Django 3.1 on 2020-09-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0022_shippingmethodlisting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingmethodchannellisting",
            name="maximum_order_price_amount",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="shippingmethodchannellisting",
            name="minimum_order_price_amount",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=0, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="shippingmethodchannellisting",
            name="price_amount",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
