# Generated by Django 3.1 on 2020-11-04 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    # TODO squash before merging multicurrency into master
    dependencies = [
        ("channel", "0003_auto_20201015_1107"),
        ("shipping", "0024_auto_20201022_0818"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingmethodchannellisting",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipping_method_listings",
                to="channel.channel",
            ),
        ),
        migrations.AlterField(
            model_name="shippingmethodchannellisting",
            name="shipping_method",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channel_listings",
                to="shipping.shippingmethod",
            ),
        ),
    ]
