# Generated by Django 3.1.1 on 2020-10-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0024_remove_shippingmethod_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingmethodchannellisting",
            name="currency",
            field=models.CharField(max_length=3),
        ),
    ]
