# Generated by Django 3.1.4 on 2020-12-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0025_auto_20201130_1122"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingmethodzipcoderule",
            name="inclusion_type",
            field=models.CharField(
                choices=[
                    ("include", "Shipping method should include ZIP code rule"),
                    ("exclude", "Shipping method should exclude ZIP code rule"),
                ],
                default="exclude",
                max_length=32,
            ),
        ),
    ]
