# Generated by Django 3.1.5 on 2021-01-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0026_shippingzone_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingmethodzipcoderule",
            name="inclusion_type",
            field=models.CharField(
                choices=[
                    ("include", "Shipping method should include ZIP code rule"),
                    ("exclude", "Shipping method should exclude ZIP code rule"),
                ],
                default="exclude",
                max_length=32,
            ),
        ),
    ]
