# Generated by Django 3.1.5 on 2021-01-20 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipping", "0026_shippingzone_description"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ShippingMethodZipCodeRule",
            new_name="ShippingMethodPostalCodeRule",
        ),
        migrations.AddField(
            model_name="shippingmethodpostalcoderule",
            name="inclusion_type",
            field=models.CharField(
                choices=[
                    ("include", "Shipping method should include postal code rule"),
                    ("exclude", "Shipping method should exclude postal code rule"),
                ],
                default="exclude",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="shippingmethodpostalcoderule",
            name="shipping_method",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="postal_code_rules",
                to="shipping.shippingmethod",
            ),
        ),
    ]
