# Generated by Django 3.1.7 on 2021-03-08 11:35

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shipping", "0027_auto_20210120_2201"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="shippingmethod",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["private_metadata"], name="shippingmethod_p_meta_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shippingmethod",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["metadata"], name="shippingmethod_meta_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shippingzone",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["private_metadata"], name="shippingzone_p_meta_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shippingzone",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["metadata"], name="shippingzone_meta_idx"
            ),
        ),
    ]
