# Generated by Django 4.0.7 on 2022-09-14 10:41

from django.db import migrations, models
import django.db.models.deletion
import saleor.tax.models


class Migration(migrations.Migration):

    dependencies = [
        ("tax", "0001_initial"),
        ("shipping", "0031_alter_shippingmethodtranslation_language_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingmethod",
            name="tax_class",
            field=models.ForeignKey(
                default=saleor.tax.models.get_default_tax_class,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="shipping_methods",
                to="tax.taxclass",
            ),
        ),
    ]
