# Generated by Django 3.2.16 on 2022-12-20 15:52

from django.db import migrations
from django.conf import settings

from .. import ShippingMethodType


def add_default_shipping(apps, schema_editor):
    Channel = apps.get_model("channel", "Channel")
    ShippingMethod = apps.get_model("shipping", "ShippingMethod")
    ShippingZone = apps.get_model("shipping", "ShippingZone")
    Warehouse = apps.get_model("warehouse", "Warehouse")

    channel = Channel.objects.filter(slug="default-channel").first()
    warehouse = Warehouse.objects.filter(slug="default-warehouse").first()

    if not ShippingZone.objects.all().exists() and settings.POPULATE_DEFAULTS:
        shipping_zone = ShippingZone.objects.create(name="Default", countries=["US"])
        shipping_method = ShippingMethod.objects.create(
            name="Default",
            type=ShippingMethodType.PRICE_BASED,
            shipping_zone=shipping_zone,
        )

        if warehouse:
            shipping_zone.warehouses.add(warehouse)

        if channel:
            shipping_zone.channels.add(channel)
            shipping_method.channel_listings.create(
                channel=channel, currency=channel.currency_code, price_amount=0
            )


class Migration(migrations.Migration):
    dependencies = [
        ("channel", "0004_create_default_channel"),
        ("shipping", "0032_shippingmethod_tax_class"),
        ("warehouse", "0031_create_default_warehouse"),
    ]

    operations = [migrations.RunPython(add_default_shipping, migrations.RunPython.noop)]
