# Generated by Django 5.2 on 2025-05-27 12:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shipping", "0035_alter_shippingmethod_metadata_and_more"),
        (
            "shipping",
            "0035_alter_shippingmethodchannellisting_maximum_order_price_amount_and_more",
        ),
    ]

    operations = []
