# Generated by Django 4.2.20 on 2025-06-30 12:26

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "shipping",
            "0035_alter_shippingmethodchannellisting_maximum_order_price_amount_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingzone",
            name="countries",
            field=django_countries.fields.CountryField(
                blank=True, default=[], max_length=752, multiple=True
            ),
        ),
    ]
