# Generated by Django 5.2.16 on 2026-09-09 07:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shipping", "0037_merge_20250630_1332"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shippingzone",
            options={
                "permissions": (
                    ("manage_shipping", "Manage shipping."),
                    ("read_shipping", "Read shipping."),
                )
            },
        ),
    ]
