# Generated by Django 3.2.18 on 2023-05-07 17:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0077_merge_20230310_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientPrescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('prescription_number', models.CharField(max_length=25)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='account.user')),
            ],
            options={
                'ordering': ('-prescription_number',),
            },
        ),
        migrations.CreateModel(
            name='PatientInsurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(db_index=True)),
                ('termination_date', models.DateField(blank=True, db_index=True, null=True)),
                ('cardholder_id', models.CharField(max_length=25)),
                ('rx_bin', models.CharField(max_length=25)),
                ('rx_group', models.CharField(max_length=25)),
                ('pcn', models.CharField(blank=True, max_length=25, null=True)),
                ('payer_name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=25, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='account.user')),
            ],
            options={
                'ordering': ('effective_date',),
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(db_index=True)),
                ('gender_assigned_at_birth', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='account.user')),
            ],
        ),
    ]
