# Generated by Django 3.2.22 on 2023-11-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_sitesettings_cookies_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
