# Generated by Django 3.2.22 on 2023-11-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_sitesettings_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='fill_fee_cold_chain',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='fill_fee_regular',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='margin_cold_chain',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='margin_regular',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
    ]
