# Generated by Django 3.2.22 on 2023-11-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_auto_20231108_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='image',
            field=models.FileField(max_length=255, upload_to='site/images'),
        ),
    ]
