# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0008_auto_20171027_0856'),
        ('site', '0006_auto_20171102_0606'),
    ]

    operations = [
    ]
