# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0009_auto_20171107_0449'),
        ('site', '0009_auto_20171107_1018'),
    ]

    operations = [
    ]
