# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0010_auto_20171113_0958'),
        ('site', '0010_merge_20171116_0810'),
    ]

    operations = [
    ]
