# Generated by Django 2.0.3 on 2018-06-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0014_handle_taxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='handle_stock_by_default',
            field=models.BooleanField(default=True, help_text='This will set the default value of stock handling on product and variant creation'),
        ),
    ]
