# Generated by Django 2.2.5 on 2019-10-07 13:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("site", "0022_sitesettings_company_address")]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="default_mail_sender_address",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="default_mail_sender_name",
            field=models.CharField(
                blank=True,
                max_length=254,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[^\\n\\r]*$",
                        code="forbidden_character",
                        message="New lines are forbidden.",
                    )
                ],
            ),
        ),
    ]
