# Generated by Django 2.2.6 on 2019-10-24 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("site", "0024_sitesettings_customer_set_password_url")]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="company_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="account.Address",
            ),
        )
    ]
