# Generated by Django 3.2.5 on 2021-07-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site", "0029_auto_20210120_0934"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="fulfillment_allow_unpaid",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="fulfillment_auto_confirm",
            field=models.BooleanField(default=True),
        ),
    ]
