# Generated by Django 3.2.6 on 2021-08-20 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("site", "0030_alter_sitesettingstranslation_language_code"),
        ("site", "0030_auto_20210722_1141"),
    ]

    operations = []
