# Generated by Django 3.2.19 on 2023-05-10 11:38

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
from .tasks.saleor3_9 import update_statistics_task

from django.apps import apps as registry
from django.db.models.signals import post_migrate


def set_initial_statistics(apps, _schema_editor):
    def on_migrations_complete(sender=None, **kwargs):
        update_statistics_task.delay()

    sender = registry.get_app_config("order")
    post_migrate.connect(on_migrations_complete, weak=False, sender=sender)


class Migration(migrations.Migration):

    dependencies = [
        ("channel", "0005_channel_allocation_strategy"),
        ("site", "0034_sitesettings_limit_quantity_per_checkout"),
    ]

    operations = [
        migrations.CreateModel(
            name="Statistics",
            fields=[
                (
                    "channel",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="channel.channel",
                    ),
                ),
                ("orders_today", models.IntegerField(default=0)),
                (
                    "sales_today",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("orders_to_fulfill", models.IntegerField(default=0)),
                ("orders_to_capture", models.IntegerField(default=0)),
                ("products_out_of_stock", models.IntegerField(default=0)),
            ],
        ),
        migrations.RunPython(set_initial_statistics, migrations.RunPython.noop),
    ]
