# Generated by Django 3.2.19 on 2023-06-15 17:54

from django.db import migrations, models
import saleor.core.utils.json_serializer


class Migration(migrations.Migration):
    dependencies = [
        ("site", "0038_auto_20230510_1107"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=saleor.core.utils.json_serializer.CustomJsonEncoder,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="private_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=saleor.core.utils.json_serializer.CustomJsonEncoder,
                null=True,
            ),
        ),
    ]
