# Generated by Django 5.2.13 on 2026-05-07 09:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site", "0050_sitesettings_return_reason_reference_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="account_confirm_merge_mode",
            field=models.CharField(
                choices=[
                    ("merge_disabled", "Account merging disabled"),
                    ("require_password", "Require password for merging"),
                ],
                default=(
                    "require_password"
                    if settings.ACCOUNT_CONFIRM_ASSOCIATE_ANONYMOUS_OBJECTS
                    else "merge_disabled"
                ),
                max_length=30,
            ),
        ),
    ]
