# Generated by Django 5.2.1 on 2025-08-12 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("page", "0031_alter_page_metadata_alter_page_private_metadata_and_more"),
        ("site", "0041_alter_sitesettings_metadata_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="refund_reason_reference_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="page.pagetype",
            ),
        ),
    ]
