# Generated by Django 5.2.11 on 2026-02-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site", "0043_sitesettings_use_legacy_update_webhook_emission"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="preserve_all_address_fields",
            field=models.BooleanField(
                db_default=False,
                default=False,
            ),
        ),
    ]
