# Generated by Django 5.2.8 on 2026-01-20 11:56

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site", "0043_sitesettings_use_legacy_update_webhook_emission"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="instance_id",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="usage_telemetry_reported_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
