# Generated by Django 5.2.11 on 2026-03-09 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("page", "0031_alter_page_metadata_alter_page_private_metadata_and_more"),
        ("site", "0044_sitesettings_preserve_all_address_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="refund_reason_reference_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="page.pagetype",
            ),
        ),
    ]
