# Generated by Django 5.2.11 on 2026-03-17 13:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("site", "0045_merge_20260223_0944"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="automatic_fulfillment_digital_products",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="default_digital_max_downloads",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="default_digital_url_valid_days",
        ),
    ]
