# Generated by Django 5.2.11 on 2026-03-31 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site", "0047_merge_20260320_1308"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="use_legacy_shipping_zone_stock_availability",
            field=models.BooleanField(db_default=True, default=False),
        ),
    ]
