# Generated by Django 5.2.16 on 2026-07-17 14:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("site", "0045_merge_20260717_1359"),
        ("site", "0050_sitesettings_return_reason_reference_type"),
    ]

    operations = []
