# Generated by Django 5.2.16 on 2026-07-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site", "0050_sitesettings_return_reason_reference_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="allow_storefront_traffic",
            field=models.BooleanField(default=True),
        ),
    ]
