# Generated by Django 5.2.16 on 2026-07-30 07:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("site", "0052_drop_digital_content_settings"),
        ("site", "0052_sitesettings_allow_storefront_traffic"),
    ]

    operations = []
