# Generated by Django 2.2.4 on 2019-09-06 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("account", "0033_serviceaccount")]

    operations = [
        migrations.CreateModel(
            name="Webhook",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        db_index=True, max_length=128, verbose_name="Event"
                    ),
                ),
                (
                    "target_url",
                    models.URLField(max_length=255, verbose_name="Target URL"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "service_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhooks",
                        to="account.ServiceAccount",
                    ),
                ),
            ],
            options={"permissions": (("manage_webhooks", "Manage webhooks"),)},
        )
    ]
