# Generated by Django 4.2.15 on 2024-08-20 07:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webhook", "0010_drop_transaction_request_action_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhook",
            name="filterable_channel_slugs",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                default=list,
                size=500,
                blank=True,
            ),
        ),
        migrations.RunSQL(
            """
            ALTER TABLE webhook_webhook
            ALTER COLUMN filterable_channel_slugs
            SET DEFAULT array[]::varchar[];
            """,
            migrations.RunSQL.noop,
        ),
    ]
