# Generated by Django 4.2.15 on 2024-08-20 08:30

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("webhook", "0011_webhook_filterable_channel_slugs"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="webhook",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["filterable_channel_slugs"],
                name="filterable_channel_slugs_idx",
            ),
        ),
    ]
