# Generated by Django 5.2.11 on 2026-02-09 13:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webhook", "0012_webhook_filterable_channel_slugs_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhook",
            name="defer_if_conditions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=128),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
