export const customers = [
  {
    dateJoined: "2017-08-05T09:24:55.311Z",
    defaultBillingAddress: {
      city: "Padbergtown",
      companyName: null,
      country: "India",
      countryArea: "Cambridgeshire",
      firstName: "Arely",
      lastName: "Christiansen",
      phone: "554-146-5580 x3399",
      postalCode: "68154-7603",
      streetAddress1: "447 Savannah Prairie",
      streetAddress2: null
    },
    defaultShippingAddress: {
      city: "Elianefort",
      companyName: null,
      country: "Cocos (Keeling) Islands",
      countryArea: null,
      firstName: "Arely",
      lastName: "Christiansen",
      phone: "262.057.1854",
      postalCode: "92971-3111",
      streetAddress1: "552 Rowe Plains",
      streetAddress2: null
    },
    email: "arely_christiansen@example.com",
    id: "50649",
    isActive: true,
    isStaff: false,
    note: null
  },
  {
    dateJoined: "2017-06-10T03:35:11.538Z",
    defaultBillingAddress: {
      city: "Isabellhaven",
      companyName: "Hartmann - Harvey",
      country: "Poland",
      countryArea: "Berkshire",
      firstName: "Lilian",
      lastName: "Bins",
      phone: "951.234.6173",
      postalCode: "61393-3608",
      streetAddress1: "8986 Timmy Estates",
      streetAddress2: null
    },
    defaultShippingAddress: {
      city: "Isabellhaven",
      companyName: "Hartmann - Harvey",
      country: "Poland",
      countryArea: "Berkshire",
      firstName: "Lilian",
      lastName: "Bins",
      phone: "951.234.6173",
      postalCode: "61393-3608",
      streetAddress1: "8986 Timmy Estates",
      streetAddress2: null
    },
    email: "lilian_bins@example.com",
    id: "47717",
    isActive: true,
    isStaff: false,
    note: null
  },
  {
    dateJoined: "2017-10-03T01:34:14.996Z",
    defaultBillingAddress: {
      city: "Lorenburgh",
      companyName: null,
      country: "Uganda",
      countryArea: null,
      firstName: "Rickie",
      lastName: "Schuppe",
      phone: "1-795-203-5072 x34840",
      postalCode: "35239-8503",
      streetAddress1: "9890 Weimann Rapids",
      streetAddress2: null
    },
    defaultShippingAddress: {
      city: "Lorineberg",
      companyName: null,
      country: "Lao People's Democratic Republic",
      countryArea: "Buckinghamshire",
      firstName: "Rickie",
      lastName: "Schuppe",
      phone: "459-208-7325",
      postalCode: "21326-5671",
      streetAddress1: "7041 Witting Court",
      streetAddress2: null
    },
    email: "rickie_schuppe@example.com",
    id: "43395",
    isActive: true,
    isStaff: false,
    note: null
  },
  {
    dateJoined: "2017-10-14T17:22:15.302Z",
    defaultBillingAddress: {
      city: "East Emilybury",
      companyName: "Padberg LLC",
      country: "Marshall Islands",
      countryArea: "Avon",
      firstName: "Oda",
      lastName: "Kreiger",
      phone: "1-963-853-9978 x55415",
      postalCode: "14783-4193",
      streetAddress1: "2350 Labadie Common",
      streetAddress2: null
    },
    defaultShippingAddress: {
      city: "Judeside",
      companyName: null,
      country: "Turkmenistan",
      countryArea: "Buckinghamshire",
      firstName: "Oda",
      lastName: "Kreiger",
      phone: "1-171-428-1386 x9613",
      postalCode: "34620",
      streetAddress1: "45368 Florence Burgs",
      streetAddress2: null
    },
    email: "oda_kreiger@example.com",
    id: "98733",
    isActive: true,
    isStaff: false,
    note: null
  },
  {
    dateJoined: "2017-11-30T01:35:23.030Z",
    defaultBillingAddress: {
      city: "Swifthaven",
      companyName: "Stokes, Schroeder and Kozey",
      country: "American Samoa",
      countryArea: null,
      firstName: "Golden",
      lastName: "Kunde",
      phone: "1-627-494-4069",
      postalCode: "05982",
      streetAddress1: "07003 Tremblay Spur",
      streetAddress2: null
    },
    defaultShippingAddress: {
      city: "Abshireland",
      companyName: null,
      country: "Tonga",
      countryArea: "Berkshire",
      firstName: "Golden",
      lastName: "Kunde",
      phone: "726-806-4810",
      postalCode: "43489",
      streetAddress1: "3749 Yasmin Mill",
      streetAddress2: null
    },
    email: "golden_kunde@example.com",
    id: "32255",
    isActive: true,
    isStaff: false,
    note: null
  },
  {
    dateJoined: "2018-04-06T01:47:19.973Z",
    defaultBillingAddress: {
      city: "South Veda",
      companyName: null,
      country: "Tunisia",
      countryArea: "Cambridgeshire",
      firstName: "Jude",
      lastName: "Terry",
      phone: "435-519-9628",
      postalCode: "20683",
      streetAddress1: "71371 Eda Parkway",
      streetAddress2: null
    },
    defaultShippingAddress: {
      city: "South Veda",
      companyName: null,
      country: "Tunisia",
      countryArea: "Cambridgeshire",
      firstName: "Jude",
      lastName: "Terry",
      phone: "435-519-9628",
      postalCode: "20683",
      streetAddress1: "71371 Eda Parkway",
      streetAddress2: null
    },
    email: "jude_terry@example.com",
    id: "30824",
    isActive: true,
    isStaff: false,
    note: null
  },
  {
    dateJoined: "2018-02-06T05:41:13.648Z",
    defaultBillingAddress: {
      city: "Tyreeview",
      companyName: null,
      country: "Macedonia",
      countryArea: null,
      firstName: "Charlene",
      lastName: "Homenick",
      phone: "716-110-9597 x83295",
      postalCode: "29716",
      streetAddress1: "3002 Webster Island",
      streetAddress2: null
    },
    defaultShippingAddress: {
      city: "Tyreeview",
      companyName: null,
      country: "Macedonia",
      countryArea: null,
      firstName: "Charlene",
      lastName: "Homenick",
      phone: "716-110-9597 x83295",
      postalCode: "29716",
      streetAddress1: "3002 Webster Island",
      streetAddress2: null
    },
    email: "charlene_homenick@example.com",
    id: "95016",
    isActive: true,
    isStaff: true,
    note: null
  },
  {
    dateJoined: "2018-01-17T14:01:24.012Z",
    defaultBillingAddress: {
      city: "Rossieburgh",
      companyName: "Schinner, Dickinson and Larson",
      country: "Puerto Rico",
      countryArea: null,
      firstName: "Eliseo",
      lastName: "Farrell",
      phone: "1-704-506-9999 x73846",
      postalCode: "80415",
      streetAddress1: "9158 Brennan Vista",
      streetAddress2: null
    },
    defaultShippingAddress: {
      city: "Rossieburgh",
      companyName: "Schinner, Dickinson and Larson",
      country: "Puerto Rico",
      countryArea: null,
      firstName: "Eliseo",
      lastName: "Farrell",
      phone: "1-704-506-9999 x73846",
      postalCode: "80415",
      streetAddress1: "9158 Brennan Vista",
      streetAddress2: null
    },
    email: "eliseo_farrell@example.com",
    id: "19478",
    isActive: true,
    isStaff: false,
    note: null
  },
  {
    dateJoined: "2017-06-11T18:16:02.317Z",
    defaultBillingAddress: {
      city: "North Nedraton",
      companyName: null,
      country: "Belarus",
      countryArea: null,
      firstName: "Oceane",
      lastName: "Veum",
      phone: "625.437.5361",
      postalCode: "56673-3197",
      streetAddress1: "4806 Rempel Square",
      streetAddress2: null
    },
    defaultShippingAddress: {
      city: "North Katherynfort",
      companyName: "Legros and Sons",
      country: "Uruguay",
      countryArea: null,
      firstName: "Oceane",
      lastName: "Veum",
      phone: "(970) 885-6654 x326",
      postalCode: "22621-0352",
      streetAddress1: "6172 Omer Cove",
      streetAddress2: null
    },
    email: "oceane_veum@example.com",
    id: "77679",
    isActive: true,
    isStaff: false,
    note: "Quidem."
  },
  {
    dateJoined: "2018-03-18T14:00:35.114Z",
    defaultBillingAddress: {
      city: "New Dereckton",
      companyName: null,
      country: "Isle of Man",
      countryArea: null,
      firstName: "Margaretta",
      lastName: "Romaguera",
      phone: "(927) 494-5335",
      postalCode: "71066-0418",
      streetAddress1: "1511 Harmon Station",
      streetAddress2: null
    },
    defaultShippingAddress: {
      city: "New Dereckton",
      companyName: null,
      country: "Isle of Man",
      countryArea: null,
      firstName: "Margaretta",
      lastName: "Romaguera",
      phone: "(927) 494-5335",
      postalCode: "71066-0418",
      streetAddress1: "1511 Harmon Station",
      streetAddress2: null
    },
    email: "margaretta_romaguera@example.com",
    id: "4621",
    isActive: true,
    isStaff: false,
    note: "Molestiae voluptatem aut."
  },
  {
    dateJoined: "2017-07-31T05:14:54.080Z",
    defaultBillingAddress: {
      city: "East Loyceshire",
      companyName: null,
      country: "Angola",
      countryArea: null,
      firstName: "Bridgette",
      lastName: "Von",
      phone: "(169) 327-5622 x7996",
      postalCode: "54408-8140",
      streetAddress1: "315 Monahan Fields",
      streetAddress2: null
    },
    defaultShippingAddress: {
      city: "East Loyceshire",
      companyName: null,
      country: "Angola",
      countryArea: null,
      firstName: "Bridgette",
      lastName: "Von",
      phone: "(169) 327-5622 x7996",
      postalCode: "54408-8140",
      streetAddress1: "315 Monahan Fields",
      streetAddress2: null
    },
    email: "bridgette_von@example.com",
    id: "32604",
    isActive: true,
    isStaff: false,
    note: null
  },
  {
    dateJoined: "2017-12-17T20:07:02.301Z",
    defaultBillingAddress: {
      city: "Purdyland",
      companyName: null,
      country: "Comoros",
      countryArea: null,
      firstName: "Betty",
      lastName: "Terry",
      phone: "246.065.8974 x67112",
      postalCode: "18348-2977",
      streetAddress1: "149 Modesto Fields",
      streetAddress2: null
    },
    defaultShippingAddress: {
      city: "North Toyside",
      companyName: null,
      country: "Brazil",
      countryArea: "Buckinghamshire",
      firstName: "Betty",
      lastName: "Terry",
      phone: "(349) 868-4307 x329",
      postalCode: "27739",
      streetAddress1: "3415 Demarcus Garden",
      streetAddress2: "Apt. 526"
    },
    email: "betty_terry@example.com",
    id: "51317",
    isActive: true,
    isStaff: false,
    note: null
  },
  {
    dateJoined: "2018-01-31T07:00:49.686Z",
    defaultBillingAddress: {
      city: "West Sydnieside",
      companyName: null,
      country: "Tajikistan",
      countryArea: null,
      firstName: "Harry",
      lastName: "Ryan",
      phone: "(249) 144-2443",
      postalCode: "35205-5099",
      streetAddress1: "8968 Ullrich Lake",
      streetAddress2: null
    },
    defaultShippingAddress: {
      city: "Hellerberg",
      companyName: null,
      country: "Bahamas",
      countryArea: null,
      firstName: "Harry",
      lastName: "Ryan",
      phone: "(342) 498-7649",
      postalCode: "43564",
      streetAddress1: "78191 Johnson Path",
      streetAddress2: null
    },
    email: "harry_ryan@example.com",
    id: "3526",
    isActive: true,
    isStaff: false,
    note: null
  },
  {
    dateJoined: "2018-01-23T17:54:14.851Z",
    defaultBillingAddress: {
      city: "New Amalia",
      companyName: null,
      country: "French Polynesia",
      countryArea: null,
      firstName: "Willow",
      lastName: "Gleason",
      phone: "602.241.1780",
      postalCode: "97539",
      streetAddress1: "5022 Vida Terrace",
      streetAddress2: null
    },
    defaultShippingAddress: {
      city: "New Amalia",
      companyName: null,
      country: "French Polynesia",
      countryArea: null,
      firstName: "Willow",
      lastName: "Gleason",
      phone: "602.241.1780",
      postalCode: "97539",
      streetAddress1: "5022 Vida Terrace",
      streetAddress2: null
    },
    email: "willow_gleason@example.com",
    id: "48590",
    isActive: true,
    isStaff: false,
    note: null
  },
  {
    dateJoined: "2018-05-24T22:40:09.175Z",
    defaultBillingAddress: {
      city: "Evangelineberg",
      companyName: null,
      country: "Malaysia",
      countryArea: null,
      firstName: "Frankie",
      lastName: "Labadie",
      phone: "(340) 697-5224 x85469",
      postalCode: "23938",
      streetAddress1: "763 Sanford Loaf",
      streetAddress2: null
    },
    defaultShippingAddress: {
      city: "Schadenville",
      companyName: "Lang - Parisian",
      country: "Macedonia",
      countryArea: "Borders",
      firstName: "Frankie",
      lastName: "Labadie",
      phone: "(613) 207-4987",
      postalCode: "68448",
      streetAddress1: "2390 Weissnat Pine",
      streetAddress2: null
    },
    email: "frankie_labadie@example.com",
    id: "63158",
    isActive: true,
    isStaff: false,
    note: null
  },
  {
    dateJoined: "2018-04-05T01:54:24.676Z",
    defaultBillingAddress: {
      city: "Lake Olaf",
      companyName: null,
      country: "Comoros",
      countryArea: "Bedfordshire",
      firstName: "Dameon",
      lastName: "King",
      phone: "915.814.0544",
      postalCode: "25168",
      streetAddress1: "0975 Emelia Square",
      streetAddress2: null
    },
    defaultShippingAddress: {
      city: "South Dexter",
      companyName: null,
      country: "Virgin Islands, British",
      countryArea: null,
      firstName: "Dameon",
      lastName: "King",
      phone: "655-309-4332",
      postalCode: "86296-0615",
      streetAddress1: "235 Swift Avenue",
      streetAddress2: null
    },
    email: "dameon_king@example.com",
    id: "76170",
    isActive: true,
    isStaff: false,
    note: null
  }
];
export const customer = customers[0];
