export const customers = [
  {
    dateJoined: "2017-10-11T13:22:30.831Z",
    defaultBillingAddress: {
      city: "Thompsontown",
      cityArea: "Rhode Island",
      companyName: null,
      country: "Swaziland",
      countryArea: "Buckinghamshire",
      firstName: "Alexander",
      id: "52402",
      lastName: "Simonis",
      phone_number: "253-928-8945",
      phone_prefix: "17",
      postalCode: "47639-5237",
      streetAddress_1: "83772 Savanah Summit",
      streetAddress_2: null
    },
    defaultShippingAddress: {
      city: "West Bret",
      cityArea: "North Dakota",
      companyName: null,
      country: "Sudan",
      countryArea: null,
      firstName: "Alexander",
      id: "77109",
      lastName: "Simonis",
      phone_number: "463-243-6545",
      phone_prefix: "21",
      postalCode: "21665",
      streetAddress_1: "780 Jaime Prairie",
      streetAddress_2: null
    },
    email: "alexander_simonis@example.com",
    id: "11810",
    isActive: true,
    isStaff: false,
    note: null
  },
  {
    dateJoined: "2018-01-21T22:41:38.241Z",
    defaultBillingAddress: {
      city: "Lake Adela",
      cityArea: "Maryland",
      companyName: "Kemmer Group",
      country: "Kenya",
      countryArea: null,
      firstName: "Augustus",
      id: "81868",
      lastName: "Crist",
      phone_number: "583-374-8576",
      phone_prefix: "19",
      postalCode: "29966",
      streetAddress_1: "5656 Crooks Park",
      streetAddress_2: null
    },
    defaultShippingAddress: {
      city: "East Brandttown",
      cityArea: "Missouri",
      companyName: null,
      country: "Somalia",
      countryArea: null,
      firstName: "Augustus",
      id: "11788",
      lastName: "Crist",
      phone_number: "584-961-3073",
      phone_prefix: "52",
      postalCode: "80218",
      streetAddress_1: "37212 O'Reilly Ford",
      streetAddress_2: null
    },
    email: "augustus_crist@example.com",
    id: "34351",
    isActive: true,
    isStaff: false,
    note: null
  },
  {
    dateJoined: "2018-01-19T21:36:19.298Z",
    defaultBillingAddress: {
      city: "East Raymond",
      cityArea: "Delaware",
      companyName: null,
      country: "San Marino",
      countryArea: null,
      firstName: "Kelton",
      id: "77939",
      lastName: "Eichmann",
      phone_number: "650-119-2676",
      phone_prefix: "17",
      postalCode: "94747-5311",
      streetAddress_1: "5060 Aufderhar Common",
      streetAddress_2: null
    },
    defaultShippingAddress: {
      city: "East Raymond",
      cityArea: "Delaware",
      companyName: null,
      country: "San Marino",
      countryArea: null,
      firstName: "Kelton",
      id: "77939",
      lastName: "Eichmann",
      phone_number: "650-119-2676",
      phone_prefix: "17",
      postalCode: "94747-5311",
      streetAddress_1: "5060 Aufderhar Common",
      streetAddress_2: null
    },
    email: "kelton_eichmann@example.com",
    id: "47883",
    isActive: true,
    isStaff: true,
    note: null
  },
  {
    dateJoined: "2018-01-18T15:08:59.535Z",
    defaultBillingAddress: {
      city: "Torphyton",
      cityArea: "Iowa",
      companyName: null,
      country: "Chad",
      countryArea: null,
      firstName: "Magnolia",
      id: "2237",
      lastName: "Brakus",
      phone_number: "136-461-3995",
      phone_prefix: "52",
      postalCode: "64573",
      streetAddress_1: "106 Swift Squares",
      streetAddress_2: null
    },
    defaultShippingAddress: {
      city: "Torphyton",
      cityArea: "Iowa",
      companyName: null,
      country: "Chad",
      countryArea: null,
      firstName: "Magnolia",
      id: "2237",
      lastName: "Brakus",
      phone_number: "136-461-3995",
      phone_prefix: "52",
      postalCode: "64573",
      streetAddress_1: "106 Swift Squares",
      streetAddress_2: null
    },
    email: "magnolia_brakus@example.com",
    id: "53433",
    isActive: true,
    isStaff: false,
    note: "Dolorem qui vero iure."
  },
  {
    dateJoined: "2017-07-22T05:21:13.774Z",
    defaultBillingAddress: {
      city: "Port Savanahfort",
      cityArea: "Nebraska",
      companyName: null,
      country: "Greenland",
      countryArea: null,
      firstName: "Adonis",
      id: "10532",
      lastName: "Pacocha",
      phone_number: "944-018-0185",
      phone_prefix: "11",
      postalCode: "52460-3432",
      streetAddress_1: "32181 Lindgren Turnpike",
      streetAddress_2: null
    },
    defaultShippingAddress: {
      city: "East Fletcher",
      cityArea: "New Hampshire",
      companyName: null,
      country: "Kyrgyz Republic",
      countryArea: null,
      firstName: "Adonis",
      id: "45425",
      lastName: "Pacocha",
      phone_number: "549-984-7736",
      phone_prefix: "36",
      postalCode: "29123-8368",
      streetAddress_1: "938 Jordyn Harbor",
      streetAddress_2: null
    },
    email: "adonis_pacocha@example.com",
    id: "42657",
    isActive: true,
    isStaff: false,
    note: "Unde qui et."
  },
  {
    dateJoined: "2018-05-31T06:55:23.938Z",
    defaultBillingAddress: {
      city: "New Eugenia",
      cityArea: "Michigan",
      companyName: null,
      country: "Iceland",
      countryArea: null,
      firstName: "Carlie",
      id: "83778",
      lastName: "Walsh",
      phone_number: "387-984-3969",
      phone_prefix: "27",
      postalCode: "48003",
      streetAddress_1: "08030 Corrine Row",
      streetAddress_2: null
    },
    defaultShippingAddress: {
      city: "North Tanyafurt",
      cityArea: "Wyoming",
      companyName: null,
      country: "Rwanda",
      countryArea: null,
      firstName: "Carlie",
      id: "14941",
      lastName: "Walsh",
      phone_number: "320-941-3747",
      phone_prefix: "44",
      postalCode: "33296",
      streetAddress_1: "1231 Eriberto Stravenue",
      streetAddress_2: null
    },
    email: "carlie_walsh@example.com",
    id: "93594",
    isActive: true,
    isStaff: false,
    note: null
  },
  {
    dateJoined: "2017-08-26T08:37:16.497Z",
    defaultBillingAddress: {
      city: "Labadiechester",
      cityArea: "Iowa",
      companyName: null,
      country: "Morocco",
      countryArea: "Buckinghamshire",
      firstName: "Junius",
      id: "86163",
      lastName: "Crist",
      phone_number: "605-434-6759",
      phone_prefix: "47",
      postalCode: "39521",
      streetAddress_1: "333 Bernie Fords",
      streetAddress_2: null
    },
    defaultShippingAddress: {
      city: "Kaylistad",
      cityArea: "Louisiana",
      companyName: null,
      country: "Equatorial Guinea",
      countryArea: "Bedfordshire",
      firstName: "Junius",
      id: "78537",
      lastName: "Crist",
      phone_number: "893-019-4257",
      phone_prefix: "20",
      postalCode: "43886-6932",
      streetAddress_1: "0597 Angeline Gateway",
      streetAddress_2: null
    },
    email: "junius_crist@example.com",
    id: "70932",
    isActive: true,
    isStaff: false,
    note: "Et cumque consequatur aliquam."
  },
  {
    dateJoined: "2018-01-08T11:55:39.220Z",
    defaultBillingAddress: {
      city: "Lydiahaven",
      cityArea: "Arkansas",
      companyName: null,
      country: "Cambodia",
      countryArea: "Berkshire",
      firstName: "Pedro",
      id: "70545",
      lastName: "Harvey",
      phone_number: "817-342-0603",
      phone_prefix: "35",
      postalCode: "72196",
      streetAddress_1: "9280 Asa Center",
      streetAddress_2: null
    },
    defaultShippingAddress: {
      city: "Lydiahaven",
      cityArea: "Arkansas",
      companyName: null,
      country: "Cambodia",
      countryArea: "Berkshire",
      firstName: "Pedro",
      id: "70545",
      lastName: "Harvey",
      phone_number: "817-342-0603",
      phone_prefix: "35",
      postalCode: "72196",
      streetAddress_1: "9280 Asa Center",
      streetAddress_2: null
    },
    email: "pedro_harvey@example.com",
    id: "61255",
    isActive: false,
    isStaff: false,
    note: null
  },
  {
    dateJoined: "2017-07-28T00:49:40.975Z",
    defaultBillingAddress: {
      city: "East Leilafurt",
      cityArea: "Arizona",
      companyName: null,
      country: "Bulgaria",
      countryArea: null,
      firstName: "Raven",
      id: "9167",
      lastName: "Deckow",
      phone_number: "210-019-3184",
      phone_prefix: "62",
      postalCode: "02296",
      streetAddress_1: "8546 Marks Highway",
      streetAddress_2: null
    },
    defaultShippingAddress: {
      city: "South Hendersonbury",
      cityArea: "Nevada",
      companyName: "Raynor Inc",
      country: "Turkmenistan",
      countryArea: null,
      firstName: "Raven",
      id: "48467",
      lastName: "Deckow",
      phone_number: "654-130-2375",
      phone_prefix: "46",
      postalCode: "00611",
      streetAddress_1: "87001 Howell Forge",
      streetAddress_2: null
    },
    email: "raven_deckow@example.com",
    id: "84610",
    isActive: true,
    isStaff: false,
    note: null
  },
  {
    dateJoined: "2018-05-04T03:17:55.298Z",
    defaultBillingAddress: {
      city: "Windlerton",
      cityArea: "Texas",
      companyName: "Heller, Bauch and Friesen",
      country: "Andorra",
      countryArea: null,
      firstName: "Paige",
      id: "63622",
      lastName: "Lesch",
      phone_number: "972-463-2863",
      phone_prefix: "8",
      postalCode: "80681-4790",
      streetAddress_1: "93719 Hackett Mountain",
      streetAddress_2: null
    },
    defaultShippingAddress: {
      city: "Windlerton",
      cityArea: "Texas",
      companyName: "Heller, Bauch and Friesen",
      country: "Andorra",
      countryArea: null,
      firstName: "Paige",
      id: "63622",
      lastName: "Lesch",
      phone_number: "972-463-2863",
      phone_prefix: "8",
      postalCode: "80681-4790",
      streetAddress_1: "93719 Hackett Mountain",
      streetAddress_2: null
    },
    email: "paige_lesch@example.com",
    id: "28741",
    isActive: true,
    isStaff: false,
    note: null
  },
  {
    dateJoined: "2018-01-27T13:43:07.363Z",
    defaultBillingAddress: {
      city: "Gleichnerborough",
      cityArea: "Missouri",
      companyName: null,
      country: "Dominica",
      countryArea: null,
      firstName: "Santino",
      id: "89962",
      lastName: "Bins",
      phone_number: "844-752-5593",
      phone_prefix: "45",
      postalCode: "33593-8299",
      streetAddress_1: "557 Jacobi Gateway",
      streetAddress_2: null
    },
    defaultShippingAddress: {
      city: "West Jolieland",
      cityArea: "Connecticut",
      companyName: null,
      country: "Saint Helena",
      countryArea: "Bedfordshire",
      firstName: "Santino",
      id: "58915",
      lastName: "Bins",
      phone_number: "685-424-9436",
      phone_prefix: "25",
      postalCode: "58377",
      streetAddress_1: "6647 Kody Locks",
      streetAddress_2: null
    },
    email: "santino_bins@example.com",
    id: "46991",
    isActive: false,
    isStaff: false,
    note: null
  },
  {
    dateJoined: "2018-03-13T22:04:39.414Z",
    defaultBillingAddress: {
      city: "North Sister",
      cityArea: "Ohio",
      companyName: null,
      country: "Bangladesh",
      countryArea: "Bedfordshire",
      firstName: "Quinn",
      id: "94894",
      lastName: "Barrows",
      phone_number: "995-317-3324",
      phone_prefix: "35",
      postalCode: "41805",
      streetAddress_1: "146 Dee Station",
      streetAddress_2: null
    },
    defaultShippingAddress: {
      city: "North Sister",
      cityArea: "Ohio",
      companyName: null,
      country: "Bangladesh",
      countryArea: "Bedfordshire",
      firstName: "Quinn",
      id: "94894",
      lastName: "Barrows",
      phone_number: "995-317-3324",
      phone_prefix: "35",
      postalCode: "41805",
      streetAddress_1: "146 Dee Station",
      streetAddress_2: null
    },
    email: "quinn_barrows@example.com",
    id: "50687",
    isActive: true,
    isStaff: false,
    note: null
  },
  {
    dateJoined: "2018-01-27T01:40:52.437Z",
    defaultBillingAddress: {
      city: "Kenstad",
      cityArea: "Alabama",
      companyName: null,
      country: "United Arab Emirates",
      countryArea: null,
      firstName: "Berry",
      id: "93575",
      lastName: "Windler",
      phone_number: "876-373-9137",
      phone_prefix: "41",
      postalCode: "89880-6342",
      streetAddress_1: "01419 Bernhard Plain",
      streetAddress_2: null
    },
    defaultShippingAddress: {
      city: "Kenstad",
      cityArea: "Alabama",
      companyName: null,
      country: "United Arab Emirates",
      countryArea: null,
      firstName: "Berry",
      id: "93575",
      lastName: "Windler",
      phone_number: "876-373-9137",
      phone_prefix: "41",
      postalCode: "89880-6342",
      streetAddress_1: "01419 Bernhard Plain",
      streetAddress_2: null
    },
    email: "berry_windler@example.com",
    id: "36798",
    isActive: true,
    isStaff: false,
    note: null
  },
  {
    dateJoined: "2017-07-17T22:43:18.274Z",
    defaultBillingAddress: {
      city: "Jamilstad",
      cityArea: "Idaho",
      companyName: "Kilback - Crooks",
      country: "Uruguay",
      countryArea: null,
      firstName: "Johnathon",
      id: "78744",
      lastName: "Kohler",
      phone_number: "888-798-4522",
      phone_prefix: "63",
      postalCode: "43892-8110",
      streetAddress_1: "287 Rowe Mews",
      streetAddress_2: null
    },
    defaultShippingAddress: {
      city: "Jamilstad",
      cityArea: "Idaho",
      companyName: "Kilback - Crooks",
      country: "Uruguay",
      countryArea: null,
      firstName: "Johnathon",
      id: "78744",
      lastName: "Kohler",
      phone_number: "888-798-4522",
      phone_prefix: "63",
      postalCode: "43892-8110",
      streetAddress_1: "287 Rowe Mews",
      streetAddress_2: null
    },
    email: "johnathon_kohler@example.com",
    id: "98483",
    isActive: true,
    isStaff: false,
    note: null
  },
  {
    dateJoined: "2017-07-10T00:09:56.552Z",
    defaultBillingAddress: {
      city: "Keltonland",
      cityArea: "West Virginia",
      companyName: "Bailey, Barrows and Prosacco",
      country: "Denmark",
      countryArea: null,
      firstName: "Linwood",
      id: "19005",
      lastName: "Windler",
      phone_number: "815-222-0791",
      phone_prefix: "60",
      postalCode: "12595",
      streetAddress_1: "496 Sporer Mountain",
      streetAddress_2: null
    },
    defaultShippingAddress: {
      city: "Keltonland",
      cityArea: "West Virginia",
      companyName: "Bailey, Barrows and Prosacco",
      country: "Denmark",
      countryArea: null,
      firstName: "Linwood",
      id: "19005",
      lastName: "Windler",
      phone_number: "815-222-0791",
      phone_prefix: "60",
      postalCode: "12595",
      streetAddress_1: "496 Sporer Mountain",
      streetAddress_2: null
    },
    email: "linwood_windler@example.com",
    id: "18050",
    isActive: true,
    isStaff: false,
    note: null
  },
  {
    dateJoined: "2017-08-25T06:08:19.951Z",
    defaultBillingAddress: {
      city: "West Feliciamouth",
      cityArea: "Montana",
      companyName: null,
      country: "Japan",
      countryArea: null,
      firstName: "Timmy",
      id: "33855",
      lastName: "Macejkovic",
      phone_number: "460-907-9374",
      phone_prefix: "41",
      postalCode: "15926",
      streetAddress_1: "0238 Cremin Freeway",
      streetAddress_2: null
    },
    defaultShippingAddress: {
      city: "Larkinstad",
      cityArea: "California",
      companyName: null,
      country: "Somalia",
      countryArea: null,
      firstName: "Timmy",
      id: "67467",
      lastName: "Macejkovic",
      phone_number: "943-882-1295",
      phone_prefix: "64",
      postalCode: "43425",
      streetAddress_1: "96332 Corkery Lane",
      streetAddress_2: null
    },
    email: "timmy_macejkovic@example.com",
    id: "65578",
    isActive: true,
    isStaff: false,
    note: "Dolorem vitae."
  }
];
export const customer = customers[0];
