
build:
  version: 2016-03-14 # version of the build schema.
  steps:
    builder:
      name: oyelogic
      dockerfile: Dockerfile
      secrets:
        id_rsa:
          type: file
          value: _env(HOME)/.ssh/id_rsa
