# Generated by Django 3.2.18 on 2023-02-17 08:37

from django.db import migrations

from .. import TaxCalculationStrategy


def set_flat_rates_as_default_strategy(apps, schema_editor):
    TaxConfiguration = apps.get_model("tax", "TaxConfiguration")
    TaxConfiguration.objects.filter(tax_calculation_strategy=None).update(
        tax_calculation_strategy=TaxCalculationStrategy.FLAT_RATES
    )


class Migration(migrations.Migration):
    dependencies = [
        ("tax", "0006_alter_taxconfiguration_tax_calculation_strategy"),
    ]

    operations = [
        migrations.RunPython(
            set_flat_rates_as_default_strategy, migrations.RunPython.noop
        )
    ]
