# Generated by Django 4.2.15 on 2025-05-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tax", "0008_auto_20240122_1353"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxclasscountryrate",
            name="rate",
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
    ]
