# Generated by Django 5.2 on 2025-05-27 12:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tax", "0009_alter_taxclass_metadata_and_more"),
        ("tax", "0009_alter_taxclasscountryrate_rate"),
    ]

    operations = []
