# Generated by Django 5.2.1 on 2025-05-30 09:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tax", "0010_merge_20250527_1210"),
        ("tax", "0010_taxconfiguration_use_weighted_tax_for_shipping_and_more"),
    ]

    operations = []
