CACHE_EXCLUDED_SHIPPING_TIME = 60 * 3
WEBHOOK_CACHE_DEFAULT_TTL: int = 5 * 60  # 5 minutes
SYNC_WEBHOOK_TIMEOUT_CACHE_TTL: int = 1  # 1 second
SYNC_WEBHOOK_TIMEOUT_SENTINEL = (
    "TIMED_OUT"  # Arbitrary value to indicate webhook timeout in cache
)
APP_ID_PREFIX = "app"

MAX_FILTERABLE_CHANNEL_SLUGS_LIMIT = 500
