# Generated by Django 3.0.6 on 2020-07-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0011_update_proxy_permissions"),
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="about_app",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="app",
            name="app_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="app",
            name="configuration_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="app",
            name="data_privacy",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="app",
            name="data_privacy_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="app",
            name="homepage_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="app",
            name="identifier",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="app",
            name="support_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="app",
            name="type",
            field=models.CharField(
                choices=[("local", "local"), ("thirdparty", "thirdparty")],
                default="local",
                max_length=60,
            ),
        ),
        migrations.AddField(
            model_name="app",
            name="version",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.CreateModel(
            name="AppInstallation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("deleted", "Deleted"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("app_name", models.CharField(max_length=60)),
                ("manifest_url", models.URLField()),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions which will be assigned to app.",
                        related_name="app_installation_set",
                        related_query_name="app_installation",
                        to="auth.Permission",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
    ]
