# Generated by Django 3.0.6 on 2020-06-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_auto_20200520_0124"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="type",
            field=models.CharField(
                choices=[("local", "local"), ("thirdparty", "thirdparty")],
                default="local",
                max_length=60,
            ),
        ),
    ]
