# Generated by Django 3.2.2 on 2021-06-29 06:49

from django.contrib.auth.hashers import make_password
from django.db import migrations


def rewrite_auth_tokens(apps, schema_editor):
    AppToken = apps.get_model("app", "AppToken")
    for token_inst in AppToken.objects.iterator():
        token_inst.raw_auth_token_last_4_chars = token_inst.auth_token[-4:]
        token_inst.auth_token = make_password(token_inst.auth_token)
        token_inst.save(update_fields=["raw_auth_token_last_4_chars", "auth_token"])


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_auto_20210629_0639"),
    ]

    operations = [
        migrations.RunPython(
            rewrite_auth_tokens, reverse_code=migrations.RunPython.noop
        )
    ]
