# Generated by Django 3.2.12 on 2022-03-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_appextension_target"),
    ]

    operations = [
        migrations.AddField(
            model_name="apptoken",
            name="token_last_4",
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name="apptoken",
            name="auth_token",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
