# Generated by Django 3.2.18 on 2023-03-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0020_app_is_installed"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="author",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
