# Generated by Django 3.2.18 on 2023-04-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0021_app_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="uuid",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="appinstallation",
            name="uuid",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
