# Generated by Django 3.2.18 on 2023-04-07 09:44

from django.contrib.postgres.functions import RandomUUID
from django.db import migrations

BATCH_SIZE = 1000


def queryset_in_batches(qs, batch_size: int):
    def batch_ids():
        length = len(ids)
        for index in range(0, length, batch_size):
            yield ids[index : min(index + batch_size, length)]

    ids = qs.values_list("id", flat=True)
    yield from batch_ids()


def update_uuid_field(model_cls, batch_size: int):
    query_set = model_cls.objects.filter(uuid__isnull=True).order_by("-pk")
    for ids_batch in queryset_in_batches(query_set, batch_size):
        qs = model_cls.objects.filter(id__in=ids_batch)
        qs.update(uuid=RandomUUID())


def update_apps_uuid_field_migration(apps, _schema_editor):
    App = apps.get_model("app", "App")
    AppInstallation = apps.get_model("app", "AppInstallation")
    update_uuid_field(App, BATCH_SIZE)
    update_uuid_field(AppInstallation, BATCH_SIZE)


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0022_auto_20230410_0859"),
    ]

    operations = [
        migrations.RunPython(
            update_apps_uuid_field_migration, reverse_code=migrations.RunPython.noop
        )
    ]
