# Generated by Django 3.2.18 on 2023-04-12 13:30

from django.contrib.postgres.functions import RandomUUID
from django.db import migrations


# This data migration is handled in the 0023 with celery tasks.
# 0023 is due to zero-downtime policy, this migration is to ensure
# that we can change token to non-nullable.
def populate_uuid_field(model_cls):
    model_cls.objects.filter(uuid__isnull=True).update(uuid=RandomUUID())


def populate_apps_uuid_field_migration(apps, _schema_editor):
    App = apps.get_model("app", "App")
    AppInstallation = apps.get_model("app", "AppInstallation")
    populate_uuid_field(App)
    populate_uuid_field(AppInstallation)


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0023_populate_app_and_app_installation_uuid"),
    ]

    operations = [
        migrations.RunPython(
            populate_apps_uuid_field_migration, migrations.RunPython.noop
        )
    ]
