# Generated by Django 3.2.22 on 2023-11-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0025_auto_20230420_1544"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="removed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
