# Generated by Django 3.2.22 on 2023-10-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0025_auto_20230420_1544"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="to_remove",
            field=models.BooleanField(default=False),
        ),
        migrations.RunSQL(
            """
            ALTER TABLE app_app
            ALTER COLUMN to_remove
            SET DEFAULT False;
            """,
            migrations.RunSQL.noop,
        ),
    ]
