# Generated by Django 3.2.19 on 2023-06-12 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0079_full_channel_access_group_for_openid"),
        ("app", "0025_auto_20230420_1544"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("installed", "App was installed"),
                            ("activated", "App was activated"),
                            ("deactivated", "App was deactivated"),
                        ],
                        db_index=True,
                        max_length=255,
                    ),
                ),
                (
                    "requestor_type",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("app", "App"),
                            ("saleor", "Saleor"),
                        ],
                        default="saleor",
                        max_length=60,
                    ),
                ),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="app.app",
                    ),
                ),
                (
                    "requestor_app",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="app.app",
                    ),
                ),
                (
                    "requestor_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="account.user",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
    ]
