# Generated by Django 5.2.1 on 2025-06-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0030_alter_app_metadata_alter_app_private_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appextension",
            name="mount",
            field=models.CharField(
                choices=[
                    ("category_overview_create", "category_overview_create"),
                    (
                        "category_overview_more_actions",
                        "category_overview_more_actions",
                    ),
                    ("category_details_more_actions", "category_details_more_actions"),
                    ("collection_overview_create", "collection_overview_create"),
                    (
                        "collection_overview_more_actions",
                        "collection_overview_more_actions",
                    ),
                    (
                        "collection_details_more_actions",
                        "collection_details_more_actions",
                    ),
                    ("gift_card_overview_create", "gift_card_overview_create"),
                    (
                        "gift_card_overview_more_actions",
                        "gift_card_overview_more_actions",
                    ),
                    (
                        "gift_card_details_more_actions",
                        "gift_card_details_more_actions",
                    ),
                    ("customer_overview_create", "customer_overview_create"),
                    (
                        "customer_overview_more_actions",
                        "customer_overview_more_actions",
                    ),
                    ("customer_details_more_actions", "customer_details_more_actions"),
                    ("product_overview_create", "product_overview_create"),
                    ("product_overview_more_actions", "product_overview_more_actions"),
                    ("product_details_more_actions", "product_details_more_actions"),
                    ("navigation_catalog", "navigation_catalog"),
                    ("navigation_orders", "navigation_orders"),
                    ("navigation_customers", "navigation_customers"),
                    ("navigation_discounts", "navigation_discounts"),
                    ("navigation_translations", "navigation_translations"),
                    ("navigation_pages", "navigation_pages"),
                    ("order_details_more_actions", "order_details_more_actions"),
                    ("order_overview_create", "order_overview_create"),
                    ("order_overview_more_actions", "order_overview_more_actions"),
                    (
                        "draft_order_details_more_actions",
                        "draft_order_details_more_actions",
                    ),
                    ("draft_order_overview_create", "draft_order_overview_create"),
                    (
                        "draft_order_overview_more_actions",
                        "draft_order_overview_more_actions",
                    ),
                    (
                        "promotions_details_more_actions",
                        "promotions_details_more_actions",
                    ),
                    ("promotions_overview_create", "promotions_overview_create"),
                    (
                        "promotions_overview_more_actions",
                        "promotions_overview_more_actions",
                    ),
                    ("voucher_details_more_actions", "voucher_details_more_actions"),
                    ("voucher_overview_create", "voucher_overview_create"),
                    ("voucher_overview_more_actions", "voucher_overview_more_actions"),
                    ("model_details_more_actions", "model_details_more_actions"),
                    ("model_overview_create", "model_overview_create"),
                    ("model_overview_more_actions", "model_overview_more_actions"),
                    ("model_types_overview_create", "model_types_overview_create"),
                    (
                        "model_types_overview_more_actions",
                        "model_types_overview_more_actions",
                    ),
                    (
                        "model_types_details_more_actions",
                        "model_types_details_more_actions",
                    ),
                    ("structure_overview_create", "structure_overview_create"),
                    (
                        "structure_overview_more_actions",
                        "structure_overview_more_actions",
                    ),
                    (
                        "structure_details_more_actions",
                        "structure_details_more_actions",
                    ),
                ],
                max_length=256,
            ),
        ),
    ]
