# Generated by Django 5.2.1 on 2025-06-06 11:59

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0031_alter_appextension_mount_alter_appextension_target"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppWebhookMutex",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("acquired_at", models.DateTimeField(null=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "app",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_mutex",
                        to="app.app",
                        verbose_name="App",
                    ),
                ),
            ],
        ),
    ]
