# Generated by Django 5.2.5 on 2025-10-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0032_appextension_http_target_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appextension",
            name="mount",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="appextension",
            name="target",
            field=models.CharField(default="popup", max_length=128),
        ),
    ]
