# Generated by Django 5.2.5 on 2025-10-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0032_appextension_http_target_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appextension",
            name="settings",
            field=models.JSONField(blank=True, db_default={}, default=dict),
        ),
    ]
