# Generated by Django 5.2.5 on 2025-10-06 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0032_appextension_http_target_method_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppWebhookMutex",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "app",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_mutex",
                        to="app.app",
                        verbose_name="App",
                    ),
                ),
            ],
        ),
    ]
