# Generated by Django 5.2.5 on 2025-11-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0033_appextension_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appextension",
            name="mount",
            field=models.CharField(
                choices=[
                    ("category_overview_create", "category_overview_create"),
                    (
                        "category_overview_more_actions",
                        "category_overview_more_actions",
                    ),
                    ("category_details_more_actions", "category_details_more_actions"),
                    ("collection_overview_create", "collection_overview_create"),
                    (
                        "collection_overview_more_actions",
                        "collection_overview_more_actions",
                    ),
                    (
                        "collection_details_more_actions",
                        "collection_details_more_actions",
                    ),
                    ("collection_details_widgets", "collection_details_widgets"),
                    ("gift_card_overview_create", "gift_card_overview_create"),
                    (
                        "gift_card_overview_more_actions",
                        "gift_card_overview_more_actions",
                    ),
                    (
                        "gift_card_details_more_actions",
                        "gift_card_details_more_actions",
                    ),
                    ("gift_card_details_widgets", "gift_card_details_widgets"),
                    ("customer_overview_create", "customer_overview_create"),
                    (
                        "customer_overview_more_actions",
                        "customer_overview_more_actions",
                    ),
                    ("customer_details_more_actions", "customer_details_more_actions"),
                    ("customer_details_widgets", "customer_details_widgets"),
                    ("product_overview_create", "product_overview_create"),
                    ("product_overview_more_actions", "product_overview_more_actions"),
                    ("product_details_more_actions", "product_details_more_actions"),
                    ("product_details_widgets", "product_details_widgets"),
                    ("navigation_catalog", "navigation_catalog"),
                    ("navigation_orders", "navigation_orders"),
                    ("navigation_customers", "navigation_customers"),
                    ("navigation_discounts", "navigation_discounts"),
                    ("navigation_translations", "navigation_translations"),
                    ("navigation_pages", "navigation_pages"),
                    ("order_details_more_actions", "order_details_more_actions"),
                    ("order_overview_create", "order_overview_create"),
                    ("order_overview_more_actions", "order_overview_more_actions"),
                    ("order_details_widgets", "order_details_widgets"),
                    (
                        "draft_order_details_more_actions",
                        "draft_order_details_more_actions",
                    ),
                    ("draft_order_overview_create", "draft_order_overview_create"),
                    (
                        "draft_order_overview_more_actions",
                        "draft_order_overview_more_actions",
                    ),
                    ("draft_order_details_widgets", "draft_order_details_widgets"),
                    ("discount_details_more_actions", "discount_details_more_actions"),
                    ("discount_overview_create", "discount_overview_create"),
                    (
                        "discount_overview_more_actions",
                        "discount_overview_more_actions",
                    ),
                    ("voucher_details_more_actions", "voucher_details_more_actions"),
                    ("voucher_overview_create", "voucher_overview_create"),
                    ("voucher_overview_more_actions", "voucher_overview_more_actions"),
                    ("voucher_details_widgets", "voucher_details_widgets"),
                    ("page_details_more_actions", "page_details_more_actions"),
                    ("page_overview_create", "page_overview_create"),
                    ("page_overview_more_actions", "page_overview_more_actions"),
                    ("page_type_overview_create", "page_type_overview_create"),
                    (
                        "page_type_overview_more_actions",
                        "page_type_overview_more_actions",
                    ),
                    (
                        "page_type_details_more_actions",
                        "page_type_details_more_actions",
                    ),
                    ("menu_overview_create", "menu_overview_create"),
                    ("menu_overview_more_actions", "menu_overview_more_actions"),
                    ("menu_details_more_actions", "menu_details_more_actions"),
                    ("translations_more_actions", "translations_more_actions"),
                ],
                max_length=256,
            ),
        ),
    ]
