# Generated by Django 5.2.8 on 2025-11-28 14:49

from django.apps import apps as registry
from django.db import migrations
from django.db.models.signals import post_migrate

from .tasks.saleor3_23 import fill_app_extension_settings_task


def fill_app_extension_settings_migration(apps, _schema_editor):
    def on_migrations_complete(sender=None, **kwargs):
        fill_app_extension_settings_task.delay()

    sender = registry.get_app_config("app")
    post_migrate.connect(on_migrations_complete, weak=False, sender=sender)


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0034_alter_appextension_mount"),
    ]

    operations = [
        migrations.RunPython(
            fill_app_extension_settings_migration, migrations.RunPython.noop
        ),
    ]
