# Generated by Django 5.2.8 on 2025-11-28 14:49

from django.db import migrations


class Migration(migrations.Migration):
    """Scheduled the 3.23 `AppExtension.settings` backfill as a Celery task.

    The backfill now runs synchronously in 0043 instead, which covers every
    instance this migration would have covered, so the task is gone and this is
    a no-op. Instances that already applied this migration keep whatever the
    task filled in; 0043 only touches rows it left empty.
    """

    dependencies = [
        ("app", "0034_alter_appextension_mount"),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
    ]
