# Generated by Django 5.2.11 on 2026-02-13 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0095_repopulate_user_number_of_orders"),
        ("app", "0034_alter_appextension_mount"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppProblem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("message", models.CharField(max_length=2048)),
                ("key", models.CharField(max_length=128)),
                ("count", models.PositiveIntegerField(default=1)),
                ("is_critical", models.BooleanField(default=False)),
                ("dismissed", models.BooleanField(default=False)),
                (
                    "dismissed_by_user_email",
                    models.EmailField(blank=True, max_length=256, null=True),
                ),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problems",
                        to="app.app",
                    ),
                ),
                (
                    "dismissed_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="account.user",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
