# Generated by Django 5.2.8 on 2025-11-28 14:49

from django.db import migrations

BATCH_SIZE = 1000


def fill_app_extension_settings(apps, _schema_editor):
    AppExtension = apps.get_model("app", "AppExtension")
    qs = AppExtension.objects.filter(
        settings={}, target__in=["widget", "new_tab"]
    ).only("pk", "target", "http_target_method")

    batch: list = []
    for extension in qs.iterator(chunk_size=BATCH_SIZE):
        if extension.target.upper() == "WIDGET":
            extension.settings = {
                "widgetTarget": {"method": extension.http_target_method}
            }
            batch.append(extension)
        elif extension.target.upper() == "NEW_TAB":
            extension.settings = {
                "newTabTarget": {"method": extension.http_target_method}
            }
            batch.append(extension)

        if len(batch) >= BATCH_SIZE:
            AppExtension.objects.bulk_update(batch, fields=["settings"])
            batch = []

    if batch:
        AppExtension.objects.bulk_update(batch, fields=["settings"])


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0034_alter_appextension_mount"),
    ]

    operations = [
        migrations.RunPython(fill_app_extension_settings, migrations.RunPython.noop),
    ]
