# Generated by Django 5.2.8 on 2025-11-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0035_app_extensions_mount_target_settings_reshape"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appextension",
            name="target",
            field=models.CharField(default="popup", max_length=128),
        ),
    ]
