# Generated by Django 5.2.15 on 2026-06-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("app", "0038_merge_20260213_1154"),
    ]

    operations = [
        migrations.AddField(
            model_name="appextension",
            name="identifier",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    CREATE UNIQUE INDEX CONCURRENTLY unique_app_extension_identifier
                    ON app_appextension ("app_id", "identifier");
                    """,
                    reverse_sql="""
                    DROP INDEX CONCURRENTLY IF EXISTS unique_app_extension_identifier;
                    """,
                ),
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE app_appextension
                    ADD CONSTRAINT unique_app_extension_identifier
                    UNIQUE USING INDEX unique_app_extension_identifier;
                    """,
                    reverse_sql="""
                    ALTER TABLE app_appextension DROP CONSTRAINT
                    IF EXISTS unique_app_extension_identifier;
                    """,
                ),
            ],
            state_operations=[
                migrations.AddConstraint(
                    model_name="appextension",
                    constraint=models.UniqueConstraint(
                        fields=("app", "identifier"),
                        name="unique_app_extension_identifier",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="appextension",
            constraint=models.CheckConstraint(
                condition=~models.Q(identifier=""),
                name="app_extension_identifier_not_blank",
            ),
        ),
    ]
