# Generated by Django 5.2.15 on 2026-06-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0038_merge_20260213_1154"),
    ]

    operations = [
        migrations.AddField(
            model_name="appextension",
            name="identifier",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddConstraint(
            model_name="appextension",
            constraint=models.UniqueConstraint(
                fields=("app", "identifier"), name="unique_app_extension_identifier"
            ),
        ),
        migrations.AddConstraint(
            model_name="appextension",
            constraint=models.CheckConstraint(
                condition=~models.Q(identifier=""),
                name="app_extension_identifier_not_blank",
            ),
        ),
    ]
