# Generated by Django 5.2.11 on 2026-03-20 11:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0038_merge_20260213_1154"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppWebhookMutex",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acquired_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="app.app",
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
