# Generated by Django 5.2.13 on 2026-04-23 08:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0038_merge_20260213_1154"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appextension",
            name="http_target_method",
        ),
    ]
