# Generated by Django 5.2.16 on 2026-07-13 10:17

from django.db import migrations


def remove_manage_observability_permission(apps, _schema_editor):
    Permission = apps.get_model("permission", "Permission")
    # Deleting the permission cascades to its group, app and app extension
    # assignments through the related many-to-many tables. The observability
    # webhook feature it gated has been removed in favour of OpenTelemetry.
    Permission.objects.filter(
        codename="manage_observability", content_type__app_label="app"
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0039_remove_manage_apps_permission"),
    ]

    operations = [
        # Auto-generated by makemigrations because manage_observability was
        # removed from App.Meta.permissions. This only syncs Django's model
        # state; it does not delete the existing auth_permission row (the
        # post_migrate create_permissions signal only ever adds permissions).
        # The RunPython below performs the actual row cleanup.
        migrations.AlterModelOptions(
            name="app",
            options={
                "ordering": ("name", "pk"),
                "permissions": (("manage_apps", "Manage apps"),),
            },
        ),
        migrations.RunPython(
            remove_manage_observability_permission, migrations.RunPython.noop
        ),
    ]
