# Generated by Django 5.2.14 on 2026-07-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0040_appwebhookmutex"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="concurrency",
            field=models.CharField(
                choices=[
                    ("sequential", "sequential"),
                    ("low", "low"),
                    ("normal", "normal"),
                    ("high", "high"),
                ],
                db_default="low",
                default="low",
                max_length=60,
            ),
        ),
    ]
