# Generated by Django 5.2.16 on 2026-09-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0041_widen_manifest_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="deprecation_reason",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
