# Generated by Django 5.2.16 on 2026-07-28 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0099_remove_digitalcontent_customerevent_type"),
        ("app", "0041_apptoken_creator_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="appinstallation",
            name="installed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="account.user",
            ),
        ),
    ]
