# Generated by Django 5.2.16 on 2026-08-20 09:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0041_merge_20260714_1040"),
        ("app", "0041_widen_manifest_url"),
    ]

    operations = []
