# Generated by Django 5.2.16 on 2026-07-13 10:17

from django.apps import apps as registry
from django.db import migrations
from django.db.models.signals import post_migrate


def remove_manage_observability_permission(apps, _schema_editor):
    """Register permission deletion after the creation hook from 0014.

    On fresh databases, an inline deletion would run before 0014's post-migrate
    hook creates the permission. Hooks run in registration order, so the later
    handler registered here deletes it last. Transactional tests can emit the
    signal without historical apps and are ignored. Deleting the permission
    cascades to its group, app, and app extension assignments.
    """

    def on_migrations_complete(sender=None, **kwargs):
        try:
            apps = kwargs["apps"]
        except KeyError:
            return
        Permission = apps.get_model("permission", "Permission")
        Permission.objects.filter(
            codename="manage_observability",
            content_type__app_label="app",
        ).delete()

    sender = registry.get_app_config("app")
    post_migrate.connect(on_migrations_complete, weak=False, sender=sender)


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0041_merge_20260714_1040"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="app",
            options={
                "ordering": ("name", "pk"),
                "permissions": (("manage_apps", "Manage apps"),),
            },
        ),
        migrations.RunPython(
            remove_manage_observability_permission, migrations.RunPython.noop
        ),
    ]
