# Generated by Django 5.2.16 on 2026-07-28 12:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0041_merge_20260714_1040"),
        ("app", "0042_appinstallation_installed_by"),
    ]

    operations = []
