# Generated by Django 5.2.16 on 2026-08-31 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0042_merge_20260820_0919"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appextension",
            name="http_target_method",
            field=models.CharField(null=True),
        ),
    ]
