# Generated by Django 3.1 on 2020-11-06 07:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0131_update_ts_vector_existing_product_name"),
    ]

    operations = []
