# Generated by Django 3.2.6 on 2021-10-04 16:36

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0148_producttype_product_type_search_gin"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description_plaintext",
            field=models.TextField(blank=True),
        ),
        # nosemgrep: add-index-concurrently
        migrations.AddIndex(
            model_name="category",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name", "slug", "description_plaintext"],
                name="category_search_name_slug_gin",
                opclasses=["gin_trgm_ops", "gin_trgm_ops", "gin_trgm_ops"],
            ),
        ),
    ]
