# Generated by Django 3.2.7 on 2021-10-20 07:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0153_merge_20211006_0910"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="quantity_limit_per_customer",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
