# Generated by Django 3.2.14 on 2022-08-02 08:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0171_alter_versatile_images"),
        ("product", "0171_product_search_index_dirty"),
    ]

    operations = []
