# Generated by Django 3.2.16 on 2022-10-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0171_product_search_index_dirty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="search_index_dirty",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
