# Generated by Django 3.2.18 on 2023-04-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0181_merge_20230417_1323"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariantchannellisting",
            name="discounted_price_amount",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=12, null=True
            ),
        ),
    ]
