# Generated by Django 3.2.19 on 2023-06-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0184_product_product_gin"),
        ("tax", "0004_migrate_tax_classes"),
    ]

    state_operations = [
        migrations.RemoveField(
            model_name="product",
            name="charge_taxes",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="charge_taxes",
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.SeparateDatabaseAndState(state_operations=state_operations),
    ]
