# Generated by Django 3.2.22 on 2024-05-13 10:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0187_merge_20231221_1030"),
        ("product", "0187_productvariantchannellisting_product_pro_price_a_fb6bd3_gin"),
    ]

    operations = []
