# Generated by Django 3.2.20 on 2023-09-29 08:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0187_auto_20230614_0838"),
        ("product", "0188_category_updated_at_idx"),
    ]

    operations = []
