# Generated by Django 3.2.22 on 2023-12-21 13:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0186_alter_productmedia_alt"),
        ("product", "0189_merge_20230929_0857"),
    ]

    operations = []
