# Generated by Django 3.2.22 on 2024-04-05 11:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0189_merge_20240405_1121"),
        ("product", "0190_merge_20231221_1356"),
    ]

    operations = []
