# Generated by Django 3.2.22 on 2024-04-05 11:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0191_merge_20240405_1125"),
        ("product", "0191_productchannellisting_discounted_price_dirty"),
    ]

    operations = []
