# Generated by Django 3.2.23 on 2024-06-20 14:04

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("product", "0193_merge_20240513_1105"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="product",
            index=models.Index(
                fields=["category_id", "slug"], name="product_pro_categor_8de99d_idx"
            ),
        ),
    ]
