# Generated by Django 5.2.1 on 2025-07-03 12:21

from django.contrib.postgres.indexes import GinIndex
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("product", "0200_merge_20250527_1210"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="productvariant",
            index=GinIndex(
                fields=["name", "sku"],
                name="variant_gin",
                opclasses=["gin_trgm_ops", "gin_trgm_ops"],
            ),
        ),
    ]
