# Generated by Django 5.2.5 on 2025-09-01 12:19

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0201_productvariant_variant_gin"),
    ]

    atomic = False

    operations = [
        AddIndexConcurrently(
            model_name="category",
            index=models.Index(
                fields=["tree_id", "lft"], name="product_category_tree_id_lf1e1"
            ),
        ),
    ]
