# Generated by Django 3.2.12 on 2022-05-12 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocknotify',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
