# Generated by Django 3.1 on 2020-08-10 14:15

from django.db import migrations, models

import saleor.core.utils.json_serializer


class Migration(migrations.Migration):

    dependencies = [
        ("plugins", "0004_drop_support_for_env_vatlayer_access_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pluginconfiguration",
            name="configuration",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=saleor.core.utils.json_serializer.CustomJsonEncoder,
                null=True,
            ),
        ),
    ]
