# Generated by Django 2.1.4 on 2019-02-14 10:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0007_auto_20190206_0938"),
        ("payment", "0007_auto_20190125_0242"),
    ]

    operations = []
