# Generated by Django 2.1.4 on 2019-02-21 02:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0009_convert_to_partially_charged_and_partially_refunded")
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="charge_status",
            field=models.CharField(
                choices=[
                    ("not-charged", "Not charged"),
                    ("partially-charged", "Partially charged"),
                    ("fully-charged", "Fully charged"),
                    ("partially-refunded", "Partially refunded"),
                    ("fully-refunded", "Fully refunded"),
                ],
                default="not-charged",
                max_length=20,
            ),
        )
    ]
