# Generated by Django 3.2.15 on 2022-08-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0036_auto_20220518_0732"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="error",
            field=models.TextField(null=True),
        ),
    ]
