# Generated by Django 3.2.23 on 2023-12-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0052_transactionitem_last_refund_success"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionevent",
            name="idempotency_key",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="transactionitem",
            name="idempotency_key",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
