# Generated by Django 3.2.19 on 2023-06-01 08:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0052_auto_20230816_1214"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="transactionitem",
                    name="status",
                ),
                migrations.RemoveField(
                    model_name="transactionevent",
                    name="status",
                ),
            ]
        ),
    ]
