# Generated by Django 3.2.22 on 2023-12-13 07:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0055_add_constraints_from_indexes"),
        ("payment", "0055_merge_20231212_1610"),
    ]

    operations = []
