# Generated by Django 5.2.1 on 2025-07-16 07:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0061_transaction_legacy_adyen_plugin_payment_method_and_more"),
        ("payment", "0063_transactionitem_payment_method_type_ids_and_more"),
    ]

    operations = []
