# Generated by Django 5.2.8 on 2026-02-06 11:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0066_transactionitem_gift_card"),
        ("payment", "0067_transactionitem_app_identifier_idx"),
    ]

    operations = []
