# Generated by Django 2.2 on 2019-05-02 13:46
from django.db import migrations

from saleor.events import OrderEvents


def _move_updated_events_to_other(apps, *_args, **_kwargs):
    cls = apps.get_model('events', 'OrderEvent')

    for event in cls.objects.filter(type='updated').all():
        event.type = OrderEvents.OTHER
        event.parameters['message'] = (
            'Order details were updated by %(user_name)s' % {
                'user_name': event.user})
        event.save(update_fields=['type', 'parameters'])


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0064_merge_20190425_0800'),
    ]

    operations = [
        migrations.RunPython(_move_updated_events_to_other)
    ]
