# Generated by Django 2.2 on 2019-05-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0065_move_updated_events_to_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderevent',
            name='type',
            field=models.CharField(choices=[('draft_created', 'The draft order was created'), ('draft_added_products', 'Some products were added to the draft order'), ('draft_removed_products', 'Some products were removed from the draft order'), ('placed', 'The order was placed'), ('placed_from_draft', 'The draft order was placed'), ('oversold_items', 'The draft order was placed with oversold items'), ('canceled', 'The order was canceled'), ('order_marked_as_paid', 'The order was manually marked as fully paid'), ('order_fully_paid', 'The order was fully paid'), ('updated_address', 'The address from the placed order was updated'), ('email_sent', 'The email was sent'), ('payment_captured', 'The payment was captured'), ('payment_refunded', 'The payment was refunded'), ('payment_voided', 'The payment was voided'), ('payment_failed', 'The payment was failed'), ('fulfillment_canceled', 'A fulfillment was canceled'), ('fulfillment_restocked_items', 'The items of the fulfillment were restocked'), ('fulfillment_fulfilled_items', 'Some items were fulfilled'), ('tracking_updated', "The fulfillment's tracking code was updated"), ('note_added', 'A note was added to the order'), ('other', 'An unknown order event containing a message')], max_length=255),
        ),
    ]
