# Generated by Django 3.2.19 on 2023-06-25 10:57

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import saleor.account.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channel', '0012_channel_delete_expired_orders_after'),
        ('account', '0079_full_channel_access_group_for_openid'),
        ('product', '0185_unmount_product_charge_taxes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('value_type', models.CharField(choices=[('fixed', 'fixed'), ('percentage', '%')], default='fixed', max_length=10)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_discounts', to='product.category')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category_discounts', models.ManyToManyField(to='b2b.CategoryDiscount')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='channel.channel')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('personal_phone', saleor.account.models.PossiblePhoneNumberField(blank=True, max_length=255, null=True, region=None)),
                ('business_phone', saleor.account.models.PossiblePhoneNumberField(blank=True, max_length=255, null=True, region=None)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('uid', models.CharField(blank=True, max_length=255, null=True)),
                ('has_access_to_b2b', models.BooleanField(default=False)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='account.user')),
            ],
        ),
    ]
