# Generated by Django 3.2.19 on 2023-06-26 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0080_user_customer_group'),
        ('b2b', '0002_companyinfo_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='recieved_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='customer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='account.user'),
        ),
    ]
