# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_auto_20160829_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='sorting_code',
            field=models.CharField(blank=True, max_length=128, verbose_name='sorting code'),
        ),
        migrations.AlterField(
            model_name='address',
            name='first_name',
            field=models.CharField(blank=True, max_length=256, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='address',
            name='last_name',
            field=models.CharField(blank=True, max_length=256, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_address_1',
            field=models.TextField(blank=True, verbose_name='address'),
        ),
    ]
