# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_auto_20161013_0633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='street_address_1',
            new_name='street_address',
        ),
        migrations.RemoveField(
            model_name='address',
            name='street_address_2',
        ),
    ]
