# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 12:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_auto_20170206_0407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='addresses',
        ),
        migrations.RemoveField(
            model_name='user',
            name='default_billing_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='default_shipping_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
