# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_auto_20170206_0407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('view_user', 'Can View User'), ('edit_user', 'Can Edit User')), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
