# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 09:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_auto_20170919_0839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('view_user', 'Can view users'), ('edit_user', 'Can edit users'), ('impersonate_user', 'Can impersonate users')), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
