# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0011_auto_20171117_0733'),
    ]

    operations = [
    ]
