# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 11:21
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields
import phonenumbers


def convert_phone_number_to_phonenumberfield(apps, schema_editor):
    Address = apps.get_model("userprofile", "Address")
    for address in Address.objects.all():
        if address.phone:
            phone_number = phonenumbers.parse(address.phone.raw_input,
                                              address.country.code)
            address.phone = phone_number
            address.save()


def convert_phone_number_to_str(apps, schema_editor):
    Address = apps.get_model("userprofile", "Address")
    for address in Address.objects.all():
        if address.phone:
            phone_number = str(address.phone)
            address.phone = phone_number
            address.save()


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0012_auto_20171117_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, verbose_name='phone number'),
        ),
        migrations.RunPython(convert_phone_number_to_phonenumberfield,
                             convert_phone_number_to_str),
    ]
