# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 10:30
from __future__ import unicode_literals
import random

from django.db import migrations
from phonenumbers import COUNTRY_CODE_TO_REGION_CODE


REVERSED_COUNTRY_CODE = dict(
    zip(COUNTRY_CODE_TO_REGION_CODE.values(),
        COUNTRY_CODE_TO_REGION_CODE.keys()))


def add_phone_number(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Address = apps.get_model("userprofile", "Address")
    db_alias = schema_editor.connection.alias
    for address in Address.objects.all():
        if (address.country,) in REVERSED_COUNTRY_CODE:
            phone_number = '+{}{}'.format(
                           REVERSED_COUNTRY_CODE[(address.country,)],
                           str(random.randint(10**9, 10**10 - 1)))
            address.phone = phone_number
            address.save()


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0013_auto_20171120_0521'),
    ]

    operations = [
        migrations.RunPython(add_phone_number),
    ]
