# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 13:34
from __future__ import unicode_literals

from django.db import migrations
import saleor.userprofile.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0014_auto_20171129_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=saleor.userprofile.models.PossiblePhoneNumberField(blank=True, default='', max_length=128, verbose_name='phone number'),
        ),
    ]
