# Generated by Django 2.2.10 on 2020-02-28 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0005_auto_20200204_0722"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="product_variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stocks",
                to="product.ProductVariant",
            ),
        ),
    ]
