# Generated by Django 2.2.6 on 2019-11-08 14:20

import uuid

import django_countries.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("shipping", "0017_django_price_2")]

    operations = [
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Warehouse name"),
                ),
                (
                    "company_name",
                    models.CharField(max_length=100, verbose_name="Legal company name"),
                ),
                (
                    "street_address",
                    models.CharField(max_length=256, verbose_name="Street name"),
                ),
                ("city", models.CharField(max_length=256)),
                (
                    "postal_code",
                    models.CharField(max_length=20, verbose_name="Zip code"),
                ),
                ("country", django_countries.fields.CountryField(max_length=2)),
                (
                    "country_area",
                    models.CharField(max_length=128, verbose_name="State/province"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=254,
                        verbose_name="Email address",
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        default="",
                        max_length=128,
                        region=None,
                        verbose_name="Phone number",
                    ),
                ),
                ("shipping_zones", models.ManyToManyField(to="shipping.ShippingZone")),
            ],
            options={
                "ordering": ("-name",),
                "permissions": (("manage_warehouses", "Manage warehouses."),),
            },
        )
    ]
