# Generated by Django 2.2.7 on 2019-12-05 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("warehouse", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="warehouse",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="account.Address"
            ),
        )
    ]
