# Generated by Django 3.0.4 on 2020-04-30 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0007_auto_20200406_0341"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="warehouse.Warehouse"
            ),
        ),
    ]
