# Generated by Django 3.0.6 on 2020-06-14 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0083_merge_20200421_0529'),
        ('checkout', '0026_checkout_expires'),
        ('warehouse', '0009_remove_invalid_allocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='checkout_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='checkout.CheckoutLine'),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='order_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='order.OrderLine'),
        ),
        migrations.AlterUniqueTogether(
            name='allocation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='allocation',
            constraint=models.UniqueConstraint(fields=('order_line', 'stock'), name='order stock constraint'),
        ),
        migrations.AddConstraint(
            model_name='allocation',
            constraint=models.UniqueConstraint(fields=('checkout_line', 'stock'), name='checkout stock constraint'),
        ),
    ]
