# Generated by Django 3.2.7 on 2021-09-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0014_remove_warehouse_company_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
    ]
