# Generated by Django 3.2.6 on 2021-12-21 11:33

from django.db import migrations, models
from django.db.models import OuterRef, Subquery, Sum
from django.db.models.functions import Coalesce


def assign_quantity_allocated_to_stocks(apps, schema_editor):
    Stock = apps.get_model("warehouse", "Stock")

    batch_size = 1000
    stocks_ids = Stock.objects.values_list("id", flat=True)
    for idx in range(0, len(stocks_ids), batch_size):
        ids_to_update = stocks_ids[idx : idx + batch_size]  # noqa: E203
        Stock.objects.filter(id__in=ids_to_update).update(
            quantity_allocated=Subquery(
                Stock.objects.filter(id=OuterRef("id"))
                .annotate(
                    allocations_allocated=Coalesce(
                        Sum("allocations__quantity_allocated"), 0
                    )
                )
                .values("allocations_allocated")[:1]
            )
        )


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0015_alter_stock_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="quantity_allocated",
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(
            assign_quantity_allocated_to_stocks, migrations.RunPython.noop
        ),
    ]
