# Generated by Django 3.2.5 on 2021-09-10 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0117_merge_20210903_1013"),
        ("product", "0148_merge_0147_auto_20210623_1304_0147_auto_20210817_1015"),
        ("warehouse", "0015_auto_20210713_0904"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreorderAllocation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                (
                    "order_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preorder_allocations",
                        to="order.orderline",
                    ),
                ),
                (
                    "product_variant_channel_listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preorder_allocations",
                        to="product.productvariantchannellisting",
                    ),
                ),
            ],
            options={
                "ordering": ("pk",),
                "unique_together": {("order_line", "product_variant_channel_listing")},
            },
        ),
    ]
