# Generated by Django 3.2.7 on 2021-09-21 10:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0015_alter_stock_quantity"),
        ("warehouse", "0015_auto_20210713_0904"),
    ]

    operations = []
