# Generated by Django 3.2.13 on 2022-04-29 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0046_alter_checkout_line_pk"),
        ("warehouse", "0027_alter_reservation_models_checkout_line"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preorderreservation",
            name="checkout_line_token",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="checkout.checkoutline"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="checkout_line_token",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="checkout.checkoutline"
            ),
        ),
        migrations.RemoveField(
            model_name="preorderreservation",
            name="checkout_line",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="checkout_line",
        ),
        migrations.RenameField(
            model_name="preorderreservation",
            old_name="checkout_line_token",
            new_name="checkout_line",
        ),
        migrations.RenameField(
            model_name="reservation",
            old_name="checkout_line_token",
            new_name="checkout_line",
        ),
        migrations.AlterField(
            model_name="preorderreservation",
            name="checkout_line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preorder_reservations",
                to="checkout.checkoutline",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="checkout_line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="checkout.checkoutline",
            ),
        ),
    ]
