# Generated by Django 3.2.13 on 2022-06-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channel", "0003_alter_channel_default_country"),
        ("warehouse", "0028_rewrite_checkouline_relations"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouse",
            name="channels",
            field=models.ManyToManyField(
                related_name="warehouses", to="channel.Channel"
            ),
        ),
    ]
