# Generated by Django 3.2.14 on 2022-08-19 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("channel", "0004_create_default_channel"),
        ("warehouse", "0031_create_default_warehouse"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE warehouse_warehouse_channels "
                        "RENAME TO warehouse_channelwarehouse"
                    ),
                    reverse_sql=(
                        "ALTER TABLE warehouse_channelwarehouse "
                        "RENAME TO warehouse_warehouse_channels"
                    ),
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="ChannelWarehouse",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "channel",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="channelwarehouse",
                                to="channel.channel",
                            ),
                        ),
                        (
                            "warehouse",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="channelwarehouse",
                                to="warehouse.warehouse",
                            ),
                        ),
                    ],
                ),
                migrations.AlterField(
                    model_name="warehouse",
                    name="channels",
                    field=models.ManyToManyField(
                        related_name="warehouses",
                        through="warehouse.ChannelWarehouse",
                        to="channel.Channel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="channelwarehouse",
            name="sort_order",
            field=models.IntegerField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="channelwarehouse",
            unique_together={("channel", "warehouse")},
        ),
        migrations.AlterModelOptions(
            name="channelwarehouse",
            options={"ordering": ("sort_order", "pk")},
        ),
    ]
