# Generated by Django 3.2.16 on 2022-12-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0032_alter_channel_warehouse"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouse",
            name="external_reference",
            field=models.CharField(
                blank=True, db_index=True, max_length=250, null=True, unique=True
            ),
        ),
    ]
