# Generated by Django 3.0.6 on 2020-07-17 09:37

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0016_auto_20200423_0314"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="action_required_data",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
            ),
        ),
    ]
