# Generated by Django 3.1 on 2020-08-10 13:10

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0017_payment_payment_method_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="return_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="action_required_data",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="charge_status",
            field=models.CharField(
                choices=[
                    ("not-charged", "Not charged"),
                    ("pending", "Pending"),
                    ("partially-charged", "Partially charged"),
                    ("fully-charged", "Fully charged"),
                    ("partially-refunded", "Partially refunded"),
                    ("fully-refunded", "Fully refunded"),
                    ("refused", "Refused"),
                    ("cancelled", "Cancelled"),
                ],
                default="not-charged",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="kind",
            field=models.CharField(
                choices=[
                    ("auth", "Authorization"),
                    ("pending", "Pending"),
                    ("refund", "Refund"),
                    ("refund_ongoing", "Refund in progress"),
                    ("capture", "Capture"),
                    ("void", "Void"),
                    ("confirm", "Confirm"),
                    ("cancel", "Cancel"),
                ],
                max_length=25,
            ),
        ),
    ]
