# Generated by Django 3.0.6 on 2020-07-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0017_transaction_action_required_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="charge_status",
            field=models.CharField(
                choices=[
                    ("action-required", "Action required"),
                    ("not-charged", "Not charged"),
                    ("partially-charged", "Partially charged"),
                    ("fully-charged", "Fully charged"),
                    ("partially-refunded", "Partially refunded"),
                    ("fully-refunded", "Fully refunded"),
                ],
                default="not-charged",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="kind",
            field=models.CharField(
                choices=[
                    ("action", "Action required"),
                    ("auth", "Authorization"),
                    ("refund", "Refund"),
                    ("refund_ongoing", "Refund in progress"),
                    ("capture", "Capture"),
                    ("void", "Void"),
                    ("confirm", "Confirm"),
                ],
                max_length=25,
            ),
        ),
    ]
