# Generated by Django 3.0.8 on 2020-07-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0018_auto_20200724_1200"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="return_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
