# Generated by Django 3.1 on 2020-08-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0018_auto_20200810_1310"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="already_processed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="kind",
            field=models.CharField(
                choices=[
                    ("auth", "Authorization"),
                    ("pending", "Pending"),
                    ("action_to_confirm", "Action to confirm"),
                    ("refund", "Refund"),
                    ("refund_ongoing", "Refund in progress"),
                    ("capture", "Capture"),
                    ("void", "Void"),
                    ("confirm", "Confirm"),
                    ("cancel", "Cancel"),
                ],
                max_length=25,
            ),
        ),
    ]
