# Generated by Django 3.0.6 on 2020-07-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0018_auto_20200720_1118"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="charge_status",
            field=models.CharField(
                choices=[
                    ("not-charged", "Not charged"),
                    ("pending", "Pending"),
                    ("partially-charged", "Partially charged"),
                    ("fully-charged", "Fully charged"),
                    ("partially-refunded", "Partially refunded"),
                    ("fully-refunded", "Fully refunded"),
                    ("refused", "Refused"),
                    ("cancelled", "Cancelled"),
                ],
                default="not-charged",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="kind",
            field=models.CharField(
                choices=[
                    ("auth", "Authorization"),
                    ("pending", "Pending"),
                    ("refund", "Refund"),
                    ("refund_ongoing", "Refund in progress"),
                    ("capture", "Capture"),
                    ("void", "Void"),
                    ("confirm", "Confirm"),
                    ("cancel", "Cancel"),
                ],
                max_length=25,
            ),
        ),
    ]
