# Generated by Django 3.1 on 2020-08-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0019_auto_20200812_0521"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="already_processed",
            field=models.BooleanField(default=False),
        ),
    ]
