# Generated by Django 3.1 on 2020-09-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0020_auto_20200902_1249"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="searchable_key",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
