# Generated by Django 3.1.2 on 2020-10-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0021_transaction_searchable_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="kind",
            field=models.CharField(
                choices=[
                    ("external", "External reference"),
                    ("auth", "Authorization"),
                    ("pending", "Pending"),
                    ("action_to_confirm", "Action to confirm"),
                    ("refund", "Refund"),
                    ("refund_ongoing", "Refund in progress"),
                    ("capture", "Capture"),
                    ("void", "Void"),
                    ("confirm", "Confirm"),
                    ("cancel", "Cancel"),
                ],
                max_length=25,
            ),
        ),
    ]
