# Generated by Django 3.1.2 on 2021-02-26 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0022_auto_20201104_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonchiquePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=None, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.payment')),
            ],
        ),
    ]
