# Generated by Django 3.1.8 on 2021-04-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0024_auto_20210326_0837"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="searchable_key",
            field=models.CharField(
                blank=True, db_index=True, max_length=512, null=True
            ),
        ),
    ]
