# Generated by Django 3.2.2 on 2021-05-14 12:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0027_assign_psp_reference_values"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="searchable_key",
        ),
    ]
