# Generated by Django 3.2.2 on 2021-05-18 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0026_merge_20210511_1153"),
        ("payment", "0028_drop_searchable_key"),
    ]

    operations = []
