# Generated by Django 3.2.5 on 2021-08-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0029_alter_payment_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="complete_order",
            field=models.BooleanField(default=False),
        ),
    ]
