# Generated by Django 3.2.5 on 2021-08-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0029_alter_payment_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="charge_status",
            field=models.CharField(
                choices=[
                    ("not-charged", "Not charged"),
                    ("authorized", "Authorized"),
                    ("pending", "Pending"),
                    ("partially-charged", "Partially charged"),
                    ("fully-charged", "Fully charged"),
                    ("partially-refunded", "Partially refunded"),
                    ("fully-refunded", "Fully refunded"),
                    ("refused", "Refused"),
                    ("cancelled", "Cancelled"),
                    ("overpaid", "Overpaid"),
                ],
                default="not-charged",
                max_length=20,
            ),
        ),
    ]
