# Generated by Django 3.2.5 on 2021-08-26 16:36

from django.db import migrations

from saleor.payment import ChargeStatus, TransactionKind


def migrate_voided_transactions(apps, schema_editor):
    Transaction = apps.get_model("payment", "Transaction")

    for ct in (
        Transaction.objects.filter(
            payment__charge_status=ChargeStatus.NOT_CHARGED,
            is_success=True,
            kind=TransactionKind.VOID,
        )
        .select_related("payment")
        .iterator()
    ):
        ct.payment.charge_status = ChargeStatus.CANCELLED
        ct.payment.save(update_fields=["charge_status"])


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0030_alter_payment_charge_status"),
    ]

    operations = [
        migrations.RunPython(migrate_voided_transactions),
    ]
