# Generated by Django 3.2.5 on 2021-08-26 16:36

from django.db import migrations

from saleor.payment import ChargeStatus, TransactionKind


def migrate_voided_transactions(apps, schema_editor):
    Payment = apps.get_model("payment", "Payment")

    Payment.objects.filter(
        charge_status=ChargeStatus.NOT_CHARGED,
        transactions__is_success=True,
        transactions__kind=TransactionKind.VOID,
    ).update(charge_status=ChargeStatus.CANCELLED)


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0030_alter_payment_charge_status"),
    ]

    operations = [
        migrations.RunPython(migrate_voided_transactions),
    ]
