# Generated by Django 3.2.5 on 2021-08-26 16:36

from django.db import migrations

from saleor.payment import ChargeStatus, TransactionKind


def migrate_not_charged_transactions(apps, schema_editor):
    Payment = apps.get_model("payment", "Payment")
    for payment in Payment.objects.filter(
        charge_status=ChargeStatus.NOT_CHARGED,
    ):
        for txn in payment.transactions.all():
            if not txn.is_success:
                continue

            if txn.kind == TransactionKind.AUTH and not txn.action_required:
                payment.charge_status = ChargeStatus.AUTHORIZED
                payment.save(update_fields=["charge_status"])
                break

            elif txn.kind == TransactionKind.VOID:
                payment.charge_status = ChargeStatus.CANCELLED
                payment.save(update_fields=["charge_status"])
                break


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0030_alter_payment_charge_status"),
    ]

    operations = [
        migrations.RunPython(migrate_not_charged_transactions),
    ]
