# Generated by Django 3.2.5 on 2021-09-02 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0030_auto_20210825_1338"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="store",
            new_name="store_payment_method",
        ),
    ]
