# Generated by Django 3.2.12 on 2022-03-15 11:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0031_merge_0030_auto_20210908_1346_0030_payment_partial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="authorized_value",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="payment",
            name="available_actions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("capture", "Capture payment"),
                        ("refund", "Refund payment"),
                        ("void", "Void payment"),
                        ("MARK_AS_PAID", "Mark as paid"),
                    ],
                    max_length=128,
                ),
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="captured_value",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="payment",
            name="reference",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AddField(
            model_name="payment",
            name="refunded_value",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AddField(
            model_name="payment",
            name="type",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AddField(
            model_name="payment",
            name="voided_value",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
