# Generated by Django 3.2.5 on 2021-08-27 07:17

from django.db import migrations

from saleor.payment import ChargeStatus, TransactionKind


def migrate_authorized_transactions(apps, schema_editor):
    Payment = apps.get_model("payment", "Payment")

    Payment.objects.filter(
        charge_status=ChargeStatus.NOT_CHARGED,
        transactions__is_success=True,
        transactions__action_required=False,
        transactions__kind=TransactionKind.AUTH,
    ).update(charge_status=ChargeStatus.AUTHORIZED)


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0031_auto_20210826_1636"),
    ]

    operations = [
        migrations.RunPython(migrate_authorized_transactions),
    ]
