# Generated by Django 3.2.5 on 2021-08-27 07:17

from django.db import migrations

from saleor.payment import ChargeStatus, TransactionKind


def migrate_authorized_transactions(apps, schema_editor):
    Transaction = apps.get_model("payment", "Transaction")

    for ct in Transaction.objects.filter(
        payment__charge_status=ChargeStatus.NOT_CHARGED,
        is_success=True,
        kind=TransactionKind.AUTH,
        action_required=False,
    ).iterator():
        ct.payment.charge_status = ChargeStatus.AUTHORIZED
        ct.payment.save(update_fields=["charge_status"])


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0031_auto_20210826_1636"),
    ]

    operations = [
        migrations.RunPython(migrate_authorized_transactions),
    ]
