# Generated by Django 3.2.12 on 2022-02-25 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0131_change_pk_to_uuid"),
        ("payment", "0032_save_payment_order_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="order_token",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="order.order"
            ),
        ),
        migrations.RemoveField(
            model_name="payment",
            name="order",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="order_token",
            new_name="order",
        ),
        migrations.AlterField(
            model_name="payment",
            name="order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="order.order",
            ),
        ),
    ]
