# Generated by Django 3.2.12 on 2022-03-04 09:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0032_auto_20220303_1719"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentpoc",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymentpoc",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
