# Generated by Django 3.2.6 on 2021-09-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0032_auto_20210827_0717"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="create_order",
            field=models.BooleanField(
                blank=True,
                help_text=(
                    "Indicates whether a payment should convert "
                    "a checkout into an order. "
                    "Used for partial payments."
                ),
                null=True,
            ),
        ),
    ]
