# Generated by Django 3.2.8 on 2021-11-20 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0030_auto_20210908_1346"),
        ("payment", "0033_payment_complete_order"),
    ]

    operations = []
