# Generated by Django 3.2.5 on 2021-09-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0033_payment_complete_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="partial",
            field=models.BooleanField(default=False),
        ),
    ]
