# Generated by Django 3.2.6 on 2021-09-27 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0033_payment_create_order"),
        ("payment", "0034_payment_partial"),
    ]

    operations = []
