# Generated by Django 3.2.12 on 2022-04-19 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0034_auto_20220415_0706"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failure", "Failure"),
                        ],
                        default="success",
                        max_length=128,
                    ),
                ),
                ("reference", models.CharField(blank=True, default="", max_length=512)),
                ("name", models.CharField(blank=True, default="", max_length=512)),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="payment.transactionitem",
                    ),
                ),
            ],
            options={
                "ordering": ("pk",),
            },
        ),
    ]
