# Generated by Django 3.2.15 on 2022-09-16 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_alter_appextension_mount"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payment", "0038_transactionitem_pending_refund_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionitem",
            name="app",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="app.app",
            ),
        ),
        migrations.AddField(
            model_name="transactionitem",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
