# Generated by Django 3.2.18 on 2023-03-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0041_add_calculation_transaction_events"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionitem",
            name="token",
            field=models.UUIDField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="transactionitem",
            name="use_old_id",
            field=models.BooleanField(default=True),
        ),
        migrations.RunSQL(
            """
            ALTER TABLE payment_transactionitem
            ALTER COLUMN use_old_id
            SET DEFAULT true;
            """,
            migrations.RunSQL.noop,
        ),
    ]
