# Generated by Django 3.2.16 on 2022-12-06 10:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0043_auto_20220922_1146"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionevent",
            name="message",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AlterField(
            model_name="transactionevent",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
