# Generated by Django 3.2.19 on 2023-06-05 11:14

import django.contrib.postgres.fields
from django.apps import apps as registry
from django.db import migrations, models
from django.db.models.signals import post_migrate

from .tasks.saleor3_14 import convert_transaction_void_to_cancel_task


def convert_void_to_cancel(apps, _schema_editor):
    def on_migrations_complete(sender=None, **kwargs):
        convert_transaction_void_to_cancel_task.delay()

    sender = registry.get_app_config("order")
    post_migrate.connect(on_migrations_complete, weak=False, sender=sender)


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0050_drop_unused_transaction_fields"),
    ]

    operations = [
        migrations.RunPython(convert_void_to_cancel, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="transactionitem",
            name="available_actions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("charge", "Charge payment"),
                        ("refund", "Refund payment"),
                        ("cancel", "Cancel payment"),
                    ],
                    max_length=128,
                ),
                default=list,
                size=None,
            ),
        ),
    ]
