# Generated by Django 3.2.19 on 2023-06-01 08:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0051_alter_transactionitem_available_actions"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="transactionitem",
            name="payment_tra_order_i_e783c4_gin",
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="transactionitem",
                    name="status",
                ),
                migrations.RemoveField(
                    model_name="transactionevent",
                    name="status",
                ),
            ]
        ),
    ]
