# Generated by Django 3.2.22 on 2023-11-22 08:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0052_transactionitem_last_refund_success"),
        ("payment", "0053_auto_20230601_0818"),
    ]

    operations = []
