# Generated by Django 3.2.22 on 2023-12-12 16:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0054_add_idempotency_key_indexes"),
        ("payment", "0054_merge_20231122_0828"),
    ]

    operations = []
