# Generated by Django 3.2.25 on 2024-07-31 10:07

from django.contrib.postgres.indexes import GinIndex
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("payment", "0056_fix_invalid_atobarai_payments"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="transaction",
            index=GinIndex(
                fields=["token"],
                name="token_idx",
            ),
        ),
    ]
