# Generated by Django 3.2.23 on 2024-03-07 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0185_ordergrantedrefund_transaction_item"),
        ("payment", "0056_merge_20231213_0755"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionevent",
            name="related_granted_refund",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transaction_events",
                to="order.ordergrantedrefund",
            ),
        ),
    ]
