# Generated by Django 3.2.25 on 2024-05-14 10:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0057_merge_20240514_0825"),
        ("payment", "0057_transactionevent_related_granted_refund"),
    ]

    operations = []
