# Generated by Django 3.2.25 on 2024-08-02 11:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0057_merge_20240514_0825"),
        ("payment", "0057_transaction_token_idx"),
    ]

    operations = []
