# Generated by Django 3.2.25 on 2024-08-02 11:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0058_merge_20240514_1004"),
        ("payment", "0058_merge_20240802_1119"),
    ]

    operations = []
