# Generated by Django 4.2.15 on 2025-07-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0060_alter_payment_captured_amount_alter_payment_total_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="legacy_adyen_plugin_payment_method",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="legacy_adyen_plugin_result_code",
            field=models.TextField(null=True),
        ),
    ]
