# Generated by Django 5.2.1 on 2025-06-18 08:13

from django.contrib.postgres.indexes import BTreeIndex
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("account", "0087_alter_address_metadata_and_more"),
        ("app", "0031_alter_appextension_mount_alter_appextension_target"),
        ("checkout", "0080_merge_20250527_1210"),
        ("order", "0210_populated_order_line_product_type_id"),
        ("payment", "0062_transactionitem_cc_brand_and_more"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="transactionitem",
            index=BTreeIndex(
                fields=["payment_method_type"], name="payment_method_type_ids"
            ),
        ),
        AddIndexConcurrently(
            model_name="transactionitem",
            index=BTreeIndex(fields=["cc_brand"], name="cc_brand_idx"),
        ),
    ]
