# Generated by Django 5.2.1 on 2025-07-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0063_transactionitem_payment_method_type_ids_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="legacy_adyen_plugin_payment_method",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="legacy_adyen_plugin_result_code",
            field=models.TextField(null=True),
        ),
    ]
