# Generated by Django 5.2.1 on 2025-08-12 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("page", "0031_alter_page_metadata_alter_page_private_metadata_and_more"),
        ("payment", "0064_merge_20250716_0709"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionevent",
            name="reason_reference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="page.page",
            ),
        ),
    ]
