# Generated by Django 5.2.5 on 2025-11-06 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("giftcard", "0022_merge_20250527_1210"),
        ("payment", "0065_transactionevent_reason_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionitem",
            name="gift_card",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="giftcard.giftcard",
            ),
        ),
    ]
