# Generated by Django 5.2.8 on 2026-03-11 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0235_order_allow_variant_reallocation"),
        ("payment", "0066_transactionitem_gift_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="fulfillment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="order.fulfillment",
            ),
        ),
    ]
