# Generated by Django 5.2.8 on 2026-02-06 10:58

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("account", "0095_repopulate_user_number_of_orders"),
        ("app", "0034_alter_appextension_mount"),
        ("checkout", "0088_reapply_fix_shared_address_instances"),
        ("order", "0219_merge_20251212_0955"),
        ("payment", "0066_transactionitem_psp_reference_idx"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="transactionitem",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["app_identifier"], name="app_identifier_idx"
            ),
        ),
    ]
