# Generated by Django 5.2.11 on 2026-03-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0068_merge_20260206_1216"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionitem",
            name="gift_card_display_code",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
