# Generated by Django 5.2.11 on 2026-03-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0068_merge_20260206_1216"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionitem",
            name="gift_card_brand",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="transactionitem",
            name="gift_card_last_4_chars",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name="transactionitem",
            name="payment_method_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("card", "Card"),
                    ("other", "Other"),
                    ("gift_card", "Gift card"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
