# Generated by Django 5.2.11 on 2026-03-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0069_transactionitem_gc_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="partial",
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
