# Generated by Django 5.2.11 on 2026-03-11 10:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0069_transactionitem_gc_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="partial",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="legacy_adyen_plugin_payment_method",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="legacy_adyen_plugin_result_code",
        ),
    ]
