# Generated by Django 5.2.11 on 2026-03-11 12:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "payment",
            "0070_remove_transaction_legacy_adyen_plugin_payment_method_and_more",
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="payment",
                    name="partial",
                ),
                migrations.RemoveField(
                    model_name="transaction",
                    name="legacy_adyen_plugin_payment_method",
                ),
                migrations.RemoveField(
                    model_name="transaction",
                    name="legacy_adyen_plugin_result_code",
                ),
            ],
        )
    ]
