# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 00:19
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_prices.models
import jsonfield.fields
import satchless.item
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discount', '0005_auto_20170303_0041'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0013_auto_20170404_0219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('status', models.CharField(choices=[('open', 'Open - currently active'), ('payment', 'Waiting for payment'), ('saved', 'Saved - for items to be purchased later'), ('ordered', 'Submitted - an order was placed'), ('checkout', 'Checkout - processed in checkout'), ('canceled', 'Canceled - canceled by user')], default='open', max_length=32, verbose_name='order status')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('last_status_change', models.DateTimeField(auto_now_add=True, verbose_name='last status change')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='token')),
                ('checkout_data', jsonfield.fields.JSONField(editable=False, null=True, verbose_name='checkout data')),
                ('total', django_prices.models.PriceField(currency='EUR', decimal_places=2, default=0, max_digits=12, verbose_name='total')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='quantity')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('voucher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='discount.Voucher', verbose_name='token')),
            ],
            options={
                'ordering': ('-last_status_change',),
                'verbose_name_plural': 'Carts',
                'verbose_name': 'Cart',
            },
        ),
        migrations.CreateModel(
            name='CartLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)], verbose_name='quantity')),
                ('data', jsonfield.fields.JSONField(blank=True, default={}, verbose_name='data')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='cart.Cart', verbose_name='cart')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='product.ProductVariant', verbose_name='product')),
            ],
            options={
                'verbose_name_plural': 'Cart lines',
                'verbose_name': 'Cart line',
            },
            bases=(models.Model, satchless.item.ItemLine),
        ),
        migrations.AlterUniqueTogether(
            name='cartline',
            unique_together=set([('cart', 'variant', 'data')]),
        ),
    ]
