# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-01-24 22:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartline',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='cartline',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartline',
            name='variant',
        ),
        migrations.DeleteModel(
            name='CartLine',
        ),
    ]
