# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 12:52
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', 'fix_empty_data_in_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='checkout_data_postgres',
            field=django.contrib.postgres.fields.jsonb.JSONField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='cartline',
            name='data_postgres',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
    ]
