# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django_prices.models


def split_total_to_total_net_and_gross(apps, schema_editor):
    Cart = apps.get_model('cart', 'Cart')
    for cart in Cart.objects.all():
        cart.total_net = cart.total
        cart.total_gross = cart.total
        cart.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20171129_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=django_prices.models.AmountField(verbose_name='price',
                                                   max_digits=12,
                                                   decimal_places=2,
                                                   currency='USD', blank=True,
                                                   null=True)),
        migrations.AddField(
            model_name='cart',
            name='total_net',
            field=django_prices.models.AmountField(verbose_name='total net', max_digits=12, decimal_places=2, currency='USD', blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='total_gross',
            field=django_prices.models.AmountField(verbose_name='total gross', max_digits=12, decimal_places=2, currency='USD', blank=True, null=True),
        ),
        migrations.RunPython(split_total_to_total_net_and_gross),
    ]
