# Generated by Django 2.0.3 on 2018-05-24 09:14

from django.db import migrations, models
import django.db.models.deletion
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0008_auto_20180108_0814'),
        ('product', '0063_required_attr_value_order'),
        ('account', '0018_auto_20180426_0641'),
        ('cart', '0006_auto_20180221_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='status',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='checkout_data',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='voucher',
        ),
        migrations.AddField(
            model_name='cart',
            name='billing_address',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='account.Address'),
        ),
        migrations.AddField(
            model_name='cart',
            name='discount_amount',
            field=django_prices.models.MoneyField(currency='USD', decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cart',
            name='discount_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cart',
            name='shipping_address',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='account.Address'),
        ),
        migrations.AddField(
            model_name='cart',
            name='shipping_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='shipping.ShippingMethodCountry'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='cart',
            name='voucher_code',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
