# Generated by Django 3.2.16 on 2022-12-14 12:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="Group",
                ),
                migrations.DeleteModel(
                    name="Permission",
                ),
                migrations.DeleteModel(
                    name="User",
                ),
            ]
        )
    ]
