# Generated by Django 3.1.7 on 2021-03-03 13:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0030_checkout_channel_listing"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="checkoutline",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="checkoutline",
            name="data",
        ),
    ]
