# Generated by Django 3.2.6 on 2021-09-03 10:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0036_alter_checkout_language_code"),
        ("checkout", "0036_merge_20210824_1103"),
    ]

    operations = []
