# Generated by Django 3.2.18 on 2023-03-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0057_remove_metadata_from_checkout_model_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkout",
            name="authorize_status",
            field=models.CharField(
                choices=[
                    ("none", "The checkout is not authorized"),
                    ("partial", "The checkout is partially authorized"),
                    ("full", "The checkout is fully authorized"),
                ],
                db_index=True,
                default="none",
                max_length=32,
            ),
        ),
        migrations.RunSQL(
            """
            ALTER TABLE checkout_checkout
            ALTER COLUMN authorize_status
            SET DEFAULT 'none';
            """,
            migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name="checkout",
            name="charge_status",
            field=models.CharField(
                choices=[
                    ("none", "The checkout is not charged"),
                    ("partial", "The checkout is partially charged"),
                    ("full", "The checkout is fully charged"),
                    ("overcharged", "The checkout is overcharged"),
                ],
                db_index=True,
                default="none",
                max_length=32,
            ),
        ),
        migrations.RunSQL(
            """
            ALTER TABLE checkout_checkout
            ALTER COLUMN charge_status
            SET DEFAULT 'none';
            """,
            migrations.RunSQL.noop,
        ),
    ]
