# Generated by Django 3.2.23 on 2024-02-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0064_checkoutline_is_gift"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkout",
            name="tax_error",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
