# Generated by Django 4.2.15 on 2025-03-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0073_checkout_external_shipping_method_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkout",
            name="external_shipping_method_id",
            field=models.CharField(
                blank=True, default=None, editable=False, max_length=512, null=True
            ),
        ),
    ]
