# Generated by Django 4.2.26 on 2025-12-08 11:22

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("checkout", "0076_checkout_discount_expiration"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="checkout",
            index=models.Index(fields=["created_at"], name="idx_checkout_created_at"),
        ),
    ]
