# Generated by Django 4.2.26 on 2025-12-02 11:13

from django.apps import apps as registry
from django.db import migrations
from django.db.models.signals import post_migrate

from .tasks.saleor3_20 import clean_duplicated_gift_lines_task


def clean_duplicated_gift_lines(apps, _schema_editor):
    def on_migrations_complete(sender=None, **kwargs):
        clean_duplicated_gift_lines_task.delay()

    sender = registry.get_app_config("checkout")
    post_migrate.connect(on_migrations_complete, weak=False, sender=sender)


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0077_checkout_idx_checkout_created_at"),
    ]

    operations = [
        migrations.RunPython(
            clean_duplicated_gift_lines,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
