# Generated by Django 5.2 on 2025-04-18 10:39

from django.db import migrations, models

import saleor.core.utils.json_serializer


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0077_merge_20250303_0958"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkoutline",
            name="metadata",
            field=models.JSONField(
                blank=True,
                db_default={},
                default=dict,
                encoder=saleor.core.utils.json_serializer.CustomJsonEncoder,
            ),
        ),
        migrations.AlterField(
            model_name="checkoutline",
            name="private_metadata",
            field=models.JSONField(
                blank=True,
                db_default={},
                default=dict,
                encoder=saleor.core.utils.json_serializer.CustomJsonEncoder,
            ),
        ),
        migrations.AlterField(
            model_name="checkoutmetadata",
            name="metadata",
            field=models.JSONField(
                blank=True,
                db_default={},
                default=dict,
                encoder=saleor.core.utils.json_serializer.CustomJsonEncoder,
            ),
        ),
        migrations.AlterField(
            model_name="checkoutmetadata",
            name="private_metadata",
            field=models.JSONField(
                blank=True,
                db_default={},
                default=dict,
                encoder=saleor.core.utils.json_serializer.CustomJsonEncoder,
            ),
        ),
    ]
