# Generated by Django 4.2.26 on 2025-11-07 11:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0076_checkout_discount_expiration"),
        ("checkout", "0080_alter_checkout_external_shipping_method_id"),
    ]

    operations = []
