# Generated by Django 5.2.5 on 2025-11-03 09:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0080_alter_checkout_external_shipping_method_id"),
        ("checkout", "0080_merge_20250527_1210"),
    ]

    operations = []
