# Generated by Django 4.2.26 on 2025-12-22 10:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0082_merge_20251211_1339"),
    ]

    # empty migration for history consistency
    operations = []
