# Generated by Django 5.2.8 on 2025-12-23 12:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0083_fix_shared_address_instances"),
        ("checkout", "0086_merge_20251212_0956"),
    ]

    operations = []
