# Generated by Django 5.0.7 on 2024-08-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_terminal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
