# Generated by Django 2.0.3 on 2018-08-14 07:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_cart_translated_discount_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartline',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
    ]
