# Generated by Django 2.0.8 on 2018-09-28 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0014_auto_20180921_0751'),
        ('checkout', '0011_auto_20180814_0216'),
    ]

    operations = [
    ]
