# Generated by Django 2.1.2 on 2018-10-17 18:46

from django.conf import settings
from django.db import migrations
import django_prices.models
import saleor.core


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0014_auto_20180921_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='discount_amount',
            field=django_prices.models.MoneyField(currency=settings.DEFAULT_CURRENCY, decimal_places=2, default=saleor.core.utils.taxes.zero_money, max_digits=12),
        ),
    ]
