# Generated by Django 2.1.2 on 2018-10-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("checkout", "0014_auto_20180921_0751")]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        )
    ]
