# Generated by Django 2.1.5 on 2019-01-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("checkout", "0016_auto_20190112_0506")]

    operations = [
        migrations.AlterField(
            model_name="cart", name="email", field=models.EmailField(max_length=254)
        )
    ]
