# Generated by Django 2.2 on 2019-04-12 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0091_auto_20190402_0853"),
        ("payment", "0010_auto_20190220_2001"),
        ("shipping", "0015_auto_20190305_0640"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("checkout", "0017_auto_20190130_0207"),
        ("account", "0026_user_avatar"),
    ]

    operations = [
        migrations.RenameModel(old_name="Cart", new_name="Checkout"),
        migrations.RenameField(
            model_name="cartline", old_name="cart", new_name="checkout"
        ),
        migrations.AlterUniqueTogether(
            name="cartline", unique_together={("checkout", "variant", "data")}
        ),
        migrations.AlterField(
            model_name="checkout",
            name="shipping_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checkouts",
                to="shipping.ShippingMethod",
            ),
        ),
        migrations.AlterField(
            model_name="checkout",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checkouts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RenameModel(old_name="CartLine", new_name="CheckoutLine"),
    ]
