# Generated by Django 2.2.9 on 2020-01-09 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0022_auto_20191219_1137"),
        ("checkout", "0022_auto_20200108_1739"),
    ]

    operations = []
