# Generated by Django 2.2.10 on 2020-02-21 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0024_auto_20200120_0154"),
    ]

    operations = [
        migrations.RenameField(
            model_name="checkout", old_name="meta", new_name="metadata",
        ),
        migrations.RenameField(
            model_name="checkout", old_name="private_meta", new_name="private_metadata",
        ),
    ]
