# Generated by Django 3.0.6 on 2020-06-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0025_auto_20200221_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
