# Generated by Django 3.1 on 2020-08-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0027_auto_20200810_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='delivery_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
