# Generated by Django 3.1 on 2020-08-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0027_auto_20200810_1415"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkout",
            name="redirect_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="checkout",
            name="tracking_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
