# Generated by Django 3.1.7 on 2021-03-03 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0141_update_descritpion_fields"),
        ("checkout", "0030_checkout_channel_listing"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="checkoutline",
            unique_together={("checkout", "variant")},
        ),
        migrations.RemoveField(
            model_name="checkoutline",
            name="data",
        ),
    ]
