# Generated by Django 3.1.7 on 2021-03-08 11:35

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0031_auto_20210303_1045"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="checkout",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["private_metadata"], name="checkout_p_meta_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="checkout",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["metadata"], name="checkout_meta_idx"
            ),
        ),
    ]
