# Generated by Django 3.1.1 on 2020-10-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0031_auto_20200819_0912"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkout",
            name="currency",
            field=models.CharField(max_length=3),
        ),
    ]
