# Generated by Django 3.2.6 on 2021-08-24 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0035_alter_checkout_language_code"),
        ("checkout", "0035_checkout_collection_point"),
    ]

    operations = []
