# Generated by Django 3.2.6 on 2021-09-03 09:16

from django.db import migrations


def remove_empty_lines(apps, schema_editor):
    CheckoutLine = apps.get_model("checkout", "CheckoutLine")
    CheckoutLine.objects.filter(quantity=0).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0036_alter_checkout_language_code"),
    ]

    operations = [
        migrations.RunPython(remove_empty_lines, migrations.RunPython.noop),
    ]
