# Generated by Django 3.2.12 on 2022-04-14 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_alter_channel_default_country'),
        ('checkout', '0037_remove_empty_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='alternative_channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alternative_checkouts', to='channel.channel'),
        ),
    ]
