# Generated by Django 3.2.6 on 2021-09-03 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0037_merge_20210903_1013"),
        ("checkout", "0037_remove_empty_lines"),
    ]

    operations = []
