# Generated by Django 3.2.5 on 2021-09-09 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0038_merge_20210903_1048"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="checkout",
            options={
                "ordering": ("-last_change", "pk"),
                "permissions": (
                    ("manage_checkouts", "Manage checkouts"),
                    ("handle_taxes", "Handle taxes"),
                ),
            },
        ),
    ]
