# Generated by Django 3.2.12 on 2022-04-15 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_alter_channel_default_country'),
        ('checkout', '0038_checkout_alternative_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='alternative_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alternative_checkouts', to='channel.channel'),
        ),
    ]
