# Generated by Django 3.2.6 on 2022-01-20 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0039_alter_checkout_email"),
        ("checkout", "0041_auto_20211206_1659"),
    ]

    operations = []
