# Generated by Django 3.2.12 on 2022-04-07 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0041_auto_20220329_1612"),
        ("checkout", "0041_checkoutline_price_override"),
    ]

    operations = []
