# Generated by Django 3.2.13 on 2022-04-12 08:25

from decimal import Decimal

import django.utils.timezone
from django.core.management.sql import emit_post_migrate_signal
from django.db import migrations, models


def assign_permission(apps, schema_editor):
    # force post signal as permissions are created in post migrate signals
    # related Django issue https://code.djangoproject.com/ticket/23422
    emit_post_migrate_signal(2, False, "default")
    Permission = apps.get_model("auth", "Permission")
    App = apps.get_model("app", "App")
    Group = apps.get_model("auth", "Group")

    handle_taxes = Permission.objects.filter(
        codename="handle_taxes", content_type__app_label="checkout"
    ).first()
    manage_checkouts = Permission.objects.filter(
        codename="manage_checkouts", content_type__app_label="checkout"
    ).first()

    apps = App.objects.filter(
        permissions=manage_checkouts,
    )
    for app in apps.iterator():
        app.permissions.add(handle_taxes)

    groups = Group.objects.filter(
        permissions=manage_checkouts,
    )
    for group in groups.iterator():
        group.permissions.add(handle_taxes)


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0042_rename_created_checkout_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="checkout",
            options={
                "ordering": ("-last_change", "pk"),
                "permissions": (
                    ("manage_checkouts", "Manage checkouts"),
                    ("handle_checkouts", "Handle checkouts"),
                    ("handle_taxes", "Handle taxes"),
                ),
            },
        ),
        migrations.RunPython(assign_permission),
        migrations.AddField(
            model_name="checkout",
            name="price_expiration",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="checkout",
            name="shipping_price_gross_amount",
            field=models.DecimalField(
                decimal_places=3, default=Decimal(0), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="checkout",
            name="shipping_price_net_amount",
            field=models.DecimalField(
                decimal_places=3, default=Decimal(0), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="checkout",
            name="shipping_tax_rate",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.0"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="checkout",
            name="subtotal_gross_amount",
            field=models.DecimalField(
                decimal_places=3, default=Decimal(0), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="checkout",
            name="subtotal_net_amount",
            field=models.DecimalField(
                decimal_places=3, default=Decimal(0), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="checkout",
            name="total_gross_amount",
            field=models.DecimalField(
                decimal_places=3, default=Decimal(0), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="checkout",
            name="total_net_amount",
            field=models.DecimalField(
                decimal_places=3, default=Decimal(0), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="checkoutline",
            name="currency",
            field=models.CharField(null=True, max_length=3),
        ),
    ]
