# Generated by Django 3.2.12 on 2022-03-28 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0044_merge_20220328_1303"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="checkout",
            options={
                "ordering": ("-last_change", "pk"),
                "permissions": (
                    ("manage_checkouts", "Manage checkouts"),
                    ("handle_checkouts", "Handle checkouts"),
                    ("handle_taxes", "Handle taxes"),
                ),
            },
        ),
    ]
