# Generated by Django 3.2.13 on 2022-05-19 10:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0043_alter_checkout_voucher_code"),
        ("checkout", "0046_alter_checkout_line_pk"),
    ]

    operations = []
