# Generated by Django 3.2.13 on 2022-05-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0046_alter_checkout_line_pk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkout",
            name="voucher_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
