# Generated by Django 3.2.13 on 2022-06-10 10:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0048_alter_checkoutline_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkout",
            name="promo_codes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), default=list, size=None
            ),
        ),
    ]
