# Generated by Django 3.2.13 on 2022-06-02 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0048_alter_checkoutline_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='country',
        ),
    ]
