# Generated by Django 3.2.13 on 2022-04-12 08:25

from decimal import Decimal

import django.utils.timezone
from django.db import migrations, models
from django.db.models.signals import post_migrate


def assign_permissions(apps, schema_editor):
    def on_migrations_complete(sender=None, **kwargs):
        Permission = apps.get_model("auth", "Permission")
        App = apps.get_model("app", "App")
        Group = apps.get_model("auth", "Group")

        handle_taxes = Permission.objects.filter(
            codename="handle_taxes", content_type__app_label="checkout"
        ).first()
        manage_checkouts = Permission.objects.filter(
            codename="manage_checkouts", content_type__app_label="checkout"
        ).first()

        apps_qs = App.objects.filter(
            permissions=manage_checkouts,
        )
        for app in apps_qs.iterator():
            app.permissions.add(handle_taxes)

        groups = Group.objects.filter(
            permissions=manage_checkouts,
        )
        for group in groups.iterator():
            group.permissions.add(handle_taxes)

    post_migrate.connect(on_migrations_complete, weak=False)


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0049_auto_20220621_0850"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="checkout",
            options={
                "ordering": ("-last_change", "pk"),
                "permissions": (
                    ("manage_checkouts", "Manage checkouts"),
                    ("handle_checkouts", "Handle checkouts"),
                    ("handle_taxes", "Handle taxes"),
                ),
            },
        ),
        migrations.RunPython(assign_permissions),
        migrations.AddField(
            model_name="checkout",
            name="price_expiration",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="checkout",
            name="shipping_price_gross_amount",
            field=models.DecimalField(
                decimal_places=3, default=Decimal(0), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="checkout",
            name="shipping_price_net_amount",
            field=models.DecimalField(
                decimal_places=3, default=Decimal(0), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="checkout",
            name="shipping_tax_rate",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.0"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="checkout",
            name="subtotal_gross_amount",
            field=models.DecimalField(
                decimal_places=3, default=Decimal(0), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="checkout",
            name="subtotal_net_amount",
            field=models.DecimalField(
                decimal_places=3, default=Decimal(0), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="checkout",
            name="total_gross_amount",
            field=models.DecimalField(
                decimal_places=3, default=Decimal(0), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="checkout",
            name="total_net_amount",
            field=models.DecimalField(
                decimal_places=3, default=Decimal(0), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="checkoutline",
            name="currency",
            field=models.CharField(null=True, max_length=3),
        ),
    ]
