# Generated by Django 3.2.13 on 2022-06-02 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0049_remove_checkout_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='channel',
        ),
    ]
