# Generated by Django 3.2.13 on 2022-04-12 08:28

from django.db import migrations


def set_default_checkout_line_currency(apps, schema_editor):
    Checkout = apps.get_model("checkout", "Checkout")
    CheckoutLine = apps.get_model("checkout", "CheckoutLine")

    for currency in Checkout.objects.values_list("currency", flat=True):
        CheckoutLine.objects.filter(currency=None, checkout__currency=currency).update(
            currency=currency
        )


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0050_create_checkout_tax_fields"),
    ]

    operations = [
        migrations.RunPython(set_default_checkout_line_currency),
    ]
