# Generated by Django 3.2.12 on 2022-05-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0053_alter_checkout_shipping_tax_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkout",
            name="shipping_tax_rate",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="checkoutline",
            name="tax_rate",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
