# Generated by Django 3.2.15 on 2022-09-26 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0055_auto_20220921_1115"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkoutmetadata",
            name="checkout",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metadata_storage",
                to="checkout.checkout",
            ),
        ),
    ]
