# Generated by Django 3.2.18 on 2023-04-03 08:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0058_auto_20230313_1602"),
        ("checkout", "0058_merge_0055_add_last_change_idx"),
    ]

    operations = []
