# Generated by Django 3.2.22 on 2023-10-11 10:59

from django.db import migrations


# TODO: TEMPORTATY MIGRATION FOR TESTING PURPOSES
# SHOULD BE REMOVED BEFORE MERGE
class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0059_merge_0058"),
    ]

    operations = []
