# Generated by Django 3.2.22 on 2023-11-15 08:30
from django.apps import apps as registry
from django.db import migrations, models
from django.db.models.signals import post_migrate

from .tasks.saleor3_13 import update_transaction_modified_at_in_checkouts


def add_transaction_modified_at_to_checkouts(apps, _schema_editor):
    def on_migrations_complete(sender=None, **kwargs):
        update_transaction_modified_at_in_checkouts.delay()

    sender = registry.get_app_config("checkout")
    post_migrate.connect(on_migrations_complete, weak=False, sender=sender)


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0060_fix_charge_and_authorize_status_for_empty_checkouts"),
        ("payment", "0049_auto_20230322_0634"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkout",
            name="last_transaction_modified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
