# Generated by Django 3.2.22 on 2024-04-02 11:14

from django.apps import apps as registry
from django.db import migrations
from django.db.models.signals import post_migrate

from ..migrations.tasks.saleor3_14 import update_checkout_addresses_task


def update_checkout_addresses(apps, schema_editor):
    def on_migrations_complete(sender=None, **kwargs):
        update_checkout_addresses_task.delay()

    sender = registry.get_app_config("checkout")
    post_migrate.connect(on_migrations_complete, weak=False, sender=sender)


class Migration(migrations.Migration):
    dependencies = [
        (
            "checkout",
            "0062_update_checkout_last_transaction_modified_at_and_refundable",
        )
    ]

    operations = [
        migrations.RunPython(update_checkout_addresses, migrations.RunPython.noop),
    ]
