# Generated by Django 3.2.25 on 2024-04-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0063_auto_20240402_1114"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkout",
            name="is_voucher_usage_increased",
            field=models.BooleanField(default=False),
        ),
        migrations.RunSQL(
            """
                ALTER TABLE checkout_checkout
                ALTER COLUMN is_voucher_usage_increased
                SET DEFAULT false;
            """,
            migrations.RunSQL.noop,
        ),
    ]
