# Generated by Django 3.2.23 on 2024-01-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0063_checkout_base_total_and_subtotal"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkoutline",
            name="is_gift",
            field=models.BooleanField(default=False),
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE checkout_checkoutline
            ALTER COLUMN is_gift
            SET DEFAULT false;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
