# Generated by Django 3.2.25 on 2024-04-03 08:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0063_auto_20240402_1114"),
        ("checkout", "0065_checkout_tax_error"),
    ]
    operations = []
