# Generated by Django 4.2.15 on 2024-10-23 11:43
from django.apps import apps as registry
from django.db import migrations
from django.db.models.signals import post_migrate

from .tasks.saleor3_20 import propagate_lines_undiscounted_unit_price_task


def propagate_lines_undiscounted_unit_price(apps, _schema_editor):
    def on_migrations_complete(sender=None, **kwargs):
        propagate_lines_undiscounted_unit_price_task.delay()

    sender = registry.get_app_config("checkout")
    post_migrate.connect(on_migrations_complete, weak=False, sender=sender)


class Migration(migrations.Migration):
    dependencies = [
        ("tax", "0008_auto_20240122_1353"),
        ("product", "0194_auto_20240620_1404"),
        ("checkout", "0070_checkoutline_undiscounted_unit_price_amount"),
    ]

    operations = [
        migrations.RunPython(
            propagate_lines_undiscounted_unit_price,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
