# Generated by Django 4.2.15 on 2024-10-23 11:43
from django.db import migrations


# Migration used to trigger celery task with data propagation, for already released
# versions.It is only for keeping a consistency, as all data was propagated in 0071
# directly during a migration.
class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0071_propagate_line_unidscounted_unit_price"),
    ]

    operations = []
