# Generated by Django 4.2.15 on 2024-10-23 11:43
from django.apps import apps as registry
from django.db import migrations
from django.db.models.signals import post_migrate

from .tasks.saleor3_19 import propagate_lines_undiscounted_unit_price_task


def propagate_lines_undiscounted_unit_price(apps, _schema_editor):
    def on_migrations_complete(sender=None, **kwargs):
        propagate_lines_undiscounted_unit_price_task.delay()

    sender = registry.get_app_config("checkout")
    post_migrate.connect(on_migrations_complete, weak=False, sender=sender)


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0071_propagate_line_unidscounted_unit_price"),
    ]

    operations = [
        migrations.RunPython(
            propagate_lines_undiscounted_unit_price,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
