# Generated by Django 4.2.20 on 2025-10-24 07:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0075_alter_checkout_base_subtotal_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkout",
            name="discount_expiration",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RunSQL(
            sql=(
                "ALTER TABLE checkout_checkout "
                "ALTER COLUMN discount_expiration SET DEFAULT NOW();"
            ),
            reverse_sql=(
                "ALTER TABLE checkout_checkout "
                "ALTER COLUMN discount_expiration DROP DEFAULT;"
            ),
        ),
    ]
