# Generated by Django 4.2.20 on 2025-05-07 06:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0075_alter_checkout_base_subtotal_amount_and_more"),
        ("checkout", "0077_merge_20250303_0958"),
    ]

    operations = []
