# Generated by Django 5.2.5 on 2025-10-01 10:01

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0080_merge_20250527_1210"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkout",
            name="shipping_methods_stale_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="CheckoutShippingMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "original_id",
                    models.CharField(db_index=True, editable=False, max_length=512),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("price_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(max_length=3)),
                (
                    "maximum_delivery_days",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "minimum_delivery_days",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("metadata", models.JSONField(default=dict)),
                ("private_metadata", models.JSONField(default=dict)),
                ("active", models.BooleanField(default=True)),
                ("message", models.TextField(blank=True, null=True)),
                ("is_external", models.BooleanField(default=False)),
                ("is_valid", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "checkout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping_methods",
                        to="checkout.checkout",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "pk"),
                "unique_together": {("checkout", "original_id")},
            },
        ),
        migrations.AddField(
            model_name="checkout",
            name="assigned_shipping_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="checkout.checkoutshippingmethod",
            ),
        ),
    ]
