# Generated by Django 4.2.26 on 2025-12-22 10:10

from django.apps import apps as registry
from django.db import migrations
from django.db.models.signals import post_migrate

from .tasks.saleor3_21 import fix_shared_address_instances_task


def fix_shared_address_instances(apps, schema_editor):
    def on_migrations_complete(sender=None, **kwargs):
        fix_shared_address_instances_task.delay()

    sender = registry.get_app_config("order")
    post_migrate.connect(on_migrations_complete, weak=False, sender=sender)


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0082_merge_20251211_1339"),
    ]

    operations = [
        migrations.RunPython(fix_shared_address_instances, migrations.RunPython.noop),
    ]
