# Generated by Django 5.2.8 on 2026-01-09 09:55

from django.apps import apps as registry
from django.db import migrations
from django.db.models.signals import post_migrate

from .tasks.saleor3_21 import fix_shared_address_instances_task


def fix_shared_address_instances(apps, schema_editor):
    def on_migrations_complete(sender=None, **kwargs):
        fix_shared_address_instances_task.delay()

    sender = registry.get_app_config("order")
    post_migrate.connect(on_migrations_complete, weak=False, sender=sender)


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0087_merge_20251223_1336"),
    ]

    operations = [
        migrations.RunPython(fix_shared_address_instances),
    ]
