# Generated by Django 5.2.8 on 2026-01-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0089_checkout_search_vector"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkout",
            name="search_index_dirty",
            field=models.BooleanField(db_default=True, default=True),
        ),
    ]
