# Generated by Django 5.2.8 on 2026-01-12 09:16

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("checkout", "0090_checkout_search_index_dirty"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="checkout",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="checkout_tsearch"
            ),
        ),
    ]
