# Generated by Django 5.2.8 on 2026-01-09 09:55

from django.apps import apps as registry
from django.db import migrations
from django.db.models.signals import post_migrate

from .tasks.saleor3_23 import propagate_checkout_deliveries_task


def propagate_checkout_deliveries(apps, schema_editor):
    def on_migrations_complete(sender=None, **kwargs):
        propagate_checkout_deliveries_task.delay()

    sender = registry.get_app_config("checkout")
    post_migrate.connect(on_migrations_complete, weak=False, sender=sender)


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0092_alter_checkoutdelivery_checkout"),
    ]

    operations = [
        migrations.RunPython(propagate_checkout_deliveries, migrations.RunPython.noop),
    ]
