# Generated by Django 5.2.13 on 2026-04-16 06:39

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0093_propagate_checkout_delivery"),
    ]

    RENAME_EXTERNAL_SHIPPING_INDEX = """
    ALTER INDEX IF EXISTS checkout_checkoutdelivery_external_shipping_method_id_55751488
        RENAME TO checkout_delivery_externalid_idx;
    """
    REVERSE_EXTERNAL_SHIPPING_INDEX = """
    ALTER INDEX IF EXISTS checkout_delivery_externalid_idx
        RENAME TO checkout_checkoutdelivery_external_shipping_method_id_55751488;
    """

    RENAME_AUTHORIZE_STATUS_INDEX = """
        ALTER INDEX IF EXISTS checkout_checkout_authorize_status_27351893
            RENAME TO checkout_authorize_status_idx;
    """
    REVERSE_RENAME_AUTHORIZE_STATUS_INDEX = """
        ALTER INDEX IF EXISTS checkout_authorize_status_idx
            RENAME TO checkout_checkout_authorize_status_27351893;
    """

    RENAME_CHARGE_STATUS_INDEX = """
        ALTER INDEX IF EXISTS checkout_checkout_charge_status_bd143b33
            RENAME TO checkout_charge_status_idx;
    """
    REVERSE_RENAME_CHARGE_STATUS_INDEX = """
        ALTER INDEX IF EXISTS checkout_charge_status_idx
            RENAME TO checkout_checkout_charge_status_bd143b33;
    """

    state_operations = [
        migrations.AlterField(
            model_name="checkout",
            name="authorize_status",
            field=models.CharField(
                choices=[
                    ("none", "The checkout is not authorized"),
                    ("partial", "The checkout is partially authorized"),
                    ("full", "The checkout is fully authorized"),
                ],
                default="none",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="checkout",
            name="charge_status",
            field=models.CharField(
                choices=[
                    ("none", "The checkout is not charged"),
                    ("partial", "The checkout is partially charged"),
                    ("full", "The checkout is fully charged"),
                    ("overcharged", "The checkout is overcharged"),
                ],
                default="none",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="checkoutdelivery",
            name="external_shipping_method_id",
            field=models.CharField(
                blank=True, editable=False, max_length=1024, null=True
            ),
        ),
        AddIndexConcurrently(
            model_name="checkoutdelivery",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["external_shipping_method_id"],
                name="checkout_delivery_externalid_idx",
            ),
        ),
        AddIndexConcurrently(
            model_name="checkout",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["charge_status"],
                name="checkout_charge_status_idx",
            ),
        ),
        AddIndexConcurrently(
            model_name="checkout",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["authorize_status"],
                name="checkout_authorize_status_idx",
            ),
        ),
    ]

    db_operations = [
        migrations.RunSQL(
            RENAME_EXTERNAL_SHIPPING_INDEX, reverse_sql=REVERSE_EXTERNAL_SHIPPING_INDEX
        ),
        migrations.RunSQL(
            RENAME_AUTHORIZE_STATUS_INDEX,
            reverse_sql=REVERSE_RENAME_AUTHORIZE_STATUS_INDEX,
        ),
        migrations.RunSQL(
            RENAME_CHARGE_STATUS_INDEX, reverse_sql=REVERSE_RENAME_CHARGE_STATUS_INDEX
        ),
    ]
    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=state_operations, database_operations=db_operations
        )
    ]
