# Generated by Django 5.2.13 on 2026-04-16 06:49

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("checkout", "0094_rename_indexes"),
    ]

    DROP_EXTERNAL_SHPPING_INDEX = """
        DROP INDEX
        CONCURRENTLY IF EXISTS checkout_checkoutdeliver_external_shipping_method_55751488_like;
    """
    REVERSE_DROP_EXTERNAL_SHPPING_INDEX = """
        CREATE INDEX CONCURRENTLY IF NOT EXISTS checkout_checkoutdeliver_external_shipping_method_55751488_like ON checkout_checkoutdelivery (external_shipping_method_id varchar_pattern_ops);
    """
    DROP_AUTHORIZE_STATUS_INDEX = """
        DROP INDEX
        CONCURRENTLY IF EXISTS checkout_checkout_authorize_status_27351893_like;
    """
    REVERSE_DROP_AUTHORIZE_STATUS_INDEX = """
        CREATE INDEX CONCURRENTLY IF NOT EXISTS checkout_checkout_authorize_status_27351893_like ON checkout_checkout (authorize_status varchar_pattern_ops);
    """

    DROP_CHARGE_STATUS_INDEX = """
        DROP INDEX
        CONCURRENTLY IF EXISTS checkout_checkout_charge_status_bd143b33_like;
    """
    REVERSE_DROP_CHARGE_STATUS_INDEX = """
        CREATE INDEX CONCURRENTLY IF NOT EXISTS checkout_checkout_charge_status_bd143b33_like ON checkout_checkout (charge_status varchar_pattern_ops);
    """

    operations = [
        migrations.RunSQL(
            DROP_EXTERNAL_SHPPING_INDEX,
            reverse_sql=REVERSE_DROP_EXTERNAL_SHPPING_INDEX,
        ),
        migrations.RunSQL(
            DROP_AUTHORIZE_STATUS_INDEX,
            reverse_sql=REVERSE_DROP_AUTHORIZE_STATUS_INDEX,
        ),
        migrations.RunSQL(
            DROP_CHARGE_STATUS_INDEX,
            reverse_sql=REVERSE_DROP_CHARGE_STATUS_INDEX,
        ),
    ]
