# Generated by Django 3.1.7 on 2021-05-13 03:02

from django.db import migrations, models
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='city',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='store',
            name='city_area',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='store',
            name='company_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='store',
            name='country',
            field=django_countries.fields.CountryField(default="VN", max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='country_area',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='store',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='street_address_1',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='store',
            name='street_address_2',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
