# Generated by Django 3.1.7 on 2021-04-19 08:12

from django.db import migrations
import saleor.store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='phone',
            field=saleor.store.models.PossiblePhoneNumberField(blank=True, default='', max_length=128, region=None),
        ),
    ]
