# Generated by Django 3.1.7 on 2021-05-07 01:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210506_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
