# Generated by Django 3.1.7 on 2021-05-10 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210510_1346'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Social',
        ),
    ]
