# Generated by Django 3.0.6 on 2020-07-09 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoiceevent", options={"ordering": ("date", "pk")},
        ),
    ]
