# Generated by Django 3.0.6 on 2020-07-13 13:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0002_invoice_message"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoiceevent",
            options={"ordering": ("date", "pk")},
        ),
    ]
