# Generated by Django 3.2.12 on 2022-02-25 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0131_change_pk_to_uuid"),
        ("invoice", "0007_save_invoice_order_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="order_token",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="order.order",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceevent",
            name="order_token",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="order.order",
            ),
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="order",
        ),
        migrations.RemoveField(
            model_name="invoiceevent",
            name="order",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="order_token",
            new_name="order",
        ),
        migrations.RenameField(
            model_name="invoiceevent",
            old_name="order_token",
            new_name="order",
        ),
        migrations.AlterField(
            model_name="invoice",
            name="order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="order.order",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceevent",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoice_events",
                to="order.order",
            ),
        ),
    ]
