# Generated by Django 3.2.18 on 2023-05-29 08:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0008_rewrite_invoice_order_relations"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoice",
            options={"ordering": ("pk",)},
        ),
    ]
