import Card, { CardContent } from "material-ui/Card";
import { withStyles } from "material-ui/styles";
import Typography from "material-ui/Typography";
import * as React from "react";

import TextField from "material-ui/TextField";
import i18n from "../../i18n";
import FormSpacer from "../FormSpacer";
import PageHeader from "../PageHeader";
import Skeleton from "../Skeleton";

interface SeoFormProps {
  title: string;
  titlePlaceholder: string;
  description: string;
  descriptionPlaceholder: string;
  storefrontUrl: string;
  loading?: boolean;
  onClick();
  onChange(event: any);
}

const decorate = withStyles(theme => ({
  titleBar: {
    color: "#1a0dab",
    cursor: "pointer",
    fontSize: "18px",
    lineHeight: "21px",
    textDecoration: "none",
    wordWrap: "break-word" as "break-word",
    overflowWrap: "break-word" as "break-word"
  },
  addressBar: {
    color: "#006621",
    fontSize: "13px",
    lineHeight: "16px",
    whiteSpace: "nowrap" as "nowrap",
    marginBottom: "2px",
    overflow: "hidden" as "hidden",
    textOverflow: "ellipsis" as "ellipsis"
  },
  descriptionBar: {
    color: "#545454",
    fontSize: "13px",
    lineHeight: "18px",
    overflowWrap: "break-word" as "break-word"
  }
}));
const SeoForm = decorate<SeoFormProps>(
  ({
    classes,
    title,
    titlePlaceholder,
    description,
    descriptionPlaceholder,
    storefrontUrl,
    loading,
    onClick,
    onChange
  }) => (
    <Card>
      <PageHeader title={i18n.t("Search Engine Preview")} />
      <CardContent>
        <div>
          {loading ? (
            <Skeleton />
          ) : (
            <>
              <Typography className={classes.titleBar} onClick={onClick}>
                {(title || titlePlaceholder).substr(0, 70)}
              </Typography>
              <Typography className={classes.addressBar}>
                {storefrontUrl}
              </Typography>
              <Typography className={classes.descriptionBar}>
                {(description || descriptionPlaceholder).substr(0, 300)}
              </Typography>
            </>
          )}
        </div>
        <FormSpacer />
        <TextField
          name="seoTitle"
          label={i18n.t("Search engine title")}
          helperText={i18n.t(
            "If empty, the preview shows what will be autogenerated."
          )}
          value={title.slice(0, 70)}
          onChange={onChange}
          fullWidth
        />
        <FormSpacer />
        <TextField
          name="seoDescription"
          label={i18n.t("Search engine title")}
          helperText={i18n.t(
            "If empty, the preview shows what will be autogenerated."
          )}
          value={description.slice(0, 300)}
          onChange={onChange}
          fullWidth
        />
      </CardContent>
    </Card>
  )
);
export default SeoForm;
