# Generated by Django 2.0.3 on 2018-04-05 16:41
from itertools import chain

from django.db import migrations
from ...core.utils import random_data


def generate_pages(*_):
    for msg in chain(random_data.create_privacy_page(),
                     random_data.create_selling_contract_page()):
        print(msg)


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20180321_0417'),
    ]

    operations = [
        migrations.RunPython(generate_pages)
    ]
