# Generated by Django 2.2.3 on 2019-07-15 07:51

from django.db import migrations
from html_to_draftjs import html_to_draftjs


def convert_pages_html_to_json(apps, schema_editor):
    Page = apps.get_model("page", "Page")
    qs = Page.objects.filter(content_json={})

    for page in qs:
        page.content_json = html_to_draftjs(page.content)
        page.save(update_fields=["content_json"])

    PageTranslation = apps.get_model("page", "PageTranslation")
    qs = PageTranslation.objects.filter(content_json={})

    for translation in qs:
        translation.content_json = html_to_draftjs(translation.content)
        translation.save(update_fields=["content_json"])


class Migration(migrations.Migration):

    dependencies = [("page", "0007_auto_20190225_0252")]

    operations = [
        migrations.RunPython(convert_pages_html_to_json),
        migrations.RemoveField(model_name="page", name="content"),
        migrations.RemoveField(model_name="pagetranslation", name="content"),
    ]
