# Generated by Django 2.2.3 on 2019-07-15 07:51
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("page", "0007_auto_20190225_0252")]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="content_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="pagetranslation",
            name="content_json",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
