# Generated by Django 3.1.7 on 2021-04-29 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210419_1512'),
        ('page', '0022_pagemedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='store.store'),
        ),
    ]
