# Generated by Django 4.0.8 on 2022-10-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0026_alter_page_publication_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
