# Generated by Django 5.2.5 on 2025-09-18 08:47

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("page", "0031_alter_page_metadata_alter_page_private_metadata_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="search_index_dirty",
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name="page",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                blank=True, null=True
            ),
        ),
    ]
