# Generated by Django 5.2.5 on 2025-10-08 11:14

from django.contrib.postgres.indexes import BTreeIndex
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("page", "0034_remove_page_page_page_title_964714_gin"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="page",
            index=BTreeIndex(fields=["slug"], name="page_slug_btree_idx"),
        ),
    ]
