# Generated by Django 3.1.3 on 2020-11-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attribute", "0003_auto_20201113_1149"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attribute",
            name="available_in_grid",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="attribute",
            name="filterable_in_dashboard",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="attribute",
            name="filterable_in_storefront",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
