# Generated by Django 3.1.3 on 2020-12-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attribute", "0003_auto_20201113_1149"),
    ]

    operations = [
        migrations.AddField(
            model_name="attribute",
            name="entity_type",
            field=models.CharField(
                blank=True, choices=[("page", "Page")], max_length=50
            ),
        ),
    ]
