# Generated by Django 3.1.3 on 2020-12-09 10:30

import django.db.models.deletion
from django.db import migrations, models


def create_through_relations(apps, schema_editor):
    AssignedProductAttribute = apps.get_model("attribute", "AssignedProductAttribute")
    AssignedProductAttributeValue = apps.get_model(
        "attribute", "AssignedProductAttributeValue"
    )
    instances = []
    for assignment in AssignedProductAttribute.objects.all():
        for value in assignment.values.all():
            instances.append(
                AssignedProductAttributeValue(value=value, assignment=assignment,)
            )
    AssignedProductAttributeValue.objects.bulk_create(instances)


class Migration(migrations.Migration):

    dependencies = [
        ("attribute", "0004_auto_20201204_1325"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignedProductAttributeValue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(db_index=True, editable=False, null=True),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productvalueassignment",
                        to="attribute.assignedproductattribute",
                    ),
                ),
                (
                    "value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productvalueassignment",
                        to="attribute.attributevalue",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "pk"),
                "unique_together": {("value", "assignment")},
            },
        ),
        migrations.RunPython(
            create_through_relations, reverse_code=migrations.RunPython.noop
        ),
        migrations.RemoveField(model_name="assignedproductattribute", name="values",),
        migrations.AddField(
            model_name="assignedproductattribute",
            name="values",
            field=models.ManyToManyField(
                blank=True,
                related_name="assignment",
                through="attribute.AssignedProductAttributeValue",
                to="attribute.AttributeValue",
            ),
        ),
    ]
