# Generated by Django 3.1.3 on 2021-01-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attribute", "0005_add_assignedattributevalues"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attribute",
            name="entity_type",
            field=models.CharField(
                blank=True,
                choices=[("Page", "Page"), ("Product", "Product")],
                max_length=50,
                null=True,
            ),
        ),
    ]
