# Generated by Django 3.1.4 on 2021-01-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attribute", "0006_auto_20210105_1031"),
    ]

    operations = [
        migrations.AddField(
            model_name="attributevalue",
            name="height",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="attributevalue",
            name="length",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="attributevalue",
            name="unit",
            field=models.CharField(
                blank=True,
                choices=[("cm", "cm"), ("m", "m"), ("ft", "ft"), ("inch", "inch")],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="attributevalue",
            name="width",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="attribute",
            name="input_type",
            field=models.CharField(
                choices=[
                    ("dropdown", "Dropdown"),
                    ("multiselect", "Multi Select"),
                    ("file", "File"),
                    ("reference", "Reference"),
                    ("dimensions", "Dimensions"),
                ],
                default="dropdown",
                max_length=50,
            ),
        ),
    ]
