# Generated by Django 3.1.7 on 2021-03-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attribute", "0007_auto_20210308_1135"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attribute",
            name="input_type",
            field=models.CharField(
                choices=[
                    ("dropdown", "Dropdown"),
                    ("multiselect", "Multi Select"),
                    ("file", "File"),
                    ("reference", "Reference"),
                    ("text", "Text"),
                ],
                default="dropdown",
                max_length=50,
            ),
        ),
    ]
