# Generated by Django 3.1.5 on 2021-01-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attribute", "0008_attribute_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attribute",
            name="input_type",
            field=models.CharField(
                choices=[
                    ("dropdown", "Dropdown"),
                    ("multiselect", "Multi Select"),
                    ("file", "File"),
                    ("reference", "Reference"),
                    ("numeric", "Numeric"),
                    ("swatch", "Swatch"),
                ],
                default="dropdown",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="attributevalue",
            name="value",
            field=models.CharField(blank=True, default="", max_length=9),
        ),
    ]
