# Generated by Django 3.1.8 on 2021-04-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attribute", "0010_auto_20210412_0736"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attribute",
            name="input_type",
            field=models.CharField(
                choices=[
                    ("dropdown", "Dropdown"),
                    ("multiselect", "Multi Select"),
                    ("file", "File"),
                    ("reference", "Reference"),
                    ("numeric", "Numeric"),
                    ("rich-text", "Rich Text"),
                    ("swatch", "Swatch"),
                ],
                default="dropdown",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="attributevalue",
            name="value",
            field=models.CharField(blank=True, default="", max_length=9),
        ),
    ]
