# Generated by Django 3.2.2 on 2021-06-08 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attribute", "0011_attributevalue_attribute_a_name_9f3448_gin"),
        ("attribute", "0011_update_values_file_urls"),
    ]

    operations = []
