# Generated by Django 3.1.8 on 2021-06-09 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attribute", "0012_merge_20210608_1034"),
    ]

    operations = [
        migrations.AddField(
            model_name="attributevalue",
            name="boolean",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="attribute",
            name="input_type",
            field=models.CharField(
                choices=[
                    ("dropdown", "Dropdown"),
                    ("multiselect", "Multi Select"),
                    ("file", "File"),
                    ("reference", "Reference"),
                    ("numeric", "Numeric"),
                    ("rich-text", "Rich Text"),
                    ("boolean", "Boolean"),
                ],
                default="dropdown",
                max_length=50,
            ),
        ),
    ]
