# Generated by Django 3.2.6 on 2021-08-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attribute", "0014_auto_20210619_1836"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attributetranslation",
            name="language_code",
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name="attributevaluetranslation",
            name="language_code",
            field=models.CharField(max_length=35),
        ),
    ]
