# Generated by Django 3.2.7 on 2021-09-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attribute", "0017_auto_20210811_0701"),
    ]

    operations = [
        migrations.AddField(
            model_name="attributevariant",
            name="variant_selection",
            field=models.BooleanField(default=False),
        ),
    ]
