# Generated by Django 3.2.13 on 2022-05-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attribute", "0021_auto_20220406_1713"),
    ]

    operations = [
        migrations.AddField(
            model_name="attributevalue",
            name="plain_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attributevaluetranslation",
            name="plain_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
