# Generated by Django 3.2.14 on 2022-08-24 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0175_alter_productmedia_product"),
        ("attribute", "0022_plain_text_attribute"),
    ]

    operations = [
        migrations.AddField(
            model_name="attributevalue",
            name="reference_variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="references",
                to="product.productvariant",
            ),
        ),
        migrations.AlterField(
            model_name="attribute",
            name="entity_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Page", "Page"),
                    ("Product", "Product"),
                    ("ProductVariant", "Product Variant"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
