# Generated by Django 3.2.16 on 2022-10-18 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attribute", "0023_extend_reference_attr_with_variant"),
        ("attribute", "0023_lstrip_slash_from_value_file_url"),
    ]

    operations = []
