# Generated by Django 3.2.16 on 2022-10-18 11:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("attribute", "0022_attribute_value_translations_propagate_names"),
        ("attribute", "0023_lstrip_slash_from_value_file_url"),
    ]

    operations = []
