# Generated by Django 3.2.16 on 2023-01-18 14:56

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("attribute", "0027_auto_20221205_1650"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="attribute",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["slug", "name", "type", "input_type", "entity_type", "unit"],
                name="attribute_gin",
                opclasses=[
                    "gin_trgm_ops",
                    "gin_trgm_ops",
                    "gin_trgm_ops",
                    "gin_trgm_ops",
                    "gin_trgm_ops",
                    "gin_trgm_ops",
                ],
            ),
        ),
    ]
