# Generated by Django 3.2.22 on 2023-11-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attribute", "0028_attribute_attribute_gin"),
    ]

    operations = [
        migrations.AddField(
            model_name="attribute",
            name="max_sort_order",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
