# Generated by Django 3.2.22 on 2023-11-02 10:55

from django.db import migrations, models

from django.apps import apps as registry
from django.db.models.signals import post_migrate

from .tasks.saleor3_14 import setup_max_sort_order


def populate_max_sort_order(apps, _schema_editor):
    def on_migrations_complete(sender=None, **kwargs):
        setup_max_sort_order.delay()

    sender = registry.get_app_config("attribute")
    post_migrate.connect(on_migrations_complete, weak=False, sender=sender)


class Migration(migrations.Migration):
    dependencies = [
        ("attribute", "0028_attribute_attribute_gin"),
    ]

    operations = [
        migrations.AddField(
            model_name="attribute",
            name="max_sort_order",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.RunPython(
            populate_max_sort_order,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
