# Generated by Django 3.2.22 on 2023-11-10 12:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("attribute", "0029_alter_attribute_unit"),
        ("attribute", "0029_attribute_max_sort_order"),
    ]

    operations = []
