# Generated by Django 3.2.20 on 2023-08-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attribute", "0029_alter_attribute_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attribute",
            name="name",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="attribute",
            name="slug",
            field=models.SlugField(allow_unicode=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="attributetranslation",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="attributevalue",
            name="value",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="attributevaluetranslation",
            name="name",
            field=models.CharField(max_length=250),
        ),
    ]
