# Generated by Django 3.2.20 on 2023-08-24 11:25

from django.db import migrations, models
import django.db.models.deletion
from django.contrib.postgres.operations import AddIndexConcurrently
from django.contrib.postgres.indexes import BTreeIndex


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("page", "0028_add_default_page_type"),
        ("attribute", "0031_extend_attributr_value_fields_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignedpageattributevalue",
            name="page",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attributevalues",
                to="page.page",
                db_index=False,
            ),
        ),
        AddIndexConcurrently(
            model_name="assignedpageattributevalue",
            index=BTreeIndex(fields=["page"], name="assignedpageattrvalue_page_idx"),
        ),
    ]
