# Generated by Django 3.2.20 on 2023-08-24 11:25

from django.contrib.postgres.indexes import BTreeIndex
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("page", "0028_add_default_page_type"),
        ("attribute", "0032_assignedpageattributevalue_page_add_field"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="assignedpageattributevalue",
            index=BTreeIndex(fields=["page"], name="assignedpageattrvalue_page_idx"),
        ),
    ]
