# Generated by Django 3.2.20 on 2023-08-24 11:25

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("attribute", "0034_assignedpageattributevalue_page_data_migration"),
    ]

    operations = [
        migrations.RunSQL(
            """
                CREATE INDEX CONCURRENTLY "assignedproductattrvalue_product_idx"
                ON assignedproductattributevalue("product") using btree;
            """
        )
    ]
