# Generated by Django 3.2.20 on 2023-08-24 11:25

from django.db import migrations
from django.db.models.signals import post_migrate
from django.apps import apps as registry

from .tasks.saleor3_16 import assign_products_to_attribute_values_task


def data_migration(apps, _schema_editor):
    def on_migrations_complete(sender=None, **kwargs):
        assign_products_to_attribute_values_task.delay()

    sender = registry.get_app_config("attribute")
    post_migrate.connect(on_migrations_complete, weak=False, sender=sender)


class Migration(migrations.Migration):
    dependencies = [
        ("attribute", "0035_assignedproductattributevalue_product_add_index"),
    ]

    operations = [
        migrations.RunPython(data_migration, migrations.RunPython.noop),
    ]
