# Generated by Django 3.2.22 on 2023-11-13 10:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("attribute", "0030_merge_20231110_1243"),
        ("attribute", "0036_assignedproductattributevalue_product_data_migration"),
    ]

    operations = []
