# Generated by Django 3.2.23 on 2024-02-09 08:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("attribute", "0039_merge_20231113_1132"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    """
                    ALTER TABLE attribute_assignedproductattributevalue
                    DROP COLUMN assignment_id;

                    ALTER TABLE attribute_assignedproductattributevalue
                    ALTER COLUMN product_id SET NOT NULL;

                    DROP TABLE attribute_assignedproductattribute;
                    """,
                    reverse_sql="""
                    ALTER TABLE attribute_assignedproductattributevalue
                    ADD COLUMN assignment_id int;

                    ALTER TABLE attribute_assignedproductattributevalue
                    ALTER COLUMN product_id DROP NOT NULL;

                    CREATE TABLE attribute_assignedproductattribute (
                        id serial NOT NULL PRIMARY KEY,
                        assignment_id integer,
                        product_id integer
                    );
                    """,
                ),
                migrations.RunSQL(
                    """
                    ALTER TABLE attribute_assignedpageattributevalue
                    DROP COLUMN assignment_id;

                    ALTER TABLE attribute_assignedpageattributevalue
                    ALTER COLUMN page_id SET NOT NULL;

                    DROP TABLE attribute_assignedpageattribute;
                    """,
                    reverse_sql="""
                    ALTER TABLE attribute_assignedpageattributevalue
                    ADD COLUMN assignment_id int;

                    ALTER TABLE attribute_assignedpageattributevalue
                    ALTER COLUMN page_id DROP NOT NULL;

                    CREATE TABLE attribute_assignedpageattribute (
                        id serial NOT NULL PRIMARY KEY,
                        assignment_id integer,
                        page_id integer
                    );
                    """,
                ),
            ],
        ),
    ]
