# Generated by Django 3.2.22 on 2024-06-06 14:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("attribute", "0040_clear_assignedattributes"),
        ("attribute", "0042_propagate_temporary_field"),
    ]

    operations = []
