# Generated by Django 4.2.18 on 2025-02-13 14:14

from django.db import migrations, models
import django.db.models.deletion
from django.db.models.signals import post_migrate
from django.apps import apps as registry

from .tasks.saleor3_20 import assign_product_variants_to_attribute_values_task


def enqueue_data_migration(apps, _schema_editor):
    def on_migrations_complete(sender=None, **kwargs):
        assign_product_variants_to_attribute_values_task.delay()

    sender = registry.get_app_config("attribute")
    post_migrate.connect(on_migrations_complete, weak=False, sender=sender)


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0197_productvariantchannellisting_prior_price_amount"),
        ("attribute", "0046_auto_20240611_1143"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignedvariantattributevalue",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attributevalues",
                to="product.productvariant",
            ),
        ),
        migrations.RunPython(enqueue_data_migration, migrations.RunPython.noop),
    ]
