# Generated by Django 5.2.1 on 2025-06-28 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0095_repopulate_user_number_of_orders"),
        ("attribute", "0048_alter_attribute_metadata_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attribute",
            name="type",
            field=models.CharField(
                choices=[
                    ("product-type", "Product type"),
                    ("page-type", "Page type"),
                    ("user-type", "User type"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="AssignedUserAttributeValue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(db_index=True, editable=False, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributevalues",
                        to="account.user",
                    ),
                ),
                (
                    "value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uservalueassignment",
                        to="attribute.attributevalue",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "pk"),
                "unique_together": {("value", "user")},
            },
        ),
    ]
