# Generated by Django 5.2.1 on 2025-07-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attribute", "0049_attributevalue_references_attr_entity_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attribute",
            name="input_type",
            field=models.CharField(
                choices=[
                    ("dropdown", "Dropdown"),
                    ("multiselect", "Multi Select"),
                    ("file", "File"),
                    ("reference", "Reference"),
                    ("single-reference", "Single Reference"),
                    ("numeric", "Numeric"),
                    ("rich-text", "Rich Text"),
                    ("plain-text", "Plain Text"),
                    ("swatch", "Swatch"),
                    ("boolean", "Boolean"),
                    ("date", "Date"),
                    ("date-time", "Date Time"),
                ],
                default="dropdown",
                max_length=50,
            ),
        ),
    ]
