# Generated by Django 4.2.18 on 2025-02-13 14:14

import django.db.models.deletion
from django.db import migrations, models


def enqueue_data_migration(apps, _schema_editor):
    # Placeholder: Data migration task failed due to lock issues.
    # Needs to be called again.
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0197_productvariantchannellisting_prior_price_amount"),
        ("attribute", "0054_attribute_reference_page_and_product_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignedvariantattributevalue",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attributevalues",
                to="product.productvariant",
            ),
        ),
        migrations.RunPython(enqueue_data_migration, migrations.RunPython.noop),
    ]
