# Generated by Django 4.2.18 on 2025-02-13 14:14

import django.db.models.deletion
from django.db import connection, migrations, models, transaction

BATCH_SIZE = 500


def update_product_variant_assignment():
    """Assign variant_id to a new field on assignedproductattributevalue.

    Take the values from attribute_assignedvariantattribute to variant_id and copy it over
    to attribute_assignedvariantattributevalue variant_id.
    """
    with transaction.atomic():
        with connection.cursor() as cursor:
            cursor.execute(
                """
                UPDATE attribute_assignedvariantattributevalue
                SET variant_id = (
                    SELECT variant_id
                    FROM attribute_assignedvariantattribute
                    WHERE attribute_assignedvariantattributevalue.assignment_id = attribute_assignedvariantattribute.id
                )
                WHERE id IN (
                    SELECT ID FROM attribute_assignedvariantattributevalue
                    WHERE VARIANT_ID IS NULL
                    ORDER BY SORT_ORDER, ID DESC
                    FOR UPDATE
                    LIMIT %s
                );
                """,
                [BATCH_SIZE],
            )


def data_migration(apps, _schema_editor):
    AssignedVariantAttributeValue = apps.get_model(
        "attribute", "AssignedVariantAttributeValue"
    )
    while (
        AssignedVariantAttributeValue.objects.filter(variant__isnull=True)
        .values_list("pk", flat=True)
        .exists()
    ):
        update_product_variant_assignment()


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0197_productvariantchannellisting_prior_price_amount"),
        ("attribute", "0054_attribute_reference_page_and_product_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignedvariantattributevalue",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attributevalues",
                to="product.productvariant",
            ),
        ),
        migrations.RunPython(data_migration, migrations.RunPython.noop),
    ]
