# Generated by Django 5.2.5 on 2025-11-04 12:15

from django.apps import apps as registry
from django.db import migrations
from django.db.models.signals import post_migrate

from .tasks.saleor3_22 import assign_product_variants_to_attribute_values_task


def enqueue_data_migration(apps, _schema_editor):
    def on_migrations_complete(sender=None, **kwargs):
        assign_product_variants_to_attribute_values_task.delay()

    sender = registry.get_app_config("attribute")
    post_migrate.connect(on_migrations_complete, weak=False, sender=sender)


class Migration(migrations.Migration):
    dependencies = [
        ("attribute", "0055_assignedvariantattributevalue_variant"),
    ]

    operations = [
        migrations.RunPython(enqueue_data_migration, migrations.RunPython.noop)
    ]
