# Generated by Django 5.2.15 on 2026-07-21 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0101_user_customer_type"),
        ("attribute", "0055_assignedvariantattributevalue_variant"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttributeCustomerType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(db_index=True, editable=False, null=True),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributecustomertype",
                        to="attribute.attribute",
                    ),
                ),
                (
                    "customer_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributecustomertype",
                        to="account.customertype",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "pk"),
                "unique_together": {("attribute", "customer_type")},
            },
        ),
        migrations.AddField(
            model_name="attribute",
            name="customer_types",
            field=models.ManyToManyField(
                blank=True,
                related_name="customer_attributes",
                through="attribute.AttributeCustomerType",
                through_fields=("attribute", "customer_type"),
                to="account.customertype",
            ),
        ),
    ]
