# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('value_type', models.CharField(choices=[(b'i', 'Integer'), (b's', 'String'), (b'b', 'Boolean')], max_length=1, verbose_name='value type')),
                ('value', models.CharField(max_length=256, verbose_name='value')),
            ],
        ),
    ]
