# Generated by Django 3.2.6 on 2021-10-12 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhook", "0007_auto_20210319_0945"),
        ("core", "0002_eventpayload_eventtask"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventDelivery",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        max_length=255,
                    ),
                ),
                ("event_type", models.CharField(max_length=255)),
                (
                    "payload",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deliveries",
                        to="core.eventpayload",
                    ),
                ),
                (
                    "webhook",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="webhook.webhook",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventDeliveryAttempt",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("task_id", models.CharField(max_length=255, null=True)),
                ("duration", models.FloatField(null=True)),
                ("response", models.TextField(null=True)),
                ("headers", models.TextField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "delivery",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attempts",
                        to="core.eventdelivery",
                    ),
                ),
            ],
        ),
    ]
