# Generated by Django 3.2.6 on 2021-10-12 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_eventdelivery_eventdeliveryattempt"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EventTask",
        ),
    ]
