# Generated by Django 3.2.6 on 2021-10-20 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_delete_eventtask"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventdelivery",
            name="payload",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliveries",
                to="core.eventpayload",
            ),
        ),
        migrations.AlterField(
            model_name="eventdelivery",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="eventdeliveryattempt",
            name="delivery",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="core.eventdelivery",
            ),
        ),
        migrations.AlterField(
            model_name="eventdeliveryattempt",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=255,
            ),
        ),
    ]
