# Generated by Django 3.2.12 on 2022-04-08 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webhook", "0008_webhook_subscription_query"),
        ("core", "0004_delete_delivery_without_webhook"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventdelivery",
            name="webhook",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="webhook.webhook"
            ),
        ),
    ]
