# Generated by Django 3.2.6 on 2021-10-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_auto_20211020_1033"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventdeliveryattempt",
            old_name="headers",
            new_name="request_headers",
        ),
        migrations.AddField(
            model_name="eventdeliveryattempt",
            name="response_headers",
            field=models.TextField(null=True),
        ),
    ]
