# Generated by Django 3.2.21 on 2023-09-05 13:09

from django.db import migrations

# Drop tables that were used by packages that are no longer used:
# - `django-prices-vatlayer` - removed in https://github.com/saleor/saleor/pull/13179/


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_add_temporary_vatlayer_tables"),
        ("tax", "0007_auto_20230217_0837"),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS django_prices_vatlayer_ratetypes",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS django_prices_vatlayer_vat;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
