# Generated by Django 5.2.13 on 2026-04-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_eventpayload_payload_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventdelivery",
            name="bypass_app_active_check",
            field=models.BooleanField(default=False),
        ),
    ]
