# Generated by Django 2.2.3 on 2019-07-17 11:26

from django.db import migrations, models
from django.db.models import Max


def set_default_position_menu_item(apps, schema_editor):
    MenuItem = apps.get_model("menu", "MenuItem")

    existing_max = MenuItem.objects.aggregate(Max("sort_order"))
    existing_max = existing_max.get("sort_order__max") or 0

    for sort_order, item in enumerate(
        MenuItem.objects.filter(sort_order=None), existing_max + 1
    ):
        item.sort_order = sort_order
        item.save(update_fields=["sort_order"])


class Migration(migrations.Migration):

    dependencies = [("menu", "0014_auto_20190523_0759")]

    operations = [
        migrations.RunPython(set_default_position_menu_item),
        migrations.AlterField(
            model_name="menuitem",
            name="sort_order",
            field=models.PositiveIntegerField(
                db_index=True, default=0, editable=False, null=False
            ),
        ),
    ]
