# Generated by Django 3.0.6 on 2020-07-09 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0017_remove_menu_json_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menuitem",
            options={"ordering": ("sort_order", "pk")},
        ),
        migrations.AlterModelOptions(
            name="menuitemtranslation",
            options={"ordering": ("language_code", "menu_item", "pk")},
        ),
    ]
