# Generated by Django 3.2.6 on 2021-08-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0021_auto_20210308_1135"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitemtranslation",
            name="language_code",
            field=models.CharField(max_length=35),
        ),
    ]
