# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0005_auto_20170907_0827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'permissions': (('view_sale', 'Can view sales'), ('edit_sale', 'Can edit sales')), 'verbose_name': 'sale', 'verbose_name_plural': 'sales'},
        ),
        migrations.AlterModelOptions(
            name='voucher',
            options={'permissions': (('view_voucher', 'Can view vouchers'), ('edit_voucher', 'Can edit vouchers')), 'verbose_name': 'voucher', 'verbose_name_plural': 'vouchers'},
        ),
    ]
