# Generated by Django 2.1.7 on 2019-03-29 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("discount", "0011_auto_20180803_0528")]

    operations = [
        migrations.CreateModel(
            name="SaleTranslation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language_code", models.CharField(max_length=10)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="discount.Sale",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="saletranslation", unique_together={("language_code", "sale")}
        ),
    ]
