# Generated by Django 2.1.5 on 2019-01-10 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0011_auto_20180803_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='once_per_customer',
            field=models.BooleanField(default=False),
        ),
    ]
