# Generated by Django 2.2.2 on 2019-06-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("discount", "0013_auto_20190618_0733")]

    operations = [
        migrations.AlterField(
            model_name="voucher",
            name="type",
            field=models.CharField(
                choices=[
                    ("entire_order", "Entire order"),
                    ("product", "Specific products"),
                    ("collection", "Specific collections of products"),
                    ("category", "Specific categories of products"),
                    ("shipping", "Shipping"),
                    (
                        "specific_product",
                        "Specific products, collections and categories",
                    ),
                ],
                default="entire_order",
                max_length=20,
            ),
        )
    ]
