# Generated by Django 3.1 on 2020-09-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discount", "0020_auto_20200709_1102"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="value",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="voucher",
            name="discount_value",
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name="voucher",
            name="min_spent_amount",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=12, null=True
            ),
        ),
    ]
