# Generated by Django 3.1 on 2020-09-21 08:26

import django.db.models.deletion
from django.db import migrations, models


def migrate_voucher_data(apps, schema_editor):
    Channel = apps.get_model("channel", "Channel")
    Voucher = apps.get_model("discount", "Voucher")
    VoucherChannelListing = apps.get_model("discount", "VoucherChannelListing")

    if Voucher.objects.exists():
        channels_dict = {}

        for voucher in Voucher.objects.iterator():
            currency = voucher.currency
            channel = channels_dict.get(currency)
            if not channel:
                channel, _ = Channel.objects.get_or_create(
                    currency_code=currency,
                    defaults={
                        "name": f"Channel {currency}",
                        "slug": f"channel-{currency.lower()}",
                    },
                )
                channels_dict[currency] = channel
            VoucherChannelListing.objects.create(
                voucher=voucher,
                channel=channel,
                currency=currency,
                discount_value=voucher.discount_value,
                min_spent_amount=voucher.min_spent_amount,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("channel", "0001_initial"),
        ("discount", "0021_auto_20200902_1249"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoucherChannelListing",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(decimal_places=3, max_digits=12),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "min_spent_amount",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voucher_listing",
                        to="channel.channel",
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_listing",
                        to="discount.voucher",
                    ),
                ),
            ],
            options={"ordering": ("pk",), "unique_together": {("voucher", "channel")}},
        ),
        migrations.RunPython(migrate_voucher_data, migrations.RunPython.noop),
        migrations.RemoveField(model_name="voucher", name="currency",),
        migrations.RemoveField(model_name="voucher", name="discount_value",),
        migrations.RemoveField(model_name="voucher", name="min_spent_amount",),
    ]
