# Generated by Django 3.1.1 on 2020-10-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discount", "0023_voucherchannellisting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voucherchannellisting",
            name="currency",
            field=models.CharField(max_length=3),
        ),
    ]
