# Generated by Django 3.1.2 on 2020-11-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discount", "0023_voucher_channel_listing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="type",
            field=models.CharField(
                choices=[("fixed", "fixed"), ("percentage", "%")],
                default="fixed",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="voucher",
            name="discount_value_type",
            field=models.CharField(
                choices=[("fixed", "fixed"), ("percentage", "%")],
                default="fixed",
                max_length=10,
            ),
        ),
    ]
