# Generated by Django 3.1 on 2020-11-04 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    # TODO squash before merging multicurrency into master
    dependencies = [
        ("channel", "0003_auto_20201015_1107"),
        ("discount", "0026_auto_20201104_0844"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voucherchannellisting",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="voucher_listings",
                to="channel.channel",
            ),
        ),
        migrations.AlterField(
            model_name="voucherchannellisting",
            name="voucher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channel_listings",
                to="discount.voucher",
            ),
        ),
    ]
