# Generated by Django 3.2.5 on 2021-07-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discount", "0027_auto_20210719_2155"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voucher",
            name="code",
            field=models.CharField(db_index=True, max_length=16, unique=True),
        ),
    ]
