# Generated by Django 3.2.6 on 2021-08-20 09:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0028_alter_voucher_code"),
        ("discount", "0028_auto_20210817_1015"),
    ]

    operations = []
