# Generated by Django 3.2.6 on 2021-09-09 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discount", "0030_sale_variants"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sale",
            name="products",
        ),
    ]
