# Generated by Django 3.2.6 on 2021-09-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0148_producttype_type"),
        ("discount", "0030_sale_variants"),
    ]

    operations = [
        migrations.AddField(
            model_name="voucher",
            name="variants",
            field=models.ManyToManyField(blank=True, to="product.ProductVariant"),
        ),
    ]
