# Generated by Django 3.2.6 on 2021-11-09 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discount", "0031_merge_0029_alter_voucher_code_0030_discount_variants"),
        ("discount", "0031_merge_20211020_1019"),
    ]

    operations = []
