# Generated by Django 3.2.12 on 2022-02-09 15:43

from django.db import migrations
from django.utils import timezone


def populate_sales_datetimes(apps, _schema_editor):
    timestamp = timezone.now()

    Sale = apps.get_model("discount", "Sale")
    Sale.objects.update(created=timestamp, updated_at=timestamp)


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0033_auto_20220209_1543"),
    ]

    operations = [
        migrations.RunPython(
            populate_sales_datetimes,
            migrations.RunPython.noop,
        ),
    ]
