# Generated by Django 3.2.12 on 2022-02-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0034_populate_sales_datetimes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="sale",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
