# Generated by Django 3.2.12 on 2022-03-24 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discount", "0035_auto_20220209_1544"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderdiscount",
            options={"ordering": ("pk",)},
        ),
    ]
