# Generated by Django 3.2.13 on 2022-07-08 06:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0042_migrate_orderdiscount_id_to_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="notification_sent_datetime",
            # The notification date is set to the current date, as the Celery would
            # trigger the tasks right after the deployment and we would send
            # events that no one listens to. So we will receive the same result with
            # setting the current date and not sending the events at first place.
            field=models.DateTimeField(
                null=True, blank=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
