# Generated by Django 3.2.13 on 2022-07-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discount", "0042_migrate_orderdiscount_id_to_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="notification_sent_datetime",
            field=models.DateTimeField(null=True, blank=True),
        ),
    ]
