# Generated by Django 3.2.13 on 2022-05-02 11:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("discount", "0042_alter_orderdiscount_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderdiscount",
            options={"ordering": ("created_at",)},
        ),
        migrations.RemoveField(
            model_name="orderdiscount",
            name="id",
        ),
        migrations.AlterField(
            model_name="orderdiscount",
            name="token",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.RenameField(
            model_name="orderdiscount",
            old_name="token",
            new_name="id",
        ),
    ]
