# Generated by Django 3.2.18 on 2023-04-21 10:18

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0059_merge_0058"),
        ("discount", "0043_sale_notification_sent_datetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderdiscount",
            name="sale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="discount.sale",
            ),
        ),
        migrations.AddField(
            model_name="orderdiscount",
            name="voucher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="discount.voucher",
            ),
        ),
        migrations.AlterField(
            model_name="orderdiscount",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="orderdiscount",
            name="type",
            field=models.CharField(
                choices=[
                    ("sale", "Sale"),
                    ("voucher", "Voucher"),
                    ("manual", "Manual"),
                ],
                default="manual",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="CheckoutLineDiscount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("sale", "Sale"),
                            ("voucher", "Voucher"),
                            ("manual", "Manual"),
                        ],
                        default="manual",
                        max_length=10,
                    ),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[("fixed", "fixed"), ("percentage", "%")],
                        default="fixed",
                        max_length=10,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.0"), max_digits=12
                    ),
                ),
                (
                    "amount_value",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.0"), max_digits=12
                    ),
                ),
                ("currency", models.CharField(max_length=3)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "translated_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                (
                    "line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discounts",
                        to="checkout.checkoutline",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="discount.sale",
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="discount.voucher",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
    ]
