# Generated by Django 3.2.19 on 2023-06-26 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0045_promotion_promotionrule"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkoutlinediscount",
            name="promotion_rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="discount.promotionrule",
            ),
        ),
        migrations.AddField(
            model_name="orderdiscount",
            name="promotion_rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="discount.promotionrule",
            ),
        ),
        migrations.AlterField(
            model_name="checkoutlinediscount",
            name="type",
            field=models.CharField(
                choices=[
                    ("sale", "Sale"),
                    ("voucher", "Voucher"),
                    ("manual", "Manual"),
                    ("promotion", "Promotion"),
                ],
                default="manual",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="orderdiscount",
            name="type",
            field=models.CharField(
                choices=[
                    ("sale", "Sale"),
                    ("voucher", "Voucher"),
                    ("manual", "Manual"),
                    ("promotion", "Promotion"),
                ],
                default="manual",
                max_length=10,
            ),
        ),
    ]
