# Generated by Django 3.2.20 on 2023-08-21 07:23

from django.db import migrations


def move_codes_to_new_model(apps, schema_editor):
    Voucher = apps.get_model("discount", "Voucher")
    VoucherCode = apps.get_model("discount", "VoucherCode")

    voucher_codes = []
    for voucher in Voucher.objects.values("id", "code", "used", "usage_limit"):
        voucher_codes.append(
            VoucherCode(
                voucher_id=voucher["id"],
                code=voucher["code"],
                used=voucher["used"],
                usage_limit=voucher["usage_limit"],
            )
        )

    VoucherCode.objects.bulk_create(voucher_codes)


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0045_vouchercode"),
    ]

    operations = [
        migrations.RunPython(
            move_codes_to_new_model,
            migrations.RunPython.noop,
        ),
    ]
