# Generated by Django 3.2.20 on 2023-09-04 08:36

from django.apps import apps as registry
from django.db import migrations
from django.db.models.signals import post_migrate

from .tasks.saleor3_16 import migrate_sales_to_promotions_task


def migrate_sales_to_promotions(apps, _schema_editor):
    def on_migrations_complete(sender=None, **kwargs):
        migrate_sales_to_promotions_task.delay()

    sender = registry.get_app_config("order")
    post_migrate.connect(on_migrations_complete, weak=False, sender=sender)


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0045_promotions"),
    ]

    operations = [
        migrations.RunPython(
            migrate_sales_to_promotions,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
