# Generated by Django 3.2.19 on 2023-06-15 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0045_promotion_promotionrule"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkoutlinediscount",
            name="promotion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="discount.promotion",
            ),
        ),
        migrations.AddField(
            model_name="orderdiscount",
            name="promotion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="discount.promotion",
            ),
        ),
    ]
