# Generated by Django 3.2.21 on 2023-10-03 09:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0047_migrate_sales_to_promotions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="promotion",
            options={
                "ordering": ("name", "pk"),
                "permissions": (
                    ("manage_discounts", "Manage promotions and vouchers."),
                ),
            },
        ),
    ]
