# Generated by Django 3.2.19 on 2023-07-04 13:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0047_auto_20230703_2018"),
    ]

    operations = [
        migrations.RenameField(
            model_name="promotionevent",
            old_name="promotion",
            new_name="parent",
        ),
    ]
