# Generated by Django 3.2.21 on 2023-10-04 13:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0047_migrate_sales_to_promotions"),
    ]

    operations = [
        # Empty migration for consistency with Saleor 3.16.
        # The migration was fixing the issue introduced in 3.16.5.
    ]
