# Generated by Django 3.2.21 on 2023-10-04 13:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0048_remigrate_sales_to_promotions"),
        ("discount", "0049_promotionevent"),
    ]

    operations = []
