# Generated by Django 3.2.20 on 2023-08-03 11:45

from django.db import migrations, models
import saleor.discount.models


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0049_migrate_sales_to_promotions"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                """
            CREATE SEQUENCE discount_promotion_old_sale_id_seq
            OWNED BY discount_promotion.old_sale_id;

            SELECT setval(
                'discount_promotion_old_sale_id_seq',
                 coalesce(max(old_sale_id), 0) + 1, false
            )
            FROM discount_promotion;
            """
            ],
            reverse_sql=["DROP SEQUENCE discount_promotion_old_sale_id_seq"],
        ),
        migrations.AlterField(
            model_name="promotion",
            name="old_sale_id",
            field=models.IntegerField(
                blank=True,
                default=saleor.discount.models.get_old_sale_id,
                null=True,
                unique=True,
            ),
        ),
    ]
