# Generated by Django 3.2.20 on 2023-08-21 07:21
from uuid import uuid4
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0050_merge_20231004_1306"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoucherCode",
            options={"ordering": ("code",)},
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=255, unique=True)),
                ("used", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "voucher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codes",
                        to="discount.voucher",
                        db_index=False,
                    ),
                ),
            ],
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE discount_vouchercode
                ALTER COLUMN is_active
                SET DEFAULT true;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
