# Generated by Django 3.2.21 on 2023-09-26 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0050_set_vouchercustomer_codes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vouchercustomer",
            name="voucher_code",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customers",
                to="discount.vouchercode",
            ),
        ),
        migrations.AlterModelOptions(
            name="vouchercustomer",
            options={"ordering": ("voucher_code", "customer_email", "pk")},
        ),
        migrations.AlterUniqueTogether(
            name="vouchercustomer",
            unique_together={("voucher_code", "customer_email")},
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AlterField(
                    model_name="vouchercustomer",
                    name="voucher",
                    field=models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customers",
                        to="discount.voucher",
                    ),
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name="vouchercustomer",
                    name="voucher",
                ),
            ],
        ),
    ]
