# Generated by Django 3.2.20 on 2023-08-21 07:23

from django.db import migrations
from .tasks.saleor3_17 import move_codes_to_voucher_code_task
from django.db.models.signals import post_migrate
from django.apps import apps as registry

BATCH_SIZE = 5000


def move_codes_to_new_model(apps, schema_editor):
    def on_migrations_complete(sender=None, **kwargs):
        move_codes_to_voucher_code_task.delay()

    sender = registry.get_app_config("attribute")
    post_migrate.connect(on_migrations_complete, weak=False, sender=sender)


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0051_voucher_code_indexes"),
    ]

    operations = [
        migrations.RunPython(
            move_codes_to_new_model,
            migrations.RunPython.noop,
        ),
    ]
