# Generated by Django 3.2.21 on 2023-10-05 10:44

from django.db import migrations
from .tasks.saleor3_17 import set_voucher_customer_codes_task
from django.apps import apps as registry
from django.db.models.signals import post_migrate


def set_voucher_code_to_voucher_customer(apps, schema_editor):
    def on_migrations_complete(sender=None, **kwargs):
        set_voucher_customer_codes_task.delay()

    sender = registry.get_app_config("discount")
    post_migrate.connect(on_migrations_complete, weak=False, sender=sender)


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0054_vouchercustomer_voucher_code_index"),
    ]

    operations = [
        migrations.RunPython(
            set_voucher_code_to_voucher_customer,
            migrations.RunPython.noop,
        ),
    ]
