# Generated by Django 3.2.22 on 2023-10-20 13:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0055_drop_sales_from_db"),
        ("discount", "0063_basediscount_voucher_code"),
    ]

    operations = []
