# Generated by Django 3.2.23 on 2023-11-17 08:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0064_alter_promotionrule_catalogue_predicate"),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                """
       ALTER TABLE discount_vouchercode
       ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
                """
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
