# Generated by Django 3.2.23 on 2023-12-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0189_merge_20230929_0857"),
        ("discount", "0065_vouchercode_created_at_check"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotionrule",
            name="variants",
            field=models.ManyToManyField(blank=True, to="product.ProductVariant"),
        ),
    ]
