# Generated by Django 3.2.21 on 2023-09-26 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0065_remove_voucher_code_index"),
    ]

    operations = [
        # Voucher
        migrations.AlterModelOptions(
            name="voucher",
            options={"ordering": ("name", "pk")},
        ),
        # VoucherCustomer
        migrations.AlterField(
            model_name="vouchercustomer",
            name="voucher_code",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customers",
                to="discount.vouchercode",
            ),
        ),
        migrations.AlterModelOptions(
            name="vouchercustomer",
            options={"ordering": ("voucher_code", "customer_email", "pk")},
        ),
        migrations.AlterUniqueTogether(
            name="vouchercustomer",
            unique_together={("voucher_code", "customer_email")},
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AlterField(
                    model_name="vouchercustomer",
                    name="voucher",
                    field=models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customers",
                        to="discount.voucher",
                    ),
                ),
                migrations.AlterField(
                    model_name="voucher",
                    name="code",
                    field=models.CharField(null=True, blank=True, max_length=255),
                ),
                migrations.AlterField(
                    model_name="voucher",
                    name="used",
                    field=models.PositiveIntegerField(default=0, null=True, blank=True),
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name="vouchercustomer",
                    name="voucher",
                ),
                migrations.RemoveField(
                    model_name="voucher",
                    name="code",
                ),
                migrations.RemoveField(
                    model_name="voucher",
                    name="used",
                ),
            ],
        ),
    ]
