# Generated by Django 3.2.23 on 2023-12-12 08:35

from django.apps import apps as registry
from django.db import migrations
from django.db.models.signals import post_migrate

from .tasks.saleor3_17 import set_promotion_rule_variants


def update_promotion_rule_variants(apps, _schema_editor):
    def on_migrations_complete(sender=None, **kwargs):
        set_promotion_rule_variants.delay()

    sender = registry.get_app_config("discount")
    post_migrate.connect(on_migrations_complete, weak=False, sender=sender)


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0066_promotionrule_variants"),
    ]

    operations = [
        migrations.RunPython(
            update_promotion_rule_variants,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
