# Generated by Django 3.2.22 on 2023-11-06 10:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0064_alter_promotionrule_catalogue_predicate"),
        ("discount", "0067_voucher_single_use"),
    ]

    operations = []
