# Generated by Django 3.2.24 on 2024-03-07 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0190_merge_20231221_1356"),
        ("discount", "0068_promotion_start_end_date_indexes"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="PromotionRule_Variants",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "productvariant",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="product.productvariant",
                            ),
                        ),
                        (
                            "promotionrule",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="discount.promotionrule",
                            ),
                        ),
                    ],
                ),
                migrations.AlterField(
                    model_name="promotionrule",
                    name="variants",
                    field=models.ManyToManyField(
                        blank=True,
                        through="discount.PromotionRule_Variants",
                        to="product.ProductVariant",
                    ),
                ),
            ]
        ),
    ]
