# Generated by Django 3.2.23 on 2023-11-17 09:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0065_vouchercode_created_at_check"),
        ("discount", "0068_merge_20231106_1013"),
    ]

    operations = []
