# Generated by Django 3.2.22 on 2023-12-15 09:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0068_promotion_start_end_date_indexes"),
        ("discount", "0069_merge_20231117_0959"),
    ]

    operations = []
