# Generated by Django 3.2.23 on 2023-12-15 09:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0070_alter_promotion_options"),
        ("discount", "0070_merge_20231215_0911"),
    ]

    operations = []
