# Generated by Django 3.2.23 on 2024-01-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0071_merge_20240307_1156"),
    ]
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    """
                    ALTER TABLE discount_promotionrule
                    ADD COLUMN IF NOT EXISTS variants_dirty boolean
                    DEFAULT false;
                    """,
                    reverse_sql="""
                    ALTER TABLE discount_promotionrule DROP COLUMN variants_dirty
                    """,
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name="promotionrule",
                    name="variants_dirty",
                    field=models.BooleanField(default=False),
                )
            ],
        ),
    ]
