# Generated by Django 3.2.23 on 2023-12-13 15:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0072_auto_20231213_1413"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE discount_vouchercustomer DROP CONSTRAINT IF EXISTS
                    discount_vouchercust_voucher_id_bb55c04f_fk_discount_;
                ALTER TABLE discount_vouchercustomer
                    DROP COLUMN voucher_id;
                ALTER TABLE discount_voucher DROP COLUMN code;
                ALTER TABLE discount_voucher DROP COLUMN used;
            """,
            reverse_sql="""
                ALTER TABLE discount_vouchercustomer ADD COLUMN voucher_id integer;
                ALTER TABLE discount_vouchercustomer
                    ADD CONSTRAINT discount_vouchercust_voucher_id_bb55c04f_fk_discount_
                    FOREIGN KEY (voucher_id) REFERENCES
                    discount_voucher(id) DEFERRABLE INITIALLY DEFERRED;
                ALTER TABLE discount_voucher ADD COLUMN code varchar(255);
                ALTER TABLE discount_voucher ADD COLUMN used integer DEFAULT 0;
            """,
        )
    ]
