# Generated by Django 3.2.24 on 2024-04-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0072_promotionrule_variants_dirty"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    """
                    ALTER TABLE discount_checkoutlinediscount
                    ADD COLUMN IF NOT EXISTS unique_type varchar(64) NULL;
                    """,
                    reverse_sql="""
                    ALTER TABLE discount_checkoutlinediscount
                    DROP COLUMN IF EXISTS unique_type
                    """,
                ),
                migrations.RunSQL(
                    """
                    ALTER TABLE discount_orderlinediscount
                    ADD COLUMN IF NOT EXISTS unique_type varchar(64) NULL;
                    """,
                    reverse_sql="""
                    ALTER TABLE discount_orderlinediscount
                    DROP COLUMN IF EXISTS unique_type
                    """,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="checkoutlinediscount",
                    name="unique_type",
                    field=models.CharField(
                        blank=True,
                        choices=[
                            ("sale", "Sale"),
                            ("voucher", "Voucher"),
                            ("manual", "Manual"),
                            ("promotion", "Promotion"),
                        ],
                        max_length=64,
                        null=True,
                    ),
                ),
                migrations.AddField(
                    model_name="orderlinediscount",
                    name="unique_type",
                    field=models.CharField(
                        blank=True,
                        choices=[
                            ("sale", "Sale"),
                            ("voucher", "Voucher"),
                            ("manual", "Manual"),
                            ("promotion", "Promotion"),
                        ],
                        max_length=64,
                        null=True,
                    ),
                ),
            ],
        )
    ]
