# Generated by Django 3.2.22 on 2023-11-06 14:59

from django.db import migrations, models

import saleor.core.utils.json_serializer


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0073_auto_20231213_1535"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotionrule",
            name="order_predicate",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=saleor.core.utils.json_serializer.CustomJsonEncoder,
            ),
        ),
        migrations.AddField(
            model_name="promotionrule",
            name="reward_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("subtotal_discount", "subtotal_discount"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.RunSQL(
            "ALTER TABLE discount_promotionrule ALTER COLUMN order_predicate SET DEFAULT '{}';",
            migrations.RunSQL.noop,
        ),
    ]
