# Generated by Django 3.2.22 on 2023-12-29 08:03

import uuid
from decimal import Decimal

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "checkout",
            "0062_update_checkout_last_transaction_modified_at_and_refundable",
        ),
        ("discount", "0075_promotionrule_reward_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckoutDiscount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("sale", "Sale"),
                            ("voucher", "Voucher"),
                            ("manual", "Manual"),
                            ("promotion", "Promotion"),
                        ],
                        default="manual",
                        max_length=10,
                    ),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[("fixed", "fixed"), ("percentage", "%")],
                        default="fixed",
                        max_length=10,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.0"), max_digits=12
                    ),
                ),
                (
                    "amount_value",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.0"), max_digits=12
                    ),
                ),
                ("currency", models.CharField(max_length=3)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "translated_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                (
                    "voucher_code",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "checkout",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discounts",
                        to="checkout.checkout",
                    ),
                ),
                (
                    "promotion_rule",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="discount.promotionrule",
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="discount.voucher",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="checkoutdiscount",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["promotion_rule"], name="checkoutdiscount_rule_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="checkoutdiscount",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name", "translated_name"], name="discount_ch_name_64e096_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="checkoutdiscount",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["voucher_code"], name="checkoutdiscount_voucher_idx"
            ),
        ),
    ]
