# Generated by Django 3.2.23 on 2024-01-09 08:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0075_promotionrule_gifts"),
    ]

    # left to keep a compatible migration. The logic moved to
    # 0072_promotionrule_variants_dirty.py
    operations = []
