# Generated by Django 3.2.23 on 2024-01-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0075_promotionrule_gifts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkoutdiscount",
            name="type",
            field=models.CharField(
                choices=[
                    ("sale", "Sale"),
                    ("voucher", "Voucher"),
                    ("manual", "Manual"),
                    ("promotion", "Promotion"),
                    ("order_promotion", "Order promotion"),
                    ("gift_promotion", "Gift promotion"),
                ],
                default="manual",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="checkoutlinediscount",
            name="type",
            field=models.CharField(
                choices=[
                    ("sale", "Sale"),
                    ("voucher", "Voucher"),
                    ("manual", "Manual"),
                    ("promotion", "Promotion"),
                    ("order_promotion", "Order promotion"),
                    ("gift_promotion", "Gift promotion"),
                ],
                default="manual",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="orderdiscount",
            name="type",
            field=models.CharField(
                choices=[
                    ("sale", "Sale"),
                    ("voucher", "Voucher"),
                    ("manual", "Manual"),
                    ("promotion", "Promotion"),
                    ("order_promotion", "Order promotion"),
                    ("gift_promotion", "Gift promotion"),
                ],
                default="manual",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="orderlinediscount",
            name="type",
            field=models.CharField(
                choices=[
                    ("sale", "Sale"),
                    ("voucher", "Voucher"),
                    ("manual", "Manual"),
                    ("promotion", "Promotion"),
                    ("order_promotion", "Order promotion"),
                    ("gift_promotion", "Gift promotion"),
                ],
                default="manual",
                max_length=64,
            ),
        ),
    ]
