# Generated by Django 3.2.23 on 2024-01-09 14:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0063_checkout_base_total_and_subtotal"),
        ("discount", "0076_update_base_discount_type"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="checkoutdiscount",
            unique_together={("checkout_id", "promotion_rule_id")},
        ),
    ]
