# Generated by Django 3.2.23 on 2024-01-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0076_update_base_discount_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotionrule",
            name="predicate_type",
            field=models.CharField(
                choices=[("catalogue", "Catalogue"), ("order", "Order")],
                max_length=255,
                default="catalogue",
            ),
        ),
        migrations.RunSQL(
            "ALTER TABLE discount_promotionrule ALTER COLUMN predicate_type SET DEFAULT 'catalogue';",
            migrations.RunSQL.noop,
        ),
    ]
