# Generated by Django 3.2.24 on 2024-04-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0077_merge_20240307_1217"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkoutlinediscount",
            name="unique_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sale", "Sale"),
                    ("voucher", "Voucher"),
                    ("manual", "Manual"),
                    ("promotion", "Promotion"),
                    ("order_promotion", "Order promotion"),
                ],
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="orderlinediscount",
            name="unique_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sale", "Sale"),
                    ("voucher", "Voucher"),
                    ("manual", "Manual"),
                    ("promotion", "Promotion"),
                    ("order_promotion", "Order promotion"),
                ],
                max_length=64,
                null=True,
            ),
        ),
    ]
