# Generated by Django 3.2.24 on 2024-03-28 13:17

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("discount", "0077_add_unique_type"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE UNIQUE INDEX CONCURRENTLY checkoutdiscount_checkout_id_unique_type_idx
                ON discount_checkoutdiscount USING btree (checkout_id, unique_type);
            """,
            reverse_sql="""
                DROP INDEX CONCURRENTLY IF EXISTS
                checkoutdiscount_checkout_id_unique_type_idx;
            """,
        ),
        migrations.RunSQL(
            sql="""
                CREATE UNIQUE INDEX CONCURRENTLY checkoutlinediscount_line_id_unique_type_idx
                ON discount_checkoutlinediscount USING btree (line_id, unique_type);
            """,
            reverse_sql="""
                DROP INDEX CONCURRENTLY IF EXISTS
                checkoutlinediscount_line_id_unique_type_idx;
            """,
        ),
        migrations.RunSQL(
            sql="""
                CREATE UNIQUE INDEX CONCURRENTLY orderdiscount_order_id_unique_type_idx
                ON discount_orderdiscount USING btree (order_id, unique_type);
            """,
            reverse_sql="""
                DROP INDEX CONCURRENTLY IF EXISTS
                orderdiscount_line_id_unique_type_idx;
            """,
        ),
        migrations.RunSQL(
            sql="""
                CREATE UNIQUE INDEX CONCURRENTLY orderlinediscount_line_id_unique_type_idx
                ON discount_orderlinediscount USING btree (line_id, unique_type);
            """,
            reverse_sql="""
                DROP INDEX CONCURRENTLY IF EXISTS
                orderlinediscount_line_id_unique_type_idx;
            """,
        ),
    ]
