# Generated by Django 3.2.23 on 2024-01-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0190_merge_20231221_1356"),
        ("discount", "0077_alter_checkoutdiscount_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotionrule",
            name="gifts",
            field=models.ManyToManyField(
                blank=True,
                related_name="_discount_promotionrule_gifts_+",
                to="product.ProductVariant",
            ),
        ),
    ]
