# Generated by Django 3.2.24 on 2024-03-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0078_add_index_for_unique_type"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE discount_checkoutdiscount
                        ADD CONSTRAINT unique_checkout_discount_type
                        UNIQUE USING INDEX checkoutdiscount_checkout_id_unique_type_idx;
                    """,
                    reverse_sql="""
                        ALTER TABLE discount_checkoutdiscount DROP CONSTRAINT IF EXISTS
                        unique_checkout_discount_type;
                    """,
                ),
                # Create back the index introduced in 0078, which was converted to
                # constraint
                migrations.RunSQL(
                    sql=migrations.RunSQL.noop,
                    reverse_sql="""
                        CREATE UNIQUE INDEX CONCURRENTLY checkoutdiscount_checkout_id_unique_type_idx
                        ON discount_checkoutdiscount USING btree (checkout_id, unique_type);
                    """,
                ),
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE discount_checkoutlinediscount
                        ADD CONSTRAINT unique_checkoutline_discount_type
                        UNIQUE USING INDEX checkoutlinediscount_line_id_unique_type_idx;
                    """,
                    reverse_sql="""
                        ALTER TABLE discount_checkoutlinediscount DROP CONSTRAINT IF EXISTS
                        unique_checkoutline_discount_type;
                    """,
                ),
                # Create back the index introduced in 0078, which was converted to
                # constraint
                migrations.RunSQL(
                    sql=migrations.RunSQL.noop,
                    reverse_sql="""
                        CREATE UNIQUE INDEX CONCURRENTLY checkoutlinediscount_line_id_unique_type_idx
                        ON discount_checkoutlinediscount USING btree (line_id, unique_type);
                    """,
                ),
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE discount_orderdiscount
                        ADD CONSTRAINT unique_order_discount_type
                        UNIQUE USING INDEX orderdiscount_order_id_unique_type_idx;
                    """,
                    reverse_sql="""
                        ALTER TABLE discount_orderdiscount DROP CONSTRAINT IF EXISTS
                        unique_order_discount_type;
                    """,
                ),
                # Create back the index introduced in 0078, which was converted to
                # constraint
                migrations.RunSQL(
                    sql=migrations.RunSQL.noop,
                    reverse_sql="""
                        CREATE UNIQUE INDEX CONCURRENTLY orderdiscount_order_id_unique_type_idx
                        ON discount_orderdiscount USING btree (order_id, unique_type);
                    """,
                ),
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE discount_orderlinediscount
                        ADD CONSTRAINT unique_orderline_discount_type
                        UNIQUE USING INDEX orderlinediscount_line_id_unique_type_idx;
                    """,
                    reverse_sql="""
                        ALTER TABLE discount_orderlinediscount DROP CONSTRAINT IF EXISTS
                        unique_orderline_discount_type;
                    """,
                ),
                # Create back the index introduced in 0078, which was converted to
                # constraint
                migrations.RunSQL(
                    sql=migrations.RunSQL.noop,
                    reverse_sql="""
                        CREATE UNIQUE INDEX CONCURRENTLY orderlinediscount_line_id_unique_type_idx
                        ON discount_orderlinediscount USING btree (line_id, unique_type);
                    """,
                ),
            ],
            state_operations=[
                migrations.AddConstraint(
                    model_name="checkoutdiscount",
                    constraint=models.UniqueConstraint(
                        fields=("checkout_id", "unique_type"),
                        name="unique_checkout_discount_type",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="checkoutlinediscount",
                    constraint=models.UniqueConstraint(
                        fields=("line_id", "unique_type"),
                        name="unique_checkoutline_discount_type",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="orderdiscount",
                    constraint=models.UniqueConstraint(
                        fields=("order_id", "unique_type"),
                        name="unique_order_discount_type",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="orderlinediscount",
                    constraint=models.UniqueConstraint(
                        fields=("line_id", "unique_type"),
                        name="unique_orderline_discount_type",
                    ),
                ),
            ],
        )
    ]
