# Generated by Django 3.2.24 on 2024-04-08 11:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0079_add_index_for_unique_type"),
    ]

    # left to keep migration compatibility
    # the logic moved to 0075_add_unique_type_constraint
    operations = []
