# Generated by Django 3.2.23 on 2024-04-22 12:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0072_promotionrule_variants_dirty"),
        ("discount", "0080_add_unique_type_constraint"),
    ]

    operations = []
