# Generated by Django 3.2.24 on 2024-05-09 15:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0075_add_unique_type_constraint"),
        ("discount", "0081_merge_20240422_1207"),
    ]

    operations = []
