# Generated by Django 3.2.24 on 2024-05-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0082_merge_20240509_1550"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkoutlinediscount",
            name="unique_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sale", "Sale"),
                    ("voucher", "Voucher"),
                    ("manual", "Manual"),
                    ("promotion", "Promotion"),
                    ("order_promotion", "Order promotion"),
                ],
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="orderlinediscount",
            name="unique_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sale", "Sale"),
                    ("voucher", "Voucher"),
                    ("manual", "Manual"),
                    ("promotion", "Promotion"),
                    ("order_promotion", "Order promotion"),
                ],
                max_length=64,
                null=True,
            ),
        ),
    ]
