# Generated by Django 3.2.18 on 2024-10-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0083_auto_20240510_0838"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkoutdiscount",
            name="type",
            field=models.CharField(
                choices=[
                    ("sale", "Sale"),
                    ("voucher", "Voucher"),
                    ("manual", "Manual"),
                    ("promotion", "Promotion"),
                    ("order_promotion", "Order promotion"),
                    ("catalogue_promotion", "Catalogue promotion"),
                ],
                default="manual",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="checkoutlinediscount",
            name="type",
            field=models.CharField(
                choices=[
                    ("sale", "Sale"),
                    ("voucher", "Voucher"),
                    ("manual", "Manual"),
                    ("promotion", "Promotion"),
                    ("order_promotion", "Order promotion"),
                    ("catalogue_promotion", "Catalogue promotion"),
                ],
                default="manual",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="checkoutlinediscount",
            name="unique_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sale", "Sale"),
                    ("voucher", "Voucher"),
                    ("manual", "Manual"),
                    ("promotion", "Promotion"),
                    ("order_promotion", "Order promotion"),
                    ("catalogue_promotion", "Catalogue promotion"),
                ],
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="orderdiscount",
            name="type",
            field=models.CharField(
                choices=[
                    ("sale", "Sale"),
                    ("voucher", "Voucher"),
                    ("manual", "Manual"),
                    ("promotion", "Promotion"),
                    ("order_promotion", "Order promotion"),
                    ("catalogue_promotion", "Catalogue promotion"),
                ],
                default="manual",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="orderlinediscount",
            name="type",
            field=models.CharField(
                choices=[
                    ("sale", "Sale"),
                    ("voucher", "Voucher"),
                    ("manual", "Manual"),
                    ("promotion", "Promotion"),
                    ("order_promotion", "Order promotion"),
                    ("catalogue_promotion", "Catalogue promotion"),
                ],
                default="manual",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="orderlinediscount",
            name="unique_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sale", "Sale"),
                    ("voucher", "Voucher"),
                    ("manual", "Manual"),
                    ("promotion", "Promotion"),
                    ("order_promotion", "Order promotion"),
                    ("catalogue_promotion", "Catalogue promotion"),
                ],
                max_length=64,
                null=True,
            ),
        ),
    ]
