# Generated by Django 4.2.16 on 2025-01-14 14:28

from django.apps import apps as registry
from django.db import migrations
from django.db.models.signals import post_migrate

from .tasks.saleor3_20 import set_discount_currency_task


def set_discount_currency(apps, _schema_editor):
    def on_migrations_complete(sender=None, **kwargs):
        set_discount_currency_task.delay()

    sender = registry.get_app_config("discount")
    post_migrate.connect(on_migrations_complete, weak=False, sender=sender)


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0083_auto_20240510_0838"),
    ]

    operations = [
        migrations.RunPython(
            set_discount_currency,
            reverse_code=migrations.RunPython.noop,
        )
    ]
