# Generated by Django 4.2.15 on 2025-05-06 09:54

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0084_set_missing_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkoutdiscount",
            name="amount_value",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.0"), max_digits=20
            ),
        ),
        migrations.AlterField(
            model_name="checkoutdiscount",
            name="value",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.0"), max_digits=20
            ),
        ),
        migrations.AlterField(
            model_name="checkoutlinediscount",
            name="amount_value",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.0"), max_digits=20
            ),
        ),
        migrations.AlterField(
            model_name="checkoutlinediscount",
            name="value",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.0"), max_digits=20
            ),
        ),
        migrations.AlterField(
            model_name="orderdiscount",
            name="amount_value",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.0"), max_digits=20
            ),
        ),
        migrations.AlterField(
            model_name="orderdiscount",
            name="value",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.0"), max_digits=20
            ),
        ),
        migrations.AlterField(
            model_name="orderlinediscount",
            name="amount_value",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.0"), max_digits=20
            ),
        ),
        migrations.AlterField(
            model_name="orderlinediscount",
            name="value",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.0"), max_digits=20
            ),
        ),
        migrations.AlterField(
            model_name="promotionrule",
            name="reward_value",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="voucherchannellisting",
            name="discount_value",
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
        migrations.AlterField(
            model_name="voucherchannellisting",
            name="min_spent_amount",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=20, null=True
            ),
        ),
    ]
