# Generated by Django 5.2 on 2025-05-27 12:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0085_alter_checkoutdiscount_amount_value_and_more"),
        ("discount", "0085_alter_promotion_metadata_and_more"),
    ]

    operations = []
