# Generated by Django 5.2.1 on 2025-06-30 07:29

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0086_merge_20250527_1210"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voucher",
            name="countries",
            field=django_countries.fields.CountryField(
                blank=True, max_length=752, multiple=True
            ),
        ),
    ]
