# Generated by Django 5.2.16 on 2026-09-08 12:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0087_merge_20250630_1332"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="promotion",
            options={
                "ordering": ("name", "pk"),
                "permissions": (
                    ("manage_discounts", "Manage promotions and vouchers."),
                    ("read_discounts", "Read promotions and vouchers."),
                ),
            },
        ),
    ]
