# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_auto_20171109_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='userprofile.Address', verbose_name='billing address'),
        ),
    ]
