# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_auto_20171123_0609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverygroup',
            options={},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-last_status_change',), 'permissions': (('view_order', 'Can view orders'), ('edit_order', 'Can edit orders'))},
        ),
        migrations.AlterModelOptions(
            name='orderhistoryentry',
            options={'ordering': ('date',)},
        ),
        migrations.AlterModelOptions(
            name='orderline',
            options={'verbose_name': 'Ordered line', 'verbose_name_plural': 'Ordered lines'},
        ),
        migrations.AlterModelOptions(
            name='ordernote',
            options={},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('-pk',)},
        ),
    ]
