# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-18 10:28
from __future__ import unicode_literals

from django.db import migrations
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_auto_20171206_0506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderline',
            options={},
        ),
        migrations.RemoveField(
            model_name='deliverygroup',
            name='shipping_price',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_price',
            field=django_prices.models.PriceField(currency='USD', decimal_places=4, default=0, editable=False, max_digits=12, verbose_name='shipping price'),
        ),
    ]
