# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-03 22:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_auto_20180103_1443'),
        ('order', '0029_auto_20171228_1752'),
    ]

    operations = [
    ]
