# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0029_auto_20180111_0845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordernote',
            options={'ordering': ('date',)},
        ),
        migrations.AddField(
            model_name='ordernote',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ordernote',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
