# Generated by Django 2.0.2 on 2018-02-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("order", "0033_auto_20180123_0832")]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_gross",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="orderline",
            name="unit_price_gross",
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name="orderline",
            name="unit_price_net",
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
    ]
