# Generated by Django 2.0.2 on 2018-02-10 10:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def assign_order_to_lines(apps, schema_editor):
    OrderLine = apps.get_model('order', 'OrderLine')
    for line in OrderLine.objects.all():
        line.order = line.delivery_group.order
        line.save(update_fields=['order'])


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0033_auto_20180123_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fulfillment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, default='', max_length=255)),
                ('shipping_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('order', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='fulfillments', to='order.Order')),
            ],
        ),
        migrations.CreateModel(
            name='FulfillmentLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)])),
                ('fulfillment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='order.Fulfillment')),
            ],
        ),
        migrations.AddField(
            model_name='orderline',
            name='order',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='order.Order'),
        ),
        migrations.AddField(
            model_name='fulfillmentline',
            name='order_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='order.OrderLine'),
        ),
        migrations.RunPython(assign_order_to_lines, migrations.RunPython.noop)
    ]
