# Generated by Django 2.0.2 on 2018-02-22 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0034_auto_20180210_0422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverygroup',
            name='order',
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': (('view_order', 'Can view orders'), ('edit_order', 'Can edit orders'))},
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_status_change',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='delivery_group',
        ),
        migrations.AddField(
            model_name='fulfillment',
            name='fulfillment_order',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='fulfillment',
            name='status',
            field=models.CharField(choices=[('fulfilled', 'Fulfilled'), ('canceled', 'Canceled')], default='fulfilled', max_length=32),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method_name',
            field=models.CharField(blank=True, default=None, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unfulfilled', 'Unfulfilled'), ('partially fulfilled', 'Partially fulfilled'), ('fulfilled', 'Fulfilled'), ('canceled', 'Canceled')], default='unfulfilled', max_length=32),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='order',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='order.Order'),
        ),
        migrations.DeleteModel(
            name='DeliveryGroup',
        ),
    ]
