# Generated by Django 2.0.2 on 2018-02-22 10:58

from django.db import migrations, models
import django.db.models.deletion


def assign_delivery_group_to_lines(apps, schema_editor):
    Order = apps.get_model('order', 'Order')
    OrderLine = apps.get_model('order', 'OrderLine')
    for order in Order.objects.all():
        delivery_group = order.groups.create()
        for line in OrderLine.objects.filter(order=order):
            line.delivery_group = delivery_group
            line.save(update_fields=['delivery_group'])


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0034_auto_20180210_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='delivery_group',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='lines', to='order.DeliveryGroup'),
        ),
        migrations.RunPython(migrations.RunPython.noop, assign_delivery_group_to_lines)
    ]
