# Generated by Django 2.0.2 on 2018-02-21 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("order", "0035_auto_20180221_1057")]

    operations = [migrations.RemoveField(model_name="order", name="total_tax")]
