# Generated by Django 2.0.3 on 2018-04-05 11:56

from django.db import migrations, models
import django.db.models.deletion


def move_data_to_base_note(apps, schema_editor):
    OrderNote = apps.get_model('order', 'OrderNote')
    BaseNote = apps.get_model('core', 'BaseNote')

    for order_note in OrderNote.objects.all():
        base_note = BaseNote.objects.create(
            user=order_note.user, date=order_note.date,
            content=order_note.content, is_public=order_note.is_public)
        order_note.basenote_ptr = base_note
        order_note.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('order', '0044_auto_20180326_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordernote',
            name='id',
        ),
        migrations.AddField(
            model_name='ordernote',
            name='basenote_ptr',
            field=models.OneToOneField(auto_created=True, default=1,
                                       on_delete=django.db.models.deletion.CASCADE,
                                       parent_link=True, primary_key=True,
                                       serialize=False, to='core.BaseNote'),
            preserve_default=False,
        ),
        migrations.RunPython(move_data_to_base_note),
        migrations.RemoveField(
            model_name='ordernote',
            name='content',
        ),
        migrations.RemoveField(
            model_name='ordernote',
            name='date',
        ),

        migrations.RemoveField(
            model_name='ordernote',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='ordernote',
            name='user',
        ),


    ]
