# Generated by Django 2.0.3 on 2018-04-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0045_auto_20180329_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=5),
        ),
        migrations.AddField(
            model_name='order',
            name='include_taxes_in_prices',
            field=models.BooleanField(default=True),
        ),
    ]
