# Generated by Django 2.0.3 on 2018-08-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("order", "0049_auto_20180719_0520")]

    operations = [
        migrations.RemoveField(model_name="ordernote", name="is_public"),
        migrations.AddField(
            model_name="order",
            name="customer_note",
            field=models.TextField(blank=True, default=""),
        ),
    ]
