# Generated by Django 2.0.3 on 2018-08-22 12:20

from django.db import migrations, models
import django.db.models.deletion
import django_measurement.models
import saleor.core.weight


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0051_merge_20180807_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='weight',
            field=django_measurement.models.MeasurementField(default=saleor.core.weight.zero_weight, measurement_class='Mass'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shipping.ShippingMethod'),
        ),
    ]
