# Generated by Django 2.1.2 on 2018-10-17 18:46

from django.conf import settings
from django.db import migrations, models
import django_prices.models
import saleor.core
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0064_auto_20181016_0819'),
        ('payment', '0002_transfer_payment_to_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=django_prices.models.MoneyField(currency=settings.DEFAULT_CURRENCY, decimal_places=2, default=saleor.core.utils.taxes.zero_money, max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_gross',
            field=django_prices.models.MoneyField(currency=settings.DEFAULT_CURRENCY, decimal_places=2, default=saleor.core.utils.taxes.zero_money, max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_net',
            field=django_prices.models.MoneyField(currency=settings.DEFAULT_CURRENCY, decimal_places=2, default=saleor.core.utils.taxes.zero_money, max_digits=12),
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.AlterField(
            model_name='orderline',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5),
        ),
    ]
