# Generated by Django 2.1.2 on 2018-10-17 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0064_auto_20181017_1346'),
        ('payment', '0002_transfer_payment_to_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
