# Generated by Django 2.1.5 on 2019-02-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0067_auto_20181102_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout_token',
            field=models.CharField(blank=True, max_length=36),
        ),
    ]
