# Generated by Django 2.2 on 2019-04-25 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0052_auto_20180822_0720'),
        ('order', '0055_remove_order_note_order_history_entry'),
        ('order', '0069_auto_20190225_2305'),
        ('order', '0062_auto_20180921_0949'),
        ('order', '0060_auto_20180919_0731'),
    ]

    operations = [
    ]
