# Generated by Django 2.2.4 on 2019-08-14 09:13

import os

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("order", "0071_order_gift_cards")]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="shipping_price_gross",
            new_name="shipping_price_gross_amount",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="shipping_price_net",
            new_name="shipping_price_net_amount",
        ),
        migrations.RenameField(
            model_name="order", old_name="total_gross", new_name="total_gross_amount"
        ),
        migrations.RenameField(
            model_name="order", old_name="total_net", new_name="total_net_amount"
        ),
        migrations.RenameField(
            model_name="orderline",
            old_name="unit_price_gross",
            new_name="unit_price_gross_amount",
        ),
        migrations.RenameField(
            model_name="orderline",
            old_name="unit_price_net",
            new_name="unit_price_net_amount",
        ),
        migrations.AddField(
            model_name="order",
            name="currency",
            field=models.CharField(
                default=os.environ.get("DEFAULT_CURRENCY", "USD"),
                max_length=settings.DEFAULT_CURRENCY_CODE_LENGTH,
            ),
        ),
        migrations.AddField(
            model_name="orderline",
            name="currency",
            field=models.CharField(
                default=os.environ.get("DEFAULT_CURRENCY", "USD"),
                max_length=settings.DEFAULT_CURRENCY_CODE_LENGTH,
            ),
        ),
    ]
