# Generated by Django 2.2.10 on 2020-02-17 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0077_auto_20191118_0606"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fulfillment", options={"ordering": ("pk",)},
        ),
    ]
