# Generated by Django 2.2.10 on 2020-03-09 14:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0080_invoice"),
        ("order", "0079_auto_20200225_0237"),
    ]

    operations = []
