# Generated by Django 3.0.5 on 2020-04-26 11:47

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models

import saleor.core.utils.json_serializer


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0083_merge_20200421_0529"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="metadata",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True,
                default=dict,
                encoder=saleor.core.utils.json_serializer.CustomJsonEncoder,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="private_metadata",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True,
                default=dict,
                encoder=saleor.core.utils.json_serializer.CustomJsonEncoder,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="status",
            field=models.CharField(default="pending", max_length=32),
        ),
        migrations.AlterField(
            model_name="invoice", name="created", field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="number",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="order.Order",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="url",
            field=models.URLField(max_length=2048, null=True),
        ),
    ]
