# Generated by Django 3.0.6 on 2020-05-25 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0084_auto_20200426_0647"),
    ]

    operations = [
        migrations.DeleteModel(name="Invoice",),
    ]
