# Generated by Django 3.1.2 on 2020-11-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0089_auto_20200902_1249"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("unconfirmed", "Unconfirmed"),
                    ("unfulfilled", "Unfulfilled"),
                    ("partially fulfilled", "Partially fulfilled"),
                    ("fulfilled", "Fulfilled"),
                    ("canceled", "Canceled"),
                ],
                default="unfulfilled",
                max_length=32,
            ),
        ),
    ]
