# Generated by Django 3.1.2 on 2020-11-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0090_order_channel_listing"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="redirect_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
