# Generated by Django 3.1.1 on 2020-10-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0090_orderchannel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order", name="currency", field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name="orderline",
            name="currency",
            field=models.CharField(max_length=3),
        ),
    ]
