# Generated by Django 3.1.8 on 2021-05-11 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0105_order_total_paid_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="origin",
            field=models.CharField(
                blank=True,
                choices=[
                    ("checkout", "Checkout"),
                    ("draft", "Draft"),
                    ("reissue", "Reissue"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="original",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="order.order",
            ),
        ),
    ]
