# Generated by Django 3.1.8 on 2021-05-11 08:25

import django.db.models.deletion
from django.db import migrations, models


def set_origin_and_original_order_values(apps, schema_editor):
    Order = apps.get_model("order", "Order")
    draft_events = ["placed_from_draft", "draft_created"]
    Order.objects.filter(events__type__in=draft_events).update(origin="draft")
    orders = []
    for order in Order.objects.filter(
        events__type="draft_created_from_replace"
    ).iterator():
        order.origin = "reissue"
        order.original_id = order.events.get(
            type="draft_created_from_replace"
        ).parameters.get("related_order_pk")
        orders.append(order)
    Order.objects.bulk_update(orders, ["origin", "original"])
    Order.objects.exclude(
        events__type__in=draft_events + ["draft_created_from_replace"]
    ).update(origin="checkout")


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0105_order_total_paid_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="origin",
            field=models.CharField(
                blank=True,
                choices=[
                    ("checkout", "Checkout"),
                    ("draft", "Draft"),
                    ("reissue", "Reissue"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="original",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="order.order",
            ),
        ),
        migrations.RunPython(
            set_origin_and_original_order_values, migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="order",
            name="origin",
            field=models.CharField(
                choices=[
                    ("checkout", "Checkout"),
                    ("draft", "Draft"),
                    ("reissue", "Reissue"),
                ],
                max_length=32,
            ),
        ),
    ]
