# Generated by Django 3.2.2 on 2021-06-29 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0014_auto_20210520_0846"),
        ("order", "0111_auto_20210518_1357"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="collection_point",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="warehouse.warehouse",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="is_click_and_collect",
            field=models.BooleanField(default=False),
        ),
    ]
