# Generated by Django 3.2.2 on 2021-07-26 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0015_auto_20210713_0904"),
        ("order", "0113_orderevent_app"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="collection_point",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="warehouse.warehouse",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="collection_point_name",
            field=models.CharField(
                blank=True, default=None, editable=False, max_length=255, null=True
            ),
        ),
    ]
