# Generated by Django 3.2.5 on 2021-08-01 11:26

import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import saleor.core.utils.json_serializer


class Migration(migrations.Migration):

    dependencies = [
        ("channel", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("product", "0147_productvariantsubscription"),
        ("order", "0113_orderevent_app"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "private_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=saleor.core.utils.json_serializer.CustomJsonEncoder,
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=saleor.core.utils.json_serializer.CustomJsonEncoder,
                        null=True,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("renewed", models.DateTimeField(blank=True, null=True)),
                ("cancelled", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("on_hold", "On hold"),
                            ("canceled", "Canceled"),
                            ("expired", "Expired"),
                            ("pending_cancel", "Pending cancel"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("customer_note", models.TextField(blank=True, default="")),
                ("language_code", models.CharField(default="en", max_length=35)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="channel.channel",
                    ),
                ),
                (
                    "orders",
                    models.ManyToManyField(
                        blank=True, related_name="subscriptions", to="order.Order"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="product.productvariant",
                    ),
                ),
            ],
            options={
                "ordering": ("-pk",),
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["private_metadata"], name="subscription_p_meta_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["metadata"], name="subscription_meta_idx"
            ),
        ),
    ]
