# Generated by Django 3.2.9 on 2021-12-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0115_alter_order_language_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderline",
            name="sale_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="orderline",
            name="voucher_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
