# Generated by Django 3.2.7 on 2021-09-21 13:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0115_alter_order_language_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_methods_expiration",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
