# Generated by Django 3.2.6 on 2021-08-24 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0114_auto_20210726_1116"),
        ("order", "0115_merge_20210820_1454"),
    ]

    operations = []
