# Generated by Django 3.2.5 on 2021-08-24 20:41

from django.db import migrations, models
from django.db.models import Case, Value, When

PAYMENT_FAILED = "payment_failed"
PAYMENT_CAPTURE_FAILED = "payment_capture_failed"
PAYMENT_REFUND_FAILED = "payment_refund_failed"
PAYMENT_VOID_FAILED = "payment_void_failed"


def change_fail_event_type_up(apps, schema_editor):
    apps.get_model("order", "OrderEvent").objects.filter(type=PAYMENT_FAILED,).update(
        type=Case(
            When(
                parameters__message__icontains="refund",
                then=Value(PAYMENT_REFUND_FAILED),
            ),
            When(
                parameters__message__icontains="capture",
                then=Value(PAYMENT_CAPTURE_FAILED),
            ),
            default=Value(PAYMENT_VOID_FAILED),
        )
    )


def change_fail_event_type_down(apps, schema_editor):
    apps.get_model("order", "OrderEvent").objects.filter(
        type__in=[
            PAYMENT_REFUND_FAILED,
            PAYMENT_VOID_FAILED,
            PAYMENT_CAPTURE_FAILED,
        ]
    ).update(type=PAYMENT_FAILED)


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0116_auto_20210905_1730"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("DRAFT_CREATED", "draft_created"),
                    ("DRAFT_CREATED_FROM_REPLACE", "draft_created_from_replace"),
                    ("ADDED_PRODUCTS", "added_products"),
                    ("REMOVED_PRODUCTS", "removed_products"),
                    ("PLACED", "placed"),
                    ("PLACED_FROM_DRAFT", "placed_from_draft"),
                    ("OVERSOLD_ITEMS", "oversold_items"),
                    ("CANCELED", "canceled"),
                    ("ORDER_MARKED_AS_PAID", "order_marked_as_paid"),
                    ("ORDER_FULLY_PAID", "order_fully_paid"),
                    ("ORDER_REPLACEMENT_CREATED", "order_replacement_created"),
                    ("ORDER_DISCOUNT_ADDED", "order_discount_added"),
                    (
                        "ORDER_DISCOUNT_AUTOMATICALLY_UPDATED",
                        "order_discount_automatically_updated",
                    ),
                    ("ORDER_DISCOUNT_UPDATED", "order_discount_updated"),
                    ("ORDER_DISCOUNT_DELETED", "order_discount_deleted"),
                    ("ORDER_LINE_DISCOUNT_UPDATED", "order_line_discount_updated"),
                    ("ORDER_LINE_DISCOUNT_REMOVED", "order_line_discount_removed"),
                    ("ORDER_LINE_PRODUCT_DELETED", "order_line_product_deleted"),
                    ("ORDER_LINE_VARIANT_DELETED", "order_line_variant_deleted"),
                    ("UPDATED_ADDRESS", "updated_address"),
                    ("EMAIL_SENT", "email_sent"),
                    ("CONFIRMED", "confirmed"),
                    ("PAYMENT_AUTHORIZED", "payment_authorized"),
                    ("PAYMENT_CAPTURED", "payment_captured"),
                    ("EXTERNAL_SERVICE_NOTIFICATION", "external_service_notification"),
                    ("PAYMENT_REFUNDED", "payment_refunded"),
                    ("PAYMENT_VOIDED", "payment_voided"),
                    ("PAYMENT_CAPTURE_FAILED", "payment_capture_failed"),
                    ("PAYMENT_REFUND_FAILED", "payment_refund_failed"),
                    ("PAYMENT_VOID_FAILED", "payment_void_failed"),
                    ("INVOICE_REQUESTED", "invoice_requested"),
                    ("INVOICE_GENERATED", "invoice_generated"),
                    ("INVOICE_UPDATED", "invoice_updated"),
                    ("INVOICE_SENT", "invoice_sent"),
                    ("FULFILLMENT_CANCELED", "fulfillment_canceled"),
                    ("FULFILLMENT_RESTOCKED_ITEMS", "fulfillment_restocked_items"),
                    ("FULFILLMENT_FULFILLED_ITEMS", "fulfillment_fulfilled_items"),
                    ("FULFILLMENT_REFUNDED", "fulfillment_refunded"),
                    ("FULFILLMENT_RETURNED", "fulfillment_returned"),
                    ("FULFILLMENT_REPLACED", "fulfillment_replaced"),
                    ("TRACKING_UPDATED", "tracking_updated"),
                    ("NOTE_ADDED", "note_added"),
                    ("OTHER", "other"),
                ],
                max_length=255,
            ),
        ),
        migrations.RunPython(change_fail_event_type_up, change_fail_event_type_down),
    ]
