# Generated by Django 3.2.6 on 2021-09-17 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0116_alter_orderevent_type"),
        ("order", "0117_alter_orderevent_type"),
    ]

    operations = []
