# Generated by Django 3.2.6 on 2021-08-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0117_merge_20210903_1013"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderline",
            name="product_sku",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="orderline",
            name="product_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
