# Generated by Django 3.2.8 on 2021-10-22 09:00

import django.contrib.postgres.indexes
from django.db import migrations, models

import saleor.core.utils.json_serializer


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0120_orderline_optional_sku"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderline",
            options={
                "ordering": ("pk",),
                "permissions": (("manage_orders", "Manage orders"),),
            },
        ),
        migrations.AddField(
            model_name="orderline",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=saleor.core.utils.json_serializer.CustomJsonEncoder,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="orderline",
            name="private_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=saleor.core.utils.json_serializer.CustomJsonEncoder,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="orderline",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["private_metadata"], name="orderline_p_meta_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderline",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["metadata"], name="orderline_meta_idx"
            ),
        ),
    ]
