# Generated by Django 3.2.8 on 2021-12-07 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0121_merge_20211120_1036"),
        ("order", "0121_order_search_document"),
    ]

    operations = []
