# Generated by Django 3.2.6 on 2022-01-24 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0122_merge_20211221_0949"),
        ("order", "0123_update_order_search_document"),
    ]

    operations = []
