# Generated by Django 3.2.12 on 2022-02-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0123_update_order_search_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
