# Generated by Django 3.2.12 on 2022-02-09 13:58

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("order", "0124_order_updated_at"),
    ]

    operations = [
        migrations.RunSQL(
            """
            UPDATE order_order
            SET updated_at = (
                SELECT MAX (order_orderevent.date)
                FROM order_orderevent
                WHERE order_orderevent.order_id = order_order.id
            )
            WHERE updated_at IS NULL;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            """
            UPDATE order_order
            SET updated_at = created
            WHERE updated_at IS NULL;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
