# Generated by Django 3.2.12 on 2022-02-24 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0126_auto_20220224_0913"),
        # ("account", "0061_rename_order_token_customerevent_order"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name="order",
        #     name="id",
        # ),
    ]
