# Generated by Django 3.2.12 on 2022-03-02 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0124_merge_20220124_1154"),
        ("order", "0126_alter_order_updated_at"),
    ]

    operations = []
