# Generated by Django 3.2.12 on 2022-03-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0133_alter_order_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="should_refresh_prices",
            field=models.BooleanField(default=True),
        ),
    ]
