# Generated by Django 3.2.12 on 2022-04-11 12:32

from django.db import migrations
from django.db.models import F
from django.db.models import OuterRef, Subquery
from django.contrib.postgres.functions import RandomUUID


def set_order_line_token_created_at_and_old_id(apps, _schema_editor):
    OrderLine = apps.get_model("order", "OrderLine")
    Order = apps.get_model("order", "Order")

    OrderLine.objects.filter(token__isnull=True).update(
        old_id=F("id"),
        token=RandomUUID(),
        created_at=Subquery(
            Order.objects.filter(lines=OuterRef("id")).values("created_at")[:1]
        ),
    )


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0138_add_orderline_token_old_id_created_at"),
    ]

    operations = [
        migrations.RunPython(
            set_order_line_token_created_at_and_old_id,
            migrations.RunPython.noop,
        )
    ]
