# Generated by Django 3.2.12 on 2022-04-11 12:32

from django.db import migrations
from django.db.models import F, OuterRef, Subquery, Case, When
from django.contrib.postgres.functions import RandomUUID
from django.contrib.postgres.operations import CryptoExtension


def set_order_line_old_id_and_order_line_token_and_created_at(apps, _schema_editor):
    OrderLine = apps.get_model("order", "OrderLine")
    Order = apps.get_model("order", "Order")

    OrderLine.objects.update(
        old_id=F("id"),
        token=Case(When(token__isnull=True, then=RandomUUID()), default="token"),
        created_at=Case(
            When(
                token__isnull=True,
                then=Subquery(
                    Order.objects.filter(lines=OuterRef("id")).values("created_at")[:1]
                ),
            ),
            default="created_at",
        ),
    )


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0138_add_orderline_token_old_id_created_at"),
    ]

    operations = [
        CryptoExtension(),
        migrations.RunPython(
            set_order_line_old_id_and_order_line_token_and_created_at,
            migrations.RunPython.noop,
        ),
    ]
