# Generated by Django 3.2.12 on 2022-04-13 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0140_alter_orderline_old_id_and_created_at"),
    ]

    operations = [
        migrations.RunSQL(
            """
            UPDATE order_fulfillmentline
            SET order_line_token = (
                SELECT token
                FROM order_orderline
                WHERE order_fulfillmentline.order_line_id = order_orderline.id
            )
            WHERE order_line_id IS NOT NULL;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
