# Generated by Django 3.2.13 on 2022-05-12 10:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0138_orderline_base_price"),
        ("order", "0145_rewrite_order_events"),
    ]

    operations = []
