# Generated by Django 3.2.13 on 2022-06-15 12:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0139_fix_undiscounted_total_on_lines"),
        ("order", "0150_update_authorize_and_charge_status"),
    ]

    operations = []
