# Generated by Django 3.2.16 on 2022-12-15 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0140_fix_order_undiscounted_total"),
        ("order", "0151_merge_20220615_1224"),
    ]

    operations = []
