# Generated by Django 3.2.13 on 2022-06-15 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0151_merge_20220615_1224"),
        ("order", "0152_update_order_search_vector"),
    ]

    operations = []
