# Generated by Django 3.2.16 on 2022-12-15 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0156_merge_20221215_1235"),
        ("order", "0158_migrate_base_shipping_price_amount"),
    ]

    operations = []
