# Generated by Django 3.2.16 on 2022-12-15 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0159_merge_20221215_1244"),
        ("order", "0159_order_shipping_tax_class_and_more"),
    ]

    operations = []
