# Generated by Django 3.2.16 on 2022-12-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0159_order_shipping_tax_class_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="external_reference",
            field=models.CharField(
                blank=True, db_index=True, max_length=250, null=True, unique=True
            ),
        ),
    ]
