# Generated by Django 3.2.18 on 2023-04-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0164_auto_20230329_1200"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="expired_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
