# Generated by Django 3.2.18 on 2023-05-08 19:16

from django.db import migrations
from django.apps import apps as registry
from django.db.models.signals import post_migrate
from .tasks.saleor3_13 import order_update_number_as_str_task


def update_number_as_str(apps, _schema_editor):
    def on_migrations_complete(sender=None, **kwargs):
        order_update_number_as_str_task.delay()

    sender = registry.get_app_config("order")
    post_migrate.connect(on_migrations_complete, weak=False, sender=sender)


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0165_order_number_as_str"),
    ]

    operations = [
        migrations.RunPython(
            update_number_as_str,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
