# Generated by Django 3.2.18 on 2023-04-13 13:22

from django.db import migrations, models
import saleor.order.models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0167_alter_order_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="number",
            field=models.CharField(
                default=saleor.order.models.get_order_number,
                editable=False,
                max_length=64,
                unique=True,
            ),
        ),
    ]
