# Generated by Django 3.2.22 on 2023-10-30 08:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0165_fix_order_charge_status_with_transactions"),
        ("order", "0169_alter_order_options"),
    ]

    operations = []
