# Generated by Django 3.2.19 on 2023-06-01 08:15

from django.db import migrations, models
from django.db.models import Exists, OuterRef

# Batch size of size 5000 is about 5MB memory
BATCH_SIZE = 5000


def queryset_in_batches(queryset):
    """Slice a queryset into batches.

    Input queryset should be sorted be pk.
    """
    start_pk = 0

    while True:
        qs = queryset.filter(pk__gt=start_pk)[:BATCH_SIZE]
        pks = list(qs.values_list("pk", flat=True))

        if not pks:
            break

        yield pks

        start_pk = pks[-1]


def drop_status_field_from_transaction_event(apps, _schema_editor):
    OrderEvent = apps.get_model("order", "OrderEvent")
    TransactionItem = apps.get_model("payment", "TransactionItem")
    orders = TransactionItem.objects.filter(order_id__isnull=False)

    qs = OrderEvent.objects.filter(
        Exists(orders.filter(order_id=OuterRef("order_id"))),
        type="transaction_event",
        parameters__has_key="status",
    ).order_by("pk")

    for ids_batch in queryset_in_batches(qs):
        events_to_update = []
        events = OrderEvent.objects.filter(pk__in=ids_batch)
        for event in events:
            if "status" in event.parameters:
                del event.parameters["status"]
                events_to_update.append(event)
        OrderEvent.objects.bulk_update(events_to_update, ["parameters"])


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0171_auto_20230518_0854"),
        ("payment", "0053_auto_20230601_0818"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("DRAFT_CREATED", "draft_created"),
                    ("DRAFT_CREATED_FROM_REPLACE", "draft_created_from_replace"),
                    ("ADDED_PRODUCTS", "added_products"),
                    ("REMOVED_PRODUCTS", "removed_products"),
                    ("PLACED", "placed"),
                    ("PLACED_FROM_DRAFT", "placed_from_draft"),
                    ("OVERSOLD_ITEMS", "oversold_items"),
                    ("CANCELED", "canceled"),
                    ("EXPIRED", "expired"),
                    ("ORDER_MARKED_AS_PAID", "order_marked_as_paid"),
                    ("ORDER_FULLY_PAID", "order_fully_paid"),
                    ("ORDER_REPLACEMENT_CREATED", "order_replacement_created"),
                    ("ORDER_DISCOUNT_ADDED", "order_discount_added"),
                    (
                        "ORDER_DISCOUNT_AUTOMATICALLY_UPDATED",
                        "order_discount_automatically_updated",
                    ),
                    ("ORDER_DISCOUNT_UPDATED", "order_discount_updated"),
                    ("ORDER_DISCOUNT_DELETED", "order_discount_deleted"),
                    ("ORDER_LINE_DISCOUNT_UPDATED", "order_line_discount_updated"),
                    ("ORDER_LINE_DISCOUNT_REMOVED", "order_line_discount_removed"),
                    ("ORDER_LINE_PRODUCT_DELETED", "order_line_product_deleted"),
                    ("ORDER_LINE_VARIANT_DELETED", "order_line_variant_deleted"),
                    ("UPDATED_ADDRESS", "updated_address"),
                    ("EMAIL_SENT", "email_sent"),
                    ("CONFIRMED", "confirmed"),
                    ("PAYMENT_AUTHORIZED", "payment_authorized"),
                    ("PAYMENT_CAPTURED", "payment_captured"),
                    ("EXTERNAL_SERVICE_NOTIFICATION", "external_service_notification"),
                    ("PAYMENT_REFUNDED", "payment_refunded"),
                    ("PAYMENT_VOIDED", "payment_voided"),
                    ("PAYMENT_FAILED", "payment_failed"),
                    ("TRANSACTION_EVENT", "transaction_event"),
                    ("TRANSACTION_CHARGE_REQUESTED", "transaction_charge_requested"),
                    ("TRANSACTION_REFUND_REQUESTED", "transaction_refund_requested"),
                    ("TRANSACTION_CANCEL_REQUESTED", "transaction_cancel_requested"),
                    (
                        "TRANSACTION_MARK_AS_PAID_FAILED",
                        "transaction_mark_as_paid_failed",
                    ),
                    ("INVOICE_REQUESTED", "invoice_requested"),
                    ("INVOICE_GENERATED", "invoice_generated"),
                    ("INVOICE_UPDATED", "invoice_updated"),
                    ("INVOICE_SENT", "invoice_sent"),
                    ("FULFILLMENT_CANCELED", "fulfillment_canceled"),
                    ("FULFILLMENT_RESTOCKED_ITEMS", "fulfillment_restocked_items"),
                    ("FULFILLMENT_FULFILLED_ITEMS", "fulfillment_fulfilled_items"),
                    ("FULFILLMENT_REFUNDED", "fulfillment_refunded"),
                    ("FULFILLMENT_RETURNED", "fulfillment_returned"),
                    ("FULFILLMENT_REPLACED", "fulfillment_replaced"),
                    ("FULFILLMENT_AWAITS_APPROVAL", "fulfillment_awaits_approval"),
                    ("TRACKING_UPDATED", "tracking_updated"),
                    ("NOTE_ADDED", "note_added"),
                    ("NOTE_UPDATED", "note_updated"),
                    ("OTHER", "other"),
                ],
                max_length=255,
            ),
        ),
        migrations.RunPython(
            drop_status_field_from_transaction_event,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
