# Generated by Django 3.2.20 on 2023-08-31 17:45

from django.db import migrations, models
from django.contrib.postgres.operations import AddIndexConcurrently


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0173_auto_20230816_1245"),
    ]

    atomic = False

    operations = [
        AddIndexConcurrently(
            model_name="order",
            index=models.Index(fields=["created_at"], name="idx_order_created_at"),
        ),
    ]
