# Generated by Django 3.2.22 on 2023-10-30 10:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0170_merge_20231030_0857"),
        ("order", "0173_auto_20230816_1245"),
    ]

    operations = []
