# Generated by Django 3.2.22 on 2023-10-30 10:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0174_merge_20231030_1033"),
        ("order", "0174_order_idx_order_created_at"),
    ]

    operations = []
