# Generated by Django 3.2.22 on 2024-03-25 13:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0172_update_order_cc_addresses"),
        ("order", "0175_merge_20231122_1040"),
    ]

    operations = []
