# Generated by Django 3.2.21 on 2023-10-04 10:26

from django.contrib.postgres.indexes import GinIndex
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("order", "0175_order_voucher_code"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="order",
            index=GinIndex(fields=["voucher_code"], name="order_voucher_code_idx"),
        ),
    ]
