# Generated by Django 3.2.22 on 2024-07-26 14:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0174_order_checkout_token_btree_idx"),
        ("order", "0177_merge_20240606_1022"),
    ]

    operations = []
