# Generated by Django 3.2.23 on 2023-11-08 09:08

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0179_merge_20231122_1348"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="subtotal_gross_amount",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0"), max_digits=12
            ),
        ),
        migrations.RunSQL(
            """
            ALTER TABLE order_order
            ALTER COLUMN subtotal_gross_amount
            SET DEFAULT 0;
            """,
            migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name="order",
            name="subtotal_net_amount",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0"), max_digits=12
            ),
        ),
        migrations.RunSQL(
            """
            ALTER TABLE order_order
            ALTER COLUMN subtotal_net_amount
            SET DEFAULT 0;
            """,
            migrations.RunSQL.noop,
        ),
    ]
