# Generated by Django 3.2.22 on 2024-07-26 14:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0179_merge_20240726_1438"),
        ("order", "0181_merge_20240606_1325"),
    ]

    operations = []
