# Generated by Django 3.2.22 on 2024-03-25 13:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0180_merge_20240325_1333"),
        ("order", "0181_order_subtotal_as_a_field"),
    ]

    operations = []
