# Generated by Django 3.2.22 on 2024-06-07 12:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0181_merge_20240606_1325"),
        ("order", "0184_merge_0182_merge_20240325_1338_0183_order_tax_error"),
    ]

    operations = []
