# Generated by Django 3.2.25 on 2024-06-07 12:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0183_merge_20240607_1222"),
        ("order", "0185_merge_20240607_1231"),
    ]

    operations = []
