# Generated by Django 3.2.25 on 2024-06-17 10:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0185_ordergrantedrefund_transaction_item"),
        ("order", "0186_merge_20240607_1247"),
    ]

    operations = []
