# Generated by Django 3.2.25 on 2024-07-08 08:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0188_merge_20240624_1308"),
        ("order", "0188_order_undiscounted_base_shipping_price_amount"),
    ]

    operations = []
