# Generated by Django 3.2.25 on 2024-07-08 08:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0189_merge_20240708_0813"),
        ("order", "0189_set_undiscounted_base_shipping_price"),
    ]

    operations = []
