# Generated by Django 3.2.23 on 2024-07-26 15:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0185_merge_20240726_1445"),
        ("order", "0190_set_undiscounted_base_shipping_price"),
    ]

    operations = []
