# Generated by Django 3.2.25 on 2024-07-25 08:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0190_merge_20240708_0814"),
        ("order", "0190_set_undiscounted_base_shipping_price"),
    ]

    operations = []
