# Generated by Django 3.2.25 on 2024-08-05 07:27
from django.apps import apps as registry
from django.db import migrations
from django.db.models.signals import post_migrate

from .tasks.saleor3_19 import set_udniscounted_base_shipping_price_on_draft_orders_task


def set_udniscounted_base_shipping_price_on_draft_orders(apps, _schema_editor):
    def on_migrations_complete(sender=None, **kwargs):
        set_udniscounted_base_shipping_price_on_draft_orders_task.delay()

    sender = registry.get_app_config("account")
    post_migrate.connect(on_migrations_complete, weak=False, sender=sender)


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0191_merge_20240726_1508"),
    ]

    operations = [
        migrations.RunPython(
            set_udniscounted_base_shipping_price_on_draft_orders,
            reverse_code=migrations.RunPython.noop,
        )
    ]
