# Generated by Django 3.2.23 on 2024-07-26 15:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0192_merge_20240725_0850"),
        ("order", "0192_merge_20240726_1513"),
    ]

    operations = []
