# Generated by Django 3.2.25 on 2024-08-05 07:27
from django.apps import apps as registry
from django.db import migrations
from django.db.models.signals import post_migrate

from .tasks.saleor3_19 import set_order_subtotal_for_orders_created_from_bulk


def fix_order_subtotal_for_orders_from_bulk(apps, _schema_editor):
    def on_migrations_complete(sender=None, **kwargs):
        set_order_subtotal_for_orders_created_from_bulk.delay()

    sender = registry.get_app_config("account")
    post_migrate.connect(on_migrations_complete, weak=False, sender=sender)


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0192_set_undiscounted_base_shipping_price_on_draft_orders"),
    ]

    operations = [
        migrations.RunPython(
            fix_order_subtotal_for_orders_from_bulk,
            reverse_code=migrations.RunPython.noop,
        )
    ]
