# Generated by Django 3.2.25 on 2024-08-05 08:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0192_merge_20240726_1513"),
        ("order", "0192_set_undiscounted_base_shipping_price_on_draft_orders"),
    ]

    operations = []
