# Generated by Django 3.2.25 on 2024-10-07 07:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0193_fix_subtotal_value_for_order_from_bulk"),
        ("order", "0193_merge_20240805_0810"),
    ]

    operations = []
