# Generated by Django 4.2.15 on 2025-05-06 09:54

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0195_merge_20241014_0617"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fulfillment",
            name="shipping_refund_amount",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="fulfillment",
            name="total_refund_amount",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="base_shipping_price_amount",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.0"), max_digits=20
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_price_gross_amount",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.0"), editable=False, max_digits=20
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_price_net_amount",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.0"), editable=False, max_digits=20
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="subtotal_gross_amount",
            field=models.DecimalField(
                decimal_places=3, default=Decimal(0), max_digits=20
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="subtotal_net_amount",
            field=models.DecimalField(
                decimal_places=3, default=Decimal(0), max_digits=20
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_authorized_amount",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.0"), max_digits=20
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_charged_amount",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.0"), max_digits=20
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_gross_amount",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.0"), max_digits=20
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_net_amount",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.0"), max_digits=20
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="undiscounted_base_shipping_price_amount",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="undiscounted_total_gross_amount",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.0"), max_digits=20
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="undiscounted_total_net_amount",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.0"), max_digits=20
            ),
        ),
        migrations.AlterField(
            model_name="ordergrantedrefund",
            name="amount_value",
            field=models.DecimalField(
                decimal_places=3, default=Decimal(0), max_digits=20
            ),
        ),
        migrations.AlterField(
            model_name="orderline",
            name="base_unit_price_amount",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.0"), max_digits=20
            ),
        ),
        migrations.AlterField(
            model_name="orderline",
            name="total_price_gross_amount",
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
        migrations.AlterField(
            model_name="orderline",
            name="total_price_net_amount",
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
        migrations.AlterField(
            model_name="orderline",
            name="undiscounted_base_unit_price_amount",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.0"), max_digits=20
            ),
        ),
        migrations.AlterField(
            model_name="orderline",
            name="undiscounted_total_price_gross_amount",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.0"), max_digits=20
            ),
        ),
        migrations.AlterField(
            model_name="orderline",
            name="undiscounted_total_price_net_amount",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.0"), max_digits=20
            ),
        ),
        migrations.AlterField(
            model_name="orderline",
            name="undiscounted_unit_price_gross_amount",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.0"), max_digits=20
            ),
        ),
        migrations.AlterField(
            model_name="orderline",
            name="undiscounted_unit_price_net_amount",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.0"), max_digits=20
            ),
        ),
        migrations.AlterField(
            model_name="orderline",
            name="unit_discount_amount",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.0"), max_digits=20
            ),
        ),
        migrations.AlterField(
            model_name="orderline",
            name="unit_discount_value",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.0"), max_digits=20
            ),
        ),
        migrations.AlterField(
            model_name="orderline",
            name="unit_price_gross_amount",
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
        migrations.AlterField(
            model_name="orderline",
            name="unit_price_net_amount",
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
    ]
