# Generated by Django 4.2.15 on 2024-10-14 06:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0195_merge_20241004_0811"),
        ("order", "0195_merge_20241014_0617"),
    ]

    operations = []
