# Generated by Django 4.2.15 on 2025-01-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0195_merge_20241014_0617"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="billing_address_saving_strategy",
            field=models.CharField(
                choices=[
                    ("save_in_user_address_book", "Save in user address book"),
                    (
                        "do_not_save_in_user_address_book",
                        "Do not save in user address book",
                    ),
                ],
                default="save_in_user_address_book",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_address_saving_strategy",
            field=models.CharField(
                choices=[
                    ("save_in_user_address_book", "Save in user address book"),
                    (
                        "do_not_save_in_user_address_book",
                        "Do not save in user address book",
                    ),
                ],
                default="save_in_user_address_book",
                max_length=64,
            ),
        ),
        migrations.RunSQL(
            """
            ALTER TABLE order_order
            ALTER COLUMN billing_address_saving_strategy
            SET DEFAULT 'save_in_user_address_book';
            """,
            migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            """
            ALTER TABLE order_order
            ALTER COLUMN shipping_address_saving_strategy
            SET DEFAULT 'save_in_user_address_book';
            """,
            migrations.RunSQL.noop,
        ),
    ]
