# Generated by Django 4.2.15 on 2025-02-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0195_merge_20241014_0617"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="save_billing_address",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="save_shipping_address",
            field=models.BooleanField(default=False),
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE order_order
            ALTER COLUMN save_billing_address
            SET DEFAULT false;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE order_order
            ALTER COLUMN save_shipping_address
            SET DEFAULT false;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
