# Generated by Django 4.2.15 on 2025-01-24 11:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0196_merge_20241014_0631"),
        ("order", "0196_order_billing_address_saving_strategy_and_more"),
    ]

    operations = []
