# Generated by Django 4.2.15 on 2025-07-02 11:39

from django.apps import apps as registry
from django.db import migrations
from django.db.models.signals import post_migrate

from .tasks.saleor3_21 import fix_negative_total_net_for_orders_using_gift_cards_task


def fix_negative_total_net_for_orders_using_gift_cards(apps, _schema_editor):
    def on_migrations_complete(sender=None, **kwargs):
        fix_negative_total_net_for_orders_using_gift_cards_task.delay()

    sender = registry.get_app_config("order")
    post_migrate.connect(on_migrations_complete, weak=False, sender=sender)


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0196_alter_fulfillment_shipping_refund_amount_and_more"),
    ]

    operations = [
        migrations.RunPython(
            fix_negative_total_net_for_orders_using_gift_cards,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
