# Generated by Django 4.2.15 on 2025-02-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0196_merge_20241014_0631"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="draft_save_billing_address",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="draft_save_shipping_address",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
