# Generated by Django 4.2.16 on 2025-03-05 11:21

from django.apps import apps as registry
from django.db import migrations
from django.db.models.signals import post_migrate

from .tasks.saleor3_21 import set_base_price_expire_time_task


def set_base_price_expire_time(apps, _schema_editor):
    def on_migrations_complete(sender=None, **kwargs):
        set_base_price_expire_time_task.delay()

    sender = registry.get_app_config("order")
    post_migrate.connect(on_migrations_complete, weak=False, sender=sender)


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0198_orderline_draft_base_price_expire_at"),
    ]

    operations = [
        migrations.RunPython(
            set_base_price_expire_time,
            reverse_code=migrations.RunPython.noop,
        )
    ]
