# Generated by Django 4.2.20 on 2025-05-07 06:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0196_alter_fulfillment_shipping_refund_amount_and_more"),
        ("order", "0200_order_with_waiting_for_approval_fulfillments"),
    ]

    operations = []
