# Generated by Django 5.2 on 2025-05-27 12:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0201_alter_fulfillment_metadata_and_more"),
        ("order", "0202_alter_order_undiscounted_base_shipping_price_amount"),
    ]

    operations = []
