# Generated by Django 5.2.1 on 2025-06-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0203_merge_20250527_1210"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="lines_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
