# Generated by Django 5.2.1 on 2025-06-03 10:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0203_merge_20250527_1210"),
        ("order", "0203_order_lines_count"),
    ]

    operations = []
