# Generated by Django 5.2.1 on 2025-06-06 11:07

from django.contrib.postgres.indexes import BTreeIndex
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("order", "0203_merge_20250527_1210"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="fulfillment",
            index=BTreeIndex(fields=["status"], name="fulfillment_status_idx"),
        ),
    ]
