# Generated by Django 4.2.20 on 2025-07-03 14:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0197_fix_negative_total_net_for_orders_using_gift_cards"),
        ("order", "0204_set_order_lines_count"),
    ]

    operations = []
