# Generated by Django 5.2.1 on 2025-06-03 11:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0204_merge_0203_merge_20250527_1210_0203_order_lines_count"),
        ("order", "0204_set_order_lines_count"),
    ]

    operations = []
