# Generated by Django 4.2.20 on 2025-11-04 11:55

from django.db import migrations, models

import saleor.core.utils.json_serializer


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0205_merge_20250703_1438"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_method_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=saleor.core.utils.json_serializer.CustomJsonEncoder,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_method_private_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=saleor.core.utils.json_serializer.CustomJsonEncoder,
                null=True,
            ),
        ),
        migrations.RunSQL(
            "ALTER TABLE order_order ALTER COLUMN shipping_method_metadata SET DEFAULT '{}';",
            migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "ALTER TABLE order_order ALTER COLUMN shipping_method_private_metadata SET DEFAULT '{}';",
            migrations.RunSQL.noop,
        ),
    ]
