# Generated by Django 5.2.1 on 2025-06-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0206_alter_order_lines_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderline",
            name="product_type_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
