# Generated by Django 5.2.1 on 2025-07-04 10:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0205_merge_20250703_1438"),
        ("order", "0215_merge_20250623_0624"),
    ]

    operations = []
