# Generated by Django 5.2.11 on 2026-02-10 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0220_add_reason_reference_to_ordergrantedrefundline"),
        ("page", "0031_alter_page_metadata_alter_page_private_metadata_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fulfillment",
            name="reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="fulfillment",
            name="reason_reference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="page.page",
            ),
        ),
    ]
