# Generated by Django 5.2.14 on 2026-06-02 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0222_ordergrantedrefundline_reason_reference"),
        ("page", "0035_page_page_slug_btree_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="fulfillment",
            name="reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE order_fulfillment
            ALTER COLUMN reason
            SET DEFAULT '';
            """,
            reverse_sql="""
            ALTER TABLE order_fulfillment
            ALTER COLUMN reason
            DROP DEFAULT;
            """,
        ),
        migrations.AddField(
            model_name="fulfillment",
            name="reason_reference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="page.page",
            ),
        ),
        migrations.AddField(
            model_name="fulfillmentline",
            name="reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE order_fulfillmentline
            ALTER COLUMN reason
            SET DEFAULT '';
            """,
            reverse_sql="""
            ALTER TABLE order_fulfillmentline
            ALTER COLUMN reason
            DROP DEFAULT;
            """,
        ),
        migrations.AddField(
            model_name="fulfillmentline",
            name="reason_reference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="page.page",
            ),
        ),
    ]
