# Generated by Django 5.2.15 on 2026-07-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0226_grantedrefundline_reason_ref_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderline",
            name="price_override_reason",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
