# Generated by Django 5.2.17 on 2026-09-17 09:35

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0227_orderline_price_override_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="base_subtotal_amount",
            field=models.DecimalField(
                db_default=Decimal(0),
                decimal_places=3,
                default=Decimal(0),
                max_digits=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="base_total_amount",
            field=models.DecimalField(
                db_default=Decimal(0),
                decimal_places=3,
                default=Decimal(0),
                max_digits=20,
            ),
        ),
    ]
