# Generated by Django 5.2.15 on 2026-07-31 22:30

from decimal import Decimal

from django.db import migrations, models
from django.db.models import Sum


def backfill_order_refund_status(apps, _schema_editor):
    Order = apps.get_model("order", "Order")
    for order in Order.objects.all().iterator(chunk_size=2000):
        last_payment = order.payments.order_by("pk").last()
        payment_is_active = last_payment and last_payment.is_active
        payment_is_fully_refunded = (
            last_payment and last_payment.charge_status == "fully-refunded"
        )
        if payment_is_active or payment_is_fully_refunded:
            total_refunded = (
                last_payment.transactions.filter(
                    kind="refund", is_success=True
                ).aggregate(total=Sum("amount"))["total"]
                or Decimal(0)
            )
        else:
            total_refunded = sum(
                (
                    tr.refunded_value
                    for tr in order.payment_transactions.all()
                ),
                Decimal(0),
            )
        total_charged = order.total_charged_amount or Decimal(0)
        if total_refunded <= Decimal(0):
            order.refund_status = "none"
        elif total_refunded >= total_charged:
            order.refund_status = "full"
        else:
            order.refund_status = "partial"
        order.save(update_fields=["refund_status"])


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0227_orderline_price_override_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="refund_status",
            field=models.CharField(
                choices=[
                    ("none", "No refunds were made."),
                    ("partial", "The order is partially refunded"),
                    ("full", "The order is fully refunded"),
                ],
                db_index=True,
                default="none",
                max_length=32,
                null=True,
            ),
        ),
        migrations.RunPython(
            backfill_order_refund_status,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="order",
            name="refund_status",
            field=models.CharField(
                choices=[
                    ("none", "No refunds were made."),
                    ("partial", "The order is partially refunded"),
                    ("full", "The order is fully refunded"),
                ],
                db_index=True,
                default="none",
                max_length=32,
            ),
        ),
    ]
