# Generated by Django 5.2.15 on 2026-07-31 22:30

from django.apps import apps as registry
from django.db import migrations
from django.db.models.signals import post_migrate

from .tasks.saleor3_24 import backfill_order_statuses


def backfill_order_statuses_migration(apps, _schema_editor):
    """Schedule the backfill of the refund and the charge status of the orders.

    The task runs once all the migrations are applied, so it does not block the
    deployment and can process the orders in batches.
    """

    def on_migrations_complete(sender=None, **kwargs):
        backfill_order_statuses.delay(current_depth=0)

    sender = registry.get_app_config("order")
    post_migrate.connect(on_migrations_complete, weak=False, sender=sender)


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0228_order_refund_status"),
    ]

    operations = [
        migrations.RunPython(
            backfill_order_statuses_migration,
            migrations.RunPython.noop,
        ),
    ]
