# Generated by Django 5.2.8 on 2026-03-11 18:00

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0235_order_allow_variant_reallocation"),
    ]

    operations = [
        migrations.AddField(
            model_name="fulfillment",
            name="shipping_allocated_net_amount",
            field=models.DecimalField(
                decimal_places=3, default=Decimal(0), max_digits=20
            ),
        ),
    ]
