# Generated by Django 3.2.17 on 2023-02-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("thumbnail", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thumbnail",
            name="format",
            field=models.CharField(
                blank=True,
                choices=[("original", "Original"), ("avif", "AVIF"), ("webp", "WebP")],
                max_length=32,
                null=True,
            ),
        ),
    ]
