# Generated by Django 3.2.16 on 2023-01-30 14:49

import django.contrib.postgres.indexes
from django.db import migrations, models
import saleor.core.utils.json_serializer


class Migration(migrations.Migration):

    dependencies = [
        ("thumbnail", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="thumbnail",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=saleor.core.utils.json_serializer.CustomJsonEncoder,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="thumbnail",
            name="private_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=saleor.core.utils.json_serializer.CustomJsonEncoder,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="thumbnail",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["private_metadata"], name="thumbnail_p_meta_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="thumbnail",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["metadata"], name="thumbnail_meta_idx"
            ),
        ),
    ]
