# Generated by Django 3.2.18 on 2023-04-12 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0025_auto_20230420_1544"),
        ("thumbnail", "0002_alter_thumbnail_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="thumbnail",
            name="app",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="thumbnails",
                to="app.app",
            ),
        ),
        migrations.AddField(
            model_name="thumbnail",
            name="app_installation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="thumbnails",
                to="app.appinstallation",
            ),
        ),
    ]
