# Generated by Django 3.2.23 on 2024-03-27 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0029_pagemedia'),
        ('thumbnail', '0003_auto_20230412_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnail',
            name='page_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='page.pagemedia'),
        ),
    ]
