# Generated by Django 5.2.16 on 2026-09-15 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0106_merge_20260807_0748"),
        ("app", "0042_merge_20260820_0919"),
        ("media", "0001_initial"),
        ("product", "0207_remove_producttype_is_digital_from_state"),
        ("thumbnail", "0003_auto_20230412_1943"),
    ]

    # Adding a nullable column without a default is metadata-only on PostgreSQL 11+.
    # The supporting indexes are built concurrently in the next migration.
    operations = [
        migrations.AddField(
            model_name="thumbnail",
            name="category_media",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="thumbnails",
                to="media.categorymedia",
            ),
        ),
        migrations.AddField(
            model_name="thumbnail",
            name="collection_media",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="thumbnails",
                to="media.collectionmedia",
            ),
        ),
        migrations.AddField(
            model_name="thumbnail",
            name="page_media",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="thumbnails",
                to="media.pagemedia",
            ),
        ),
    ]
