# Generated by Django 5.2.16 on 2026-09-15 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0002_move_productmedia_from_product_app"),
        ("thumbnail", "0005_thumbnail_media_owner_indexes"),
    ]

    # Django state only: `product_media` already references the same table, which
    # `ProductMedia` keeps after moving to the media app.
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="thumbnail",
                    name="product_media",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thumbnails",
                        to="media.productmedia",
                    ),
                ),
            ],
        ),
    ]
