# Generated by Django 2.0.2 on 2018-02-06 15:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("account", "0016_auto_20180108_0814")]

    operations = [
        migrations.AlterModelTable(name="address", table=None),
        migrations.AlterModelTable(name="user", table=None),
    ]
