# Generated by Django 2.0.3 on 2018-07-18 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_unique_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('view_user', 'Can view users'), ('edit_user', 'Can edit users'), ('view_staff', 'Can view staff'), ('edit_staff', 'Can edit staff'), ('impersonate_user', 'Can impersonate users'))},
        ),
    ]
