# Generated by Django 2.0.3 on 2018-07-19 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20180718_0956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('manage_users', 'Capability to view, create, modify, and delete customers.'), ('manage_staff', 'Capability to view, create, modify and delete staff users.'), ('impersonate_users', 'Capability to impersonate the customers.'))},
        ),
    ]
