# Generated by Django 2.0.3 on 2018-08-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_auto_20180719_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_change_requested_on',
            field=models.DateTimeField(null=True),
        ),
    ]
