# Generated by Django 2.0.3 on 2018-08-20 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_auto_20180801_1808'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='Organization',
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'permissions': (('manage_organizations', 'Manage organizations'),)},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='company',
            new_name='organization',
        ),
    ]
