# Generated by Django 2.1.7 on 2019-03-14 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("account", "0024_auto_20181011_0737")]

    operations = [
        migrations.AlterModelOptions(name="address", options={"ordering": ("pk",)})
    ]
