# Generated by Django 2.2.3 on 2019-07-19 12:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations

import saleor.core.utils.json_serializer


class Migration(migrations.Migration):

    dependencies = [("account", "0029_user_meta")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="meta",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True,
                default=dict,
                encoder=saleor.core.utils.json_serializer.CustomJsonEncoder,
                null=True,
            ),
        )
    ]
