# Generated by Django 2.2.9 on 2020-01-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0037_auto_20191219_0944"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceaccount",
            name="permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this service.",
                related_name="service_set",
                related_query_name="service",
                to="auth.Permission",
            ),
        ),
    ]
