# Generated by Django 2.2.10 on 2020-02-21 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0038_auto_20200123_0034"),
    ]

    operations = [
        migrations.RenameField(
            model_name="serviceaccount", old_name="meta", new_name="metadata",
        ),
        migrations.RenameField(
            model_name="serviceaccount",
            old_name="private_meta",
            new_name="private_metadata",
        ),
        migrations.RenameField(
            model_name="user", old_name="meta", new_name="metadata",
        ),
        migrations.RenameField(
            model_name="user", old_name="private_meta", new_name="private_metadata",
        ),
    ]
