# Generated by Django 3.0.5 on 2020-04-15 09:43

from django.db import migrations


def change_extension_permission_to_plugin_permission(apps, schema_editor):
    permission = apps.get_model("auth", "Permission")
    users = apps.get_model("account", "User")
    plugin_permission = permission.objects.get(
        codename="manage_plugins", content_type__app_label="plugins"
    )
    extension_permission = permission.objects.get(
        codename="manage_plugins", content_type__app_label="extensions"
    )
    users = users.objects.filter(
        user_permissions__content_type__app_label="extensions",
        user_permissions__codename="manage_plugins",
    )
    for user in users:
        user.user_permissions.remove(extension_permission)
        user.user_permissions.add(plugin_permission)


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0039_auto_20200221_0257"),
    ]

    operations = [
        migrations.RunPython(change_extension_permission_to_plugin_permission),
    ]
