# Generated by Django 3.0.5 on 2020-04-16 06:00

from django.db import migrations, models


# TODO Apply step to move SA permission to MANAFGE APPS
class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_migrate_metadata"),
        ("auth", "0011_update_proxy_permissions"),
        ("webhook", "0002_webhook_name"),
        ("account", "0039_auto_20200221_0257"),
    ]

    operations = [
        migrations.RenameModel(old_name="ServiceAccount", new_name="App",),
        migrations.RenameModel(old_name="ServiceAccountToken", new_name="AppToken",),
        migrations.AlterModelOptions(
            name="app",
            options={"permissions": (("manage_app", "Manage service account"),)},
        ),
        migrations.AlterModelTable(name="app", table="app_app",),
        migrations.AlterModelTable(name="apptoken", table="app_apptoken",),
        migrations.RenameField(
            model_name="apptoken", old_name="service_account", new_name="app",
        ),
        migrations.AlterModelOptions(
            name="app", options={"permissions": (("manage_app", "Manage app"),)},
        ),
        migrations.AlterField(
            model_name="app",
            name="permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this app.",
                related_name="app_set",
                related_query_name="app",
                to="auth.Permission",
            ),
        ),
    ]
