# Generated by Django 3.0.5 on 2020-04-23 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0040_auto_20200423_0425"),
        ("account", "0042_merge_20200422_0555"),
    ]

    operations = []
