# Generated by Django 3.0.5 on 2020-04-23 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0043_merge_20200423_0653"),
        ("account", "0044_unmount_app_and_app_token"),
    ]

    operations = []
