# Generated by Django 3.1.7 on 2021-03-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0048_auto_20210308_1135"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="language_code",
            field=models.CharField(
                choices=[
                    ("ar", "Arabic"),
                    ("az", "Azerbaijani"),
                    ("bg", "Bulgarian"),
                    ("bn", "Bengali"),
                    ("ca", "Catalan"),
                    ("cs", "Czech"),
                    ("da", "Danish"),
                    ("de", "German"),
                    ("el", "Greek"),
                    ("en", "English"),
                    ("es", "Spanish"),
                    ("es-co", "Colombian Spanish"),
                    ("et", "Estonian"),
                    ("fa", "Persian"),
                    ("fi", "Finnish"),
                    ("fr", "French"),
                    ("hi", "Hindi"),
                    ("hu", "Hungarian"),
                    ("hy", "Armenian"),
                    ("id", "Indonesian"),
                    ("is", "Icelandic"),
                    ("it", "Italian"),
                    ("ja", "Japanese"),
                    ("ka", "Georgian"),
                    ("km", "Khmer"),
                    ("ko", "Korean"),
                    ("lt", "Lithuanian"),
                    ("mn", "Mongolian"),
                    ("my", "Burmese"),
                    ("nb", "Norwegian"),
                    ("nl", "Dutch"),
                    ("pl", "Polish"),
                    ("pt", "Portuguese"),
                    ("pt-br", "Brazilian Portuguese"),
                    ("ro", "Romanian"),
                    ("ru", "Russian"),
                    ("sk", "Slovak"),
                    ("sl", "Slovenian"),
                    ("sq", "Albanian"),
                    ("sr", "Serbian"),
                    ("sv", "Swedish"),
                    ("sw", "Swahili"),
                    ("ta", "Tamil"),
                    ("th", "Thai"),
                    ("tr", "Turkish"),
                    ("uk", "Ukrainian"),
                    ("vi", "Vietnamese"),
                    ("zh-hans", "Simplified Chinese"),
                    ("zh-hant", "Traditional Chinese"),
                ],
                default="en",
                max_length=35,
            ),
        ),
    ]
