# Generated by Django 3.1.7 on 2021-05-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0049_user_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_supplier',
            field=models.BooleanField(default=False),
        ),
    ]
