# Generated by Django 3.2.2 on 2021-06-01 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0050_auto_20210506_1058"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="default_shipping_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_user_shipping",
                to="account.address",
            ),
        ),
    ]
