# Generated by Django 3.2.6 on 2021-08-25 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0053_auto_20210719_1048"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ("email",),
                "permissions": (
                    ("manage_users", "Manage customers."),
                    ("manage_staff", "Manage staff."),
                    ("impersonate_user", "Impersonate user."),
                ),
            },
        ),
    ]
