# Generated by Django 3.2.6 on 2021-11-22 09:28

import django.contrib.postgres.indexes
from django.db import migrations, models

BATCH_SIZE = 10000


def set_search_document(apps, schema_editor):
    User = apps.get_model("account", "User")

    users = []
    for user in User.objects.iterator():
        user.search_document = prepare_search_document_value(user)
        users.append(user)

    User.objects.bulk_update(users, ["search_document"], batch_size=BATCH_SIZE)


def prepare_search_document_value(user):
    search_document = f"{user.email}{user.first_name}{user.last_name}"

    for address in user.addresses.all():
        search_document += (
            f"{address.first_name}{address.last_name}"
            f"{address.street_address_1}{address.street_address_2}"
            f"{address.city}{address.postal_code}{address.country}{address.phone}"
        )

    search_document = search_document.replace(" ", "").lower()

    return search_document


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0056_merge_20210903_0640"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="search_document",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.RunPython(set_search_document, migrations.RunPython.noop),
        migrations.RemoveIndex(
            model_name="user",
            name="user_search_gin",
        ),
        migrations.AddIndex(
            model_name="user",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["email", "first_name", "last_name"],
                name="order_user_search_gin",
                opclasses=["gin_trgm_ops", "gin_trgm_ops", "gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_document"],
                name="user_search_gin",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
