# Generated by Django 3.2.12 on 2022-02-18 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0124_alter_order_token"),
        ("account", "0058_update_user_search_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerevent",
            name="order_on_token",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customer_events",
                to="order.order",
                to_field="token",
            ),
        ),
    ]
