# Generated by Django 3.2.12 on 2022-02-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0058_update_user_search_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(null=True, db_index=True),
        ),
    ]
