# Generated by Django 3.2.12 on 2022-02-18 09:21

from django.db import migrations

BATCH_SIZE = 10000


def set_order_token_relation(apps, schema_editor):
    CustomerEvent = apps.get_model("account", "CustomerEvent")
    Order = apps.get_model("order", "Order")

    queryset = CustomerEvent.objects.filter(order_id__isnull=False)
    for batch_pks in queryset_in_batches(queryset):
        batch = CustomerEvent.objects.filter(pk__in=batch_pks)
        order_ids = batch.values_list("order_id", flat=True)
        order_in_bulk = Order.objects.in_bulk(order_ids)
        for event in batch:
            event.order_on_token = order_in_bulk.get(event.order_id)

        CustomerEvent.objects.bulk_update(batch, ["order_on_token"])


def queryset_in_batches(queryset):
    """Slice a queryset into batches.

    Input queryset should be sorted be pk.
    """
    start_pk = 0

    while True:
        qs = queryset.filter(pk__gt=start_pk)[:BATCH_SIZE]
        pks = list(qs.values_list("pk", flat=True))

        if not pks:
            break

        yield pks

        start_pk = pks[-1]


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0059_order_on_token"),
    ]

    operations = [
        migrations.RunPython(
            set_order_token_relation, reverse_code=migrations.RunPython.noop
        ),
    ]
