# Generated by Django 3.2.12 on 2022-02-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0061_populate_user_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
