# Generated by Django 3.2.12 on 2022-02-25 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0131_change_pk_to_uuid"),
        ("account", "0063_save_customerevent_order_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerevent",
            name="order_token",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customer_events",
                to="order.order",
            ),
        ),
        migrations.RemoveField(
            model_name="customerevent",
            name="order",
        ),
        migrations.RenameField(
            model_name="customerevent",
            old_name="order_token",
            new_name="order",
        ),
        migrations.AlterField(
            model_name="customerevent",
            name="order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="order.order",
            ),
        ),
    ]
