# Generated by Django 3.2.16 on 2022-12-27 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0063_user_user_p_meta_jsonb_path_idx"),
        ("account", "0064_rewrite_customerevent_order_relation"),
    ]

    operations = []
