# Generated by Django 3.2.16 on 2022-12-27 13:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0065_address_warehouse_address_search_gin"),
        ("account", "0065_merge_20221227_1254"),
    ]

    operations = []
