# Generated by Django 3.2.14 on 2022-07-15 14:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0066_alter_customerevent_type"),
        ("account", "0066_alter_user_avatar"),
    ]

    operations = []
