# Generated by Django 3.2.16 on 2022-11-29 09:50

from django.db import migrations, models
import saleor.account.models


class Migration(migrations.Migration):

    dependencies = [
        ("permission", "0001_initial"),
        ("account", "0070_alter_user_uuid"),
        ("app", "0017_app_audience"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=("ALTER TABLE auth_group RENAME TO account_group"),
                    reverse_sql=("ALTER TABLE account_group RENAME TO auth_group"),
                ),
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE auth_group_permissions RENAME TO account_group_permissions"  # noqa: E501
                    ),
                    reverse_sql=(
                        "ALTER TABLE account_group_permissions RENAME TO auth_group_permissions"  # noqa: E501
                    ),
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="Group",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "name",
                            models.CharField(
                                max_length=150, unique=True, verbose_name="name"
                            ),
                        ),
                        (
                            "permissions",
                            models.ManyToManyField(
                                blank=True,
                                to="auth.Permission",
                                verbose_name="permissions",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "group",
                        "verbose_name_plural": "groups",
                    },
                    managers=[
                        ("objects", saleor.account.models.GroupManager()),
                    ],
                ),
            ],
        ),
    ]
