# Generated by Django 3.2.16 on 2022-12-27 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0066_merge_20221227_1315"),
        ("account", "0070_alter_user_uuid"),
    ]

    operations = []
