# Generated by Django 3.2.16 on 2022-12-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0070_alter_user_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="external_reference",
            field=models.CharField(
                blank=True, db_index=True, max_length=250, null=True, unique=True
            ),
        ),
    ]
