# Generated by Django 3.2.18 on 2023-02-21 09:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0064_user_last_password_reset_request"),
        ("account", "0071_merge_0066_merge_20221227_1315_0070_alter_user_uuid"),
    ]

    operations = []
