# Generated by Django 3.2.16 on 2022-12-27 13:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0071_merge_0066_merge_20221227_1315_0070_alter_user_uuid"),
        ("account", "0071_user_external_reference"),
    ]

    operations = []
