# Generated by Django 3.2.16 on 2023-01-02 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0072_merge_20221227_1353"),
        ("account", "0073_alter_group_permissions"),
    ]

    operations = []
