# Generated by Django 3.2.18 on 2023-02-21 10:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0072_merge_20230221_0956"),
        ("account", "0075_add_address_metadata"),
    ]

    operations = []
