# Generated by Django 3.2.16 on 2023-01-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channel", "0005_channel_allocation_strategy"),
        ("account", "0075_add_address_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="channels",
            field=models.ManyToManyField(blank=True, to="channel.Channel"),
        ),
        migrations.AddField(
            model_name="group",
            name="restrictedAccessToChannel",
            field=models.BooleanField(default=False),
        ),
    ]
