# Generated by Django 3.2.18 on 2023-03-10 11:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0076_fill_empty_passwords"),
        ("account", "0076_merge_20230221_1002"),
    ]

    operations = []
