# Generated by Django 3.2.18 on 2023-03-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channel", "0008_update_null_order_settings"),
        ("account", "0077_merge_20230310_1107"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="channels",
            field=models.ManyToManyField(blank=True, to="channel.Channel"),
        ),
        migrations.AddField(
            model_name="group",
            name="restricted_access_to_channels",
            field=models.BooleanField(default=False),
        ),
        migrations.RunSQL(
            """
                ALTER TABLE account_group
                ALTER COLUMN restricted_access_to_channels
                SET DEFAULT false;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
