# Generated by Django 3.2.22 on 2023-12-05 13:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0082_auto_20231204_1419"),
        ("account", "0082_user_last_confirm_email_request"),
    ]

    operations = []
