# Generated by Django 3.2.24 on 2024-05-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0084_merge_20240229_1435"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="validation_skipped",
            field=models.BooleanField(default=False),
        ),
        migrations.RunSQL(
            """
                ALTER TABLE account_address
                ALTER COLUMN validation_skipped
                SET DEFAULT false;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
