# Generated by Django 3.2.25 on 2024-07-22 17:53

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0085_address_validation_skipped"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="user",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Upper("first_name"),
                    name="gin_trgm_ops",
                ),
                name="upper_first_name_gin",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Upper("last_name"),
                    name="gin_trgm_ops",
                ),
                name="upper_last_name_gin",
            ),
        ),
    ]
