# Generated by Django 3.2.24 on 2024-06-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0085_address_validation_skipped"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="address",
                    name="phone",
                    field=models.CharField(
                        blank=True, db_index=True, default="", max_length=128
                    ),
                )
            ]
        ),
    ]
