# Generated by Django 4.2.20 on 2025-05-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0086_auto_20240805_0851"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, unique=True, verbose_name="name"),
                ),
                (
                    "customers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="customer_groups",
                        to="account.user",
                        verbose_name="customers",
                    ),
                ),
            ],
        ),
    ]
