# Generated by Django 3.2.25 on 2024-07-25 08:48

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0086_auto_20240723_1741"),
    ]
    atomic = False

    operations = [
        AddIndexConcurrently(
            model_name="user",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["first_name"], name="first_name_gin", opclasses=["gin_trgm_ops"]
            ),
        ),
        AddIndexConcurrently(
            model_name="user",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["last_name"], name="last_name_gin", opclasses=["gin_trgm_ops"]
            ),
        ),
        AddIndexConcurrently(
            model_name="user",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["full_name"],
                name="user_full_name_gin",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
