# Generated by Django 5.2.1 on 2025-06-23 11:17

from django.contrib.postgres.indexes import BTreeIndex
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("account", "0088_user_user_date_joined_idx"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="user",
            index=BTreeIndex(fields=["email"], name="user_email_idx"),
        ),
    ]
