# Generated by Django 5.2.1 on 2025-06-25 09:45

from django.contrib.postgres.indexes import BTreeIndex
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("account", "0091_populate_user_number_of_orders"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="address",
            index=BTreeIndex(fields=["country"], name="address_country_idx"),
        ),
    ]
