# Generated by Django 5.2.1 on 2025-06-27 07:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0093_user_user_number_of_orders_idx"),
    ]

    # empty migration for consistency, the populating task called in 0095
    operations = []
