# Generated by Django 5.2.8 on 2025-12-29 11:57

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("account", "0096_user_search_vector"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="user",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="user_tsearch"
            ),
        ),
    ]
