# Generated by Django 5.2.15 on 2026-07-13 09:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0099_remove_digitalcontent_customerevent_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ("email",),
                "permissions": (
                    ("manage_users", "Manage customers."),
                    ("manage_staff", "Manage staff."),
                    ("impersonate_user", "Impersonate user."),
                    ("read_users", "Read customers."),
                    ("read_staff", "Read staff."),
                ),
            },
        ),
    ]
