# Generated by Django 5.2.15 on 2026-07-21 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0100_customertype"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="customer_type",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="account.customertype",
            ),
        ),
    ]
