# Generated by Django 5.2.16 on 2026-09-08 12:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0100_alter_user_options"),
        ("account", "0105_add_manage_customer_types_and_attributes_perm"),
    ]

    operations = []
