# Generated by Django 5.2.15 on 2026-08-07 07:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0100_remove_digital_link_from_customerevent_type"),
        ("account", "0105_add_manage_customer_types_and_attributes_perm"),
    ]

    operations = []
