# Generated by Django 5.2.16 on 2026-09-09 07:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0106_merge_20260908_1207"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customertype",
            options={
                "ordering": ("slug",),
                "permissions": (
                    (
                        "manage_customer_types_and_attributes",
                        "Manage customer types and attributes.",
                    ),
                    (
                        "read_customer_types_and_attributes",
                        "Read customer types and attributes.",
                    ),
                ),
            },
        ),
    ]
