/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type PaymentGatewayInitializeTokenizationSession =
  | PaymentMethodTokenizationSuccess
  | PaymentMethodTokenizationPending
  | PaymentMethodTokenizationFailed;
/**
 * ID of the payment method.
 */
export type Id = string;
/**
 * Result of the payment method tokenization.
 */
export type Result = "SUCCESSFULLY_TOKENIZED" | "ADDITIONAL_ACTION_REQUIRED";
/**
 * A data passes to the client.
 */
export type JsonValue =
  | string
  | number
  | boolean
  | {
      [k: string]: unknown;
    }
  | unknown[]
  | null;
/**
 * ID of the payment method.
 */
export type Id1 = string | null;
/**
 * Result of the payment method tokenization.
 */
export type Result1 = "PENDING";
/**
 * A data passes to the client.
 */
export type JsonValue1 =
  | string
  | number
  | boolean
  | {
      [k: string]: unknown;
    }
  | unknown[]
  | null;
/**
 * Result of the payment method tokenization.
 */
export type Result2 = "FAILED_TO_TOKENIZE" | "FAILED_TO_DELIVER";
/**
 * Error message that will be passed to the frontend.
 */
export type Error = string | null;

export interface PaymentMethodTokenizationSuccess {
  id: Id;
  result: Result;
  data?: JsonValue;
  [k: string]: unknown;
}
export interface PaymentMethodTokenizationPending {
  id?: Id1;
  result: Result1;
  data?: JsonValue1;
  [k: string]: unknown;
}
export interface PaymentMethodTokenizationFailed {
  result: Result2;
  error?: Error;
  [k: string]: unknown;
}
