# Generated by Django 3.2.10 on 2021-12-22 21:11

import datetime

from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("customer_group", "0002_alter_customergroup_customers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customergroup",
            name="date",
        ),
        migrations.AddField(
            model_name="customergroup",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2021, 12, 22, 21, 11, 24, 658318, tzinfo=utc),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customergroup",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="customergroup",
            name="customers",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="customergroup",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customergroup",
            name="name",
            field=models.CharField(db_index=True, max_length=256),
        ),
    ]
