# Generated by Django 3.2.10 on 2021-12-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0155_merge_20211208_1108"),
        ("customer_group", "0003_auto_20211222_2111"),
    ]

    operations = [
        migrations.AddField(
            model_name="customergroup",
            name="variants",
            field=models.ManyToManyField(to="product.ProductVariant"),
        ),
    ]
