# Generated by Django 3.2.12 on 2022-05-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom',
            name='pick_date',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
