# Generated by Django 3.2.12 on 2022-05-21 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0002_custom_pick_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom',
            name='new_feature',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
