# Generated by Django 3.1.7 on 2021-04-29 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
