# Generated by Django 3.1.7 on 2021-04-29 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210419_1512'),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social',
            old_name='action',
            new_name='follow',
        ),
        migrations.AddField(
            model_name='social',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='socials', to='store.store'),
        ),
    ]
