# Generated by Django 3.1.7 on 2021-05-10 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20210504_1407'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Social',
        ),
    ]
