# Generated by Django 3.2.5 on 2021-07-19 13:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("giftcard", "0006_auto_20210719_1117"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="giftcard",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="giftcard",
            name="user",
        ),
    ]
