# Generated by Django 3.2.5 on 2021-08-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("giftcard", "0007_auto_20210719_1311"),
    ]

    operations = [
        migrations.AlterField(
            model_name="giftcard",
            name="expiry_period_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("day", "Day"),
                    ("week", "Week"),
                    ("month", "Month"),
                    ("year", "Year"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.RemoveField(
            model_name="giftcard",
            name="expiry_period",
        ),
        migrations.RemoveField(
            model_name="giftcard",
            name="expiry_period_type",
        ),
        migrations.RemoveField(
            model_name="giftcard",
            name="expiry_type",
        ),
        migrations.AlterField(
            model_name="giftcardevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("issued", "The gift card was created be staff user or app."),
                    ("bought", "The gift card was bought by customer."),
                    ("updated", "The gift card was updated."),
                    ("activated", "The gift card was activated."),
                    ("deactivated", "The gift card was deactivated."),
                    ("balance_reset", "The gift card balance was reset."),
                    ("expiry_date_updated", "The gift card expiry date was updated."),
                    ("tag_updated", "The gift card tag was updated."),
                    ("sent_to_customer", "The gift card was sent to the customer."),
                    ("resent", "The gift card was resent to the customer."),
                    ("note_added", "A note was added to the gift card."),
                    ("used_in_order", "The gift card was used in order."),
                ],
                max_length=255,
            ),
        ),
    ]
