# Generated by Django 3.2.6 on 2021-10-07 05:46

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("giftcard", "0009_giftcard_fulfillment_line"),
    ]

    operations = [
        migrations.CreateModel(
            name="GiftCardTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={"ordering": ("name",)},
        ),
        migrations.RemoveIndex(
            model_name="giftcard",
            name="giftcard_p_meta_idx",
        ),
        migrations.RemoveIndex(
            model_name="giftcard",
            name="giftcard_meta_idx",
        ),
        migrations.RemoveIndex(
            model_name="giftcard",
            name="giftcard_search_gin",
        ),
        migrations.AddField(
            model_name="giftcard",
            name="tags",
            field=models.ManyToManyField(
                related_name="gift_cards", to="giftcard.GiftCardTag"
            ),
        ),
        migrations.AddIndex(
            model_name="giftcardtag",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"],
                name="gift_card_tag_search_gin",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
