# Generated by Django 4.0.8 on 2022-10-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("giftcard", "0015_rename_created_giftcard_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="giftcard",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
