# Generated by Django 3.2.15 on 2023-01-04 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("giftcard", "0016_alter_giftcard_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="giftcard",
            name="code",
            field=models.CharField(
                db_index=True,
                max_length=16,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(8)],
            ),
        ),
    ]
