# Generated by Django 3.2.16 on 2023-02-01 12:42

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("giftcard", "0017_alter_giftcard_code"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="giftcard",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["private_metadata"], name="giftcard_p_meta_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="giftcard",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["metadata"], name="giftcard_meta_idx"
            ),
        ),
    ]
