# Generated by Django 3.2.18 on 2023-06-23 08:57

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
from django.contrib.postgres.operations import AddIndexConcurrently


class Migration(migrations.Migration):
    dependencies = [
        ("giftcard", "0018_metadata_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="giftcard",
            name="search_index_dirty",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="giftcard",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                blank=True, null=True
            ),
        ),
        AddIndexConcurrently(
            model_name="giftcard",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"],
                name="giftcard_tsearch",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
