# Generated by Django 5.2 on 2025-04-18 10:39

from django.db import migrations, models

import saleor.core.utils.json_serializer


class Migration(migrations.Migration):
    dependencies = [
        ("giftcard", "0020_search_vector_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="giftcard",
            name="metadata",
            field=models.JSONField(
                blank=True,
                db_default={},
                default=dict,
                encoder=saleor.core.utils.json_serializer.CustomJsonEncoder,
            ),
        ),
        migrations.AlterField(
            model_name="giftcard",
            name="private_metadata",
            field=models.JSONField(
                blank=True,
                db_default={},
                default=dict,
                encoder=saleor.core.utils.json_serializer.CustomJsonEncoder,
            ),
        ),
    ]
