# Generated by Django 5.2 on 2025-05-27 12:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("giftcard", "0021_alter_giftcard_current_balance_amount_and_more"),
        ("giftcard", "0021_alter_giftcard_metadata_and_more"),
    ]

    operations = []
