# Generated by Django 5.2.8 on 2026-01-30 12:58

from django.apps import apps as registry
from django.db import migrations
from django.db.models.signals import post_migrate

from .tasks.saleor3_22 import mark_gift_cards_search_index_as_dirty_task


def mark_gift_cards_search_index_as_dirty(apps, _schema_editor):
    def on_migrations_complete(sender=None, **kwargs):
        mark_gift_cards_search_index_as_dirty_task.delay()

    sender = registry.get_app_config("attribute")
    post_migrate.connect(on_migrations_complete, weak=False, sender=sender)


class Migration(migrations.Migration):
    dependencies = [
        ("giftcard", "0022_merge_20250527_1210"),
    ]

    operations = [
        migrations.RunPython(
            mark_gift_cards_search_index_as_dirty, migrations.RunPython.noop
        ),
    ]
