# Generated by Django 5.2.15 on 2026-07-07 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0099_remove_digitalcontent_customerevent_type"),
        ("giftcard", "0024_alter_giftcardevent_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="giftcard",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_gift_cards",
                to="account.user",
            ),
        ),
        migrations.AddField(
            model_name="giftcard",
            name="assigned_to_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="giftcardevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("issued", "The gift card was created be staff user or app."),
                    ("bought", "The gift card was bought by customer."),
                    ("updated", "The gift card was updated."),
                    ("activated", "The gift card was activated."),
                    ("deactivated", "The gift card was deactivated."),
                    ("balance_reset", "The gift card balance was reset."),
                    ("expiry_date_updated", "The gift card expiry date was updated."),
                    ("tags_updated", "The gift card tags were updated."),
                    ("sent_to_customer", "The gift card was sent to the customer."),
                    ("resent", "The gift card was resent to the customer."),
                    ("note_added", "A note was added to the gift card."),
                    ("used_in_order", "The gift card was used in order."),
                    ("refunded_in_order", "The gift card was refunded in order."),
                    (
                        "balance_adjusted",
                        "The gift card balance was adjusted by a delta.",
                    ),
                ],
                max_length=255,
            ),
        ),
    ]
