# Generated by Django 5.2.16 on 2026-09-08 12:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("giftcard", "0025_giftcard_customer_assignment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="giftcard",
            options={
                "ordering": ("code",),
                "permissions": (
                    ("manage_gift_card", "Manage gift cards."),
                    ("read_gift_card", "Read gift cards."),
                ),
            },
        ),
    ]
