# Generated by Django 5.2.15 on 2026-07-09 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0099_remove_digitalcontent_customerevent_type"),
        ("giftcard", "0026_giftcard_assigned_to_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="giftcard",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assigned_gift_cards",
                to="account.user",
            ),
        ),
    ]
