# Generated by Django 5.2.8 on 2026-02-27 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0006_purchaseorderitem_quantity_fulfilled"),
        ("warehouse", "0040_fulfillmentsource"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("confirmed", "Confirmed"),
                    ("partially_received", "Partially Received"),
                    ("received", "Received"),
                ],
                default="draft",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="PurchaseOrderRequestedAllocation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_order_requested_allocations",
                        to="warehouse.allocation",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requested_allocations",
                        to="inventory.purchaseorder",
                    ),
                ),
            ],
            options={
                "unique_together": {("purchase_order", "allocation")},
            },
        ),
    ]
