# Generated by Django 5.2.8 on 2026-02-27 15:52

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0007_purchaseorder_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorderitem",
            name="country_of_origin",
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, null=True
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderitem",
            name="currency",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorderitem",
            name="total_price_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Total invoice amount. Null until set from price list.",
                max_digits=20,
                null=True,
            ),
        ),
    ]
