# Generated by Django 5.2.8 on 2026-03-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0011_purchase_order_add_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="currency",
            field=models.CharField(blank=True, default="", max_length=3),
        ),
    ]
