# Generated by Django 5.2.8 on 2026-03-10 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channel", "0027_channel_allow_legacy_gift_card_use"),
        ("inventory", "0013_alter_purchaseorderitem_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="channel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_orders",
                to="channel.channel",
            ),
        ),
    ]
