# Generated by Django 3.0.6 on 2020-06-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("csv", "0003_auto_20200520_0247"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("export_pending", "Data export was started."),
                    ("export_success", "Data export was completed successfully."),
                    ("export_failed", "Data export failed."),
                    ("export_deleted", "Export file was started."),
                    (
                        "exported_file_sent",
                        "Email with link to download file was sent to the customer.",
                    ),
                    (
                        "Export_failed_info_sent",
                        "Email with info that export failed was sent to the customer.",
                    ),
                ],
                max_length=255,
            ),
        ),
    ]
