# Generated by Django 2.0.8 on 2018-09-13 13:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("order", "0058_remove_orderevent_parameters")]

    operations = [
        migrations.RenameField(
            model_name="orderevent", old_name="parameters_new", new_name="parameters"
        )
    ]
