# Generated by Django 3.2.2 on 2021-07-12 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_auto_20210308_1135"),
        ("order", "0112_auto_20210616_0548"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderevent",
            name="app",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="app.app",
            ),
        ),
    ]
