# Generated by Django 3.2.6 on 2021-08-20 14:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0114_alter_order_language_code"),
        ("order", "0114_auto_20210722_1146"),
    ]

    operations = []
