# Generated by Django 3.2.6 on 2021-09-03 10:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0115_alter_order_language_code"),
        ("order", "0116_merge_20210824_1103"),
    ]

    operations = []
