# Generated by Django 3.2.16 on 2022-12-15 12:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0152_merge_20221215_1217"),
        ("order", "0154_auto_20220621_0850"),
    ]

    operations = []
