# Generated by Django 3.2.16 on 2022-12-15 12:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0155_merge_20221215_1223"),
        ("order", "0155_order_should_refresh_prices"),
    ]

    operations = []
