# Generated by Django 3.2.22 on 2023-11-22 08:58

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("order", "0170_merge_20231030_0857"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="order",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["user_email", "user_id"], name="order_user_email_user_id_idx"
            ),
        ),
    ]
