# Generated by Django 3.2.19 on 2023-05-18 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0170_auto_20230529_1314"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordergrantedrefund",
            name="shipping_costs_included",
            field=models.BooleanField(default=False),
        ),
        migrations.RunSQL(
            "ALTER TABLE order_ordergrantedrefund ALTER COLUMN shipping_costs_included "
            "SET DEFAULT false;",
            migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name="OrderGrantedRefundLine",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "granted_refund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="order.ordergrantedrefund",
                    ),
                ),
                (
                    "order_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="granted_refund_lines",
                        to="order.orderline",
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, null=True, default=""),
                ),
            ],
        ),
    ]
