# Generated by Django 3.2.22 on 2023-11-22 13:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0175_merge_20231030_1040"),
        ("order", "0175_merge_20231122_1040"),
    ]

    operations = []
