# Generated by Django 3.2.25 on 2024-06-06 10:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0173_alter_orderline_unit_discount_type_add_is_price_overridden"),
        ("order", "0176_merge_20240325_1315"),
    ]

    operations = []
