# Generated by Django 3.2.22 on 2024-03-25 13:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0177_merge_20240325_1329"),
        ("order", "0179_merge_20231122_1348"),
    ]

    operations = []
