# Generated by Django 3.2.25 on 2024-06-06 13:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0178_merge_20240606_1036"),
        ("order", "0180_merge_20240325_1333"),
    ]

    operations = []
