# Generated by Django 3.2.23 on 2024-03-06 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0056_merge_20231213_0755"),
        ("order", "0184_merge_0182_merge_20240325_1338_0183_order_tax_error"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordergrantedrefund",
            name="transaction_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="granted_refund",
                to="payment.transactionitem",
            ),
        ),
        migrations.AddField(
            model_name="ordergrantedrefund",
            name="status",
            field=models.CharField(
                choices=[
                    ("none", "The refund on related transactionItem is not processed"),
                    ("pending", "The refund on related transactionItem is pending"),
                    (
                        "success",
                        "The refund on related transactionItem is successfully "
                        "processed",
                    ),
                    ("failure", "The refund on related transactionItem failed"),
                ],
                default="none",
                max_length=128,
            ),
        ),
        migrations.RunSQL(
            "ALTER TABLE order_ordergrantedrefund ALTER COLUMN status SET DEFAULT 'none';",
            migrations.RunSQL.noop,
        ),
    ]
