# Generated by Django 3.2.25 on 2024-06-24 13:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0187_merge_20240617_1056"),
        ("order", "0187_merge_20240624_1245"),
    ]

    operations = []
