# Generated by Django 3.2.25 on 2024-07-08 09:06

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0190_merge_20240708_0814"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="undiscounted_base_shipping_price_amount",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.0"), max_digits=12
            ),
        ),
        migrations.RunSQL(
            """
            ALTER TABLE order_order
            ALTER COLUMN undiscounted_base_shipping_price_amount
            SET DEFAULT 0;
            """,
            migrations.RunSQL.noop,
        ),
    ]
