# Generated by Django 3.2.23 on 2024-07-26 15:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0191_merge_20240725_0844"),
        ("order", "0191_merge_20240726_1508"),
    ]

    operations = []
