# Generated by Django 3.2.25 on 2024-07-25 08:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0191_alter_order_undiscounted_base_shipping_price_amount"),
        ("order", "0191_merge_20240725_0844"),
    ]

    operations = []
