# Generated by Django 4.2.16 on 2024-10-14 06:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0193_fix_subtotal_value_for_order_from_bulk"),
        ("order", "0194_alter_orderevent_type"),
    ]

    operations = []
