# Generated by Django 4.2.15 on 2024-10-04 08:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0194_alter_orderevent_type"),
        ("order", "0194_merge_20240805_0820"),
    ]

    operations = []
