# Generated by Django 5.2.1 on 2025-06-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0205_merge_20250603_1125"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="lines_count",
            field=models.PositiveIntegerField(),
        ),
    ]
