# Generated by Django 5.2.1 on 2025-06-13 08:34

from django.contrib.postgres.indexes import BTreeIndex
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("order", "0211_order_totalamount_indexes"),
        ("product", "0200_merge_20250527_1210"),
        ("tax", "0011_merge_20250530_0929"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="orderline",
            index=BTreeIndex(
                fields=["product_type_id"], name="product_type_id_btree_idx"
            ),
        ),
    ]
