# Generated by Django 5.2.1 on 2025-06-23 06:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0214_order_order_status_idx"),
        ("order", "0214_orderevent_order_orderevent_date_idx"),
    ]

    operations = []
