# Generated by Django 5.2.1 on 2025-08-08 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0216_merge_20250704_1033"),
        ("page", "0031_alter_page_metadata_alter_page_private_metadata_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordergrantedrefund",
            name="reason_reference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="page.page",
            ),
        ),
    ]
