name: "Changelog check"
on:
  pull_request:
    branches:
      - 'main'
    # The specific activity types are listed here to include "labeled" and "unlabeled"
    # (which are not included by default for the "pull_request" trigger).
    # This is needed to allow skipping enforcement of the changelog in PRs with specific labels,
    # as defined in the (optional) "skipLabels" property.
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]


jobs:
  # Enforces the update of a changelog file on every pull request
  changelog:
    if: github.event.pull_request.draft == false || contains(github.event.pull_request.labels.*.name, 'run CI')
    runs-on: ubuntu-latest
    steps:
    - uses: dangoslen/changelog-enforcer@83e1e992a730c447cca6e9ecf8e7b21cb9a7463e
      with:
        skipLabels: "skip changelog,dependencies,bot"
