name: GraphQL Inspector

on:
  pull_request:
    paths: ["**.graphql"]

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      checks: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: graphql-hive/graphql-inspector@8733c10560f98b868d3eb4db1325c8edf64936b3 # @graphql-inspector/action@5.0.21
        with:
          schema: "${{ github.event.pull_request.base.sha }}:saleor/graphql/schema.graphql"
