name: GraphQL Inspector

on:
  push:
    paths: [ "**.graphql" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: graphql-hive/graphql-inspector@8733c10560f98b868d3eb4db1325c8edf64936b3 # @graphql-inspector/action@5.0.21
        with:
          schema: "3.22:saleor/graphql/schema.graphql"
