name: Notify Discord on Help Wanted Issue

on:
  # We are limiting secrets and not using untrusted inputs for anything
  # dangerous (e.g., building or executing commands).
  # nosemgrep: yaml.github-actions.security.audit.dangerous-event-type
  issues:
    types: [labeled]

permissions: {}

jobs:
  notify:
    if: github.event.label.name == 'help wanted'

    permissions: {}

    runs-on: ubuntu-latest
    environment: discord-notifier

    steps:
      - name: Send notification to Discord
        uses: appleboy/discord-action@6047e1fe519c24dbf2865cf0557f20f51f075b3e # v1.2.0
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: |
            🎉 New Issue Labeled with "Help Wanted" in Saleor Core

            **Issue Details:**
            - Title: ${{ github.event.issue.title }}
            - Number: #${{ github.event.issue.number }}
            - URL: ${{ github.event.issue.html_url }}

            Please take a look and help if you can! 🙏
