name: Migrations performance test

on:
  pull_request:
    types: [labeled, unlabeled, opened, closed]

jobs:
  run:
    name: Run migrations performance test
    if: ${{ (((github.event.action == 'labeled') && (github.event.label.name == 'migrations perf test')) || ((github.event.action == 'opened') && contains(github.event.pull_request.labels.*.name, 'migrations perf test')) && github.repository == 'saleor/saleor') }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write # needed by aws-actions/configure-aws-credentials
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: rlespinasse/github-slug-action@c33ff65466c58d57e4d796f88bb1ae0ff26ee453 # v5.2.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@a03048d87541d1d9fcf2ecf528a4a65ba9bd7838 # v5.0.0
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_TESTENVS_ACCOUNT_ID }}:role/${{ secrets.AWS_TESTENVS_CICD_ROLE_NAME }}
          aws-region: ${{ vars.AWS_TESTENVS_REGION }}

      - name: Build and push
        uses: kciter/aws-ecr-action@ea6db9ecebec495c996b0f084c8ea1591f1185d7 # v5
        with:
          access_key_id: ${{ env.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          account_id: ${{ secrets.AWS_TESTENVS_ACCOUNT_ID }}
          repo: saleor-testenvs
          region: ${{ vars.AWS_TESTENVS_REGION }}
          tags: ${{ env.GITHUB_HEAD_REF_SLUG_URL }},${{ github.sha }}

      - name: Get pull number
        run: |
          echo "PULL_ID=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")" >> $GITHUB_ENV

      - name: Invoke deployment lambda
        uses: gagoar/invoke-aws-lambda@2ea0b5791eba7a9513ddf0fb7f91aa8f098b6458 # v3.4.0
        with:
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ env.AWS_SESSION_TOKEN }}
          REGION: ${{ vars.AWS_TESTENVS_REGION }}
          FunctionName: migrations-perf-test-manager
          Payload: >-
            {
              "action": "${{ github.event.action }}",
              "label": "${{ env.GITHUB_HEAD_REF_SLUG_URL }}",
              "image": "${{ secrets.AWS_TESTENVS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_TESTENVS_REGION }}.amazonaws.com/saleor-testenvs:${{ github.sha }}",
              "pr_id": "${{ env.PULL_ID }}",
              "commit_hash": "${{ github.sha }}"
            }
          LogType: Tail

  cleanup:
    name: Cleanup after migrations performance test
    if: ${{ (((github.event.action == 'unlabeled') && (github.event.label.name == 'migrations perf test')) || ((github.event.action == 'closed') && contains(github.event.pull_request.labels.*.name, 'migrations perf test')) && github.repository == 'saleor/saleor') }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write # needed by aws-actions/configure-aws-credentials
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: rlespinasse/github-slug-action@c33ff65466c58d57e4d796f88bb1ae0ff26ee453 # v5.2.0

      - name: Get pull number
        run: |
          echo "PULL_ID=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@a03048d87541d1d9fcf2ecf528a4a65ba9bd7838 # v5.0.0
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_TESTENVS_ACCOUNT_ID }}:role/${{ secrets.AWS_TESTENVS_CICD_ROLE_NAME }}
          aws-region: ${{ vars.AWS_TESTENVS_REGION }}

      - name: Invoke deployment lambda
        uses: gagoar/invoke-aws-lambda@2ea0b5791eba7a9513ddf0fb7f91aa8f098b6458 # v3.4.0
        with:
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ env.AWS_SESSION_TOKEN }}
          REGION: ${{ vars.AWS_TESTENVS_REGION }}
          FunctionName: migrations-perf-test-manager
          Payload: >-
            {
              "action": "${{ github.event.action }}",
              "label": "${{ env.GITHUB_HEAD_REF_SLUG_URL }}",
              "image": "${{ secrets.AWS_TESTENVS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_TESTENVS_REGION }}.amazonaws.com/saleor-testenvs:${{ github.sha }}",
              "pr_id": "${{ env.PULL_ID }}",
              "commit_hash": "${{ github.sha }}"
            }
          LogType: Tail
