name: Publish for load test

on:
  pull_request:
    types: [reopened, synchronize, labeled]
    branches: ["**"]

permissions: {}

jobs:
  init:
    if: ${{ ((github.event.action == 'labeled') && (github.event.label.name == 'load test')) || ((github.event.action != 'labeled') && contains(github.event.pull_request.labels.*.name, 'load test')) }}
    runs-on: ubuntu-latest
    permissions: {}

    outputs:
      version: ${{ steps.variables.outputs.version }}

    steps:
      - name: Prepare variables
        id: variables
        env:
          HEAD_REF: ${{ github.event.pull_request.head.ref }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          branch_slug=$(echo "$HEAD_REF" | sed 's@/@-@g')
          image_version="${branch_slug}-${HEAD_SHA:0:8}"

          echo "VERSION=${image_version}" >> $GITHUB_OUTPUT

  publish:
    needs: [init]
    permissions:
      contents: read
      id-token: write # needed for AWS/ECR login (not used, but required permission)
      packages: write # needed for GHCR

    uses: ./.github/workflows/publish-containers.yml
    with:
      version: ${{ needs.init.outputs.version }}
      notification-environment: notify-slack-releasing
      publish-environment: publish-load-test
    secrets: inherit

  deploy:
    runs-on: ubuntu-latest
    environment: load-test-deploy
    permissions: {}

    needs:
      - publish

    steps:
      - name: Get Token
        id: get-token
        uses: saleor/saleor-internal-actions/request-vault-token@49a069ae9731cfccf3a1033fe1da4e3da84f4f2a # v1.11.0
        with:
          vault-url: ${{ secrets.VAULT_URL }}
          vault-jwt: ${{ secrets.VAULT_JWT }}

      - name: Trigger load test deployment
        env:
          BRANCH: ${{ github.event.pull_request.base.ref }}
          VERSION: ${{ needs.publish.outputs.version }}
          GITHUB_TOKEN: ${{ steps.get-token.outputs.token }}
        run: |
          payload=$(
              jq --arg version "$VERSION" --arg branch "$BRANCH" --null-input '
                {
                  "event_type": "deploy-load-test",
                  "client_payload": {
                    "branch": $branch,
                    "version": $version
                  }
                }
              '
          )

          gh api /repos/saleor/saleor-multitenant/dispatches --input - <<< "$payload"
