name: Publish main

on:
  push:
    branches:
      - main
      - ci/**

permissions: {}

jobs:
  publish:
    uses: ./.github/workflows/publish-containers.yml

    permissions:
      contents: read
      id-token: write # needed for AWS/ECR login (not used, but required permission)
      packages: write # needed for GHCR

    with:
      prefix: unstable-
      notification-environment: notify-slack-releasing
      publish-environment: publish-main
    secrets: inherit
