name: Test migrations compatibility

on:
  pull_request:
    branches:
      - "3.*"
      - "main"
    paths:
      - "**/migrations/**"
      - .github/workflows/test-migrations-compatibility.yml

env:
  DATABASE_URL: "postgres://saleor:saleor@postgres:5432/saleor"
  SECRET_KEY: ci-test

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.12

    permissions:
      contents: read

    services:
      postgres:
        image: library/postgres:15-alpine
        env:
          POSTGRES_PASSWORD: saleor
          POSTGRES_USER: saleor
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Install system dependencies
        run: |
          apt-get install -y libpq-dev

      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          enable-cache: true

      # Sync dependencies if cache is not hit or there is a partial key match
      - name: Install dependencies
        run: |
          uv sync --locked

      - name: Migrate
        run: |
          export DJANGO_SETTINGS_MODULE=saleor.tests.settings
          uv run python manage.py migrate

      - name: Checkout base
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: ${{ github.event.pull_request.base.sha }}

      # Sync dependencies to ensure consistency with base branch
      - name: Synchronize dependencies
        run: |
          uv sync --locked

      - name: Run tests
        run: |
          export PYTEST_DB_URL="$DATABASE_URL"
          uv run pytest -n 0 --reuse-db
